### PR TITLE
Remove spurious `#[derive(Encode, Decode)]`

### LINKED ISSUE #2742: error: Could not compile `srml-staking`
macos

curl https://sh.rustup.rs -sSf | sh
rustup update nightly
rustup target add wasm32-unknown-unknown --toolchain nightly
rustup update stable
cargo install --git https://github.com/alexcrichton/wasm-gc
brew install cmake pkg-config openssl git llvm

Then
cargo install --force --git https://github.com/paritytech/substrate subkey

It showed that

error[E0277]: the trait bound `usize: _IMPL_DECODE_FOR_RewardDestination::_parity_codec::Encode` is not satisfied
  --> /Users/zhangtong/.cargo/git/checkouts/substrate-7e08433d4c370a21/c93ca93/srml/staking/src/phragmen.rs:75:2
   |
75 |     /// Index of the candidate stored in the 'candidates' vector.
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `_IMPL_DECODE_FOR_RewardDestination::_parity_codec::Encode` is not implemented for `usize`

error[E0277]: the trait bound `usize: _IMPL_DECODE_FOR_RewardDestination::_parity_codec::Decode` is not satisfied
  --> /Users/zhangtong/.cargo/git/checkouts/substrate-7e08433d4c370a21/c93ca93/srml/staking/src/phragmen.rs:75:2
   |
75 |     /// Index of the candidate stored in the 'candidates' vector.
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `_IMPL_DECODE_FOR_RewardDestination::_parity_codec::Decode` is not implemented for `usize`
   |
   = note: required by `_IMPL_DECODE_FOR_RewardDestination::_parity_codec::Decode::decode`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `srml-staking`.

### PR DESCRIPTION
**Pull request by DemiMarie-parity**
They did not compile, since `Encode` and `Decode` are deliberately not
implemented for `usize`.

Fixes #2742.

### CODE REVIEW

**Comment by bkchr** [comment]
(Tests are failing)

File: srml/aura/src/lib.rs [hunk 1]
```diff
@@ -51,6 +51,7 @@
 pub use timestamp;
 
 use rstd::{result, prelude::*};
+use parity_codec::Decode;
```
Comment (tomusdrw) [inline srml/aura/src/lib.rs]: It should be added only in `feature = std`, otherwise will trigger a unused code warning.

Comment (bkchr) [reply srml/aura/src/lib.rs]: Or just move the use statement into `error_to_string`.

Comment (DemiMarie-parity) [reply srml/aura/src/lib.rs]: @bkchr @tomusdrw done
