### PR TITLE
Named reserve

### LINKED ISSUE #7223: Exclusive reserves for pallet-balances
Currently the reserved balances are shared. Every pallets that uses reserve feature should keep a record how much is reserved so later it can unreserve / slash the same amount. Otherwise if deposits changes, a wrong value will be unserved / slashed.

Given that we should always have the reserved amount stored somewhere (or you may have bugs), we should just have pallet-balances (or another pallet) to do the bookkeeping. Also fund reserved by different pallets should not be shared. Reserve from `pallet-identity` cannot be used by `pallet-proxy`. This will simplify code, eliminates a category of bugs, and improve UX (How do I unreserve my money?). 

Examples of extra deposit bookkeeping codes:

https://github.com/paritytech/substrate/blob/596f377d49fede088e0c32791fb72f1343003b0d/frame/identity/src/lib.rs#L377-L378

https://github.com/paritytech/substrate/blob/596f377d49fede088e0c32791fb72f1343003b0d/frame/treasury/src/lib.rs#L275-L276

https://github.com/paritytech/substrate/blob/596f377d49fede088e0c32791fb72f1343003b0d/frame/treasury/src/lib.rs#L295-L296

https://github.com/paritytech/substrate/blob/596f377d49fede088e0c32791fb72f1343003b0d/frame/indices/src/lib.rs#L79

https://github.com/paritytech/substrate/blob/596f377d49fede088e0c32791fb72f1343003b0d/frame/proxy/src/lib.rs#L157-L160

Missing bookkeeping:

https://github.com/paritytech/substrate/blob/596f377d49fede088e0c32791fb72f1343003b0d/frame/elections-phragmen/src/lib.rs#L828

https://github.com/paritytech/substrate/blob/596f377d49fede088e0c32791fb72f1343003b0d/frame/elections-phragmen/src/lib.rs#L581

I suspect some fund may already be locked forever for early Kusama council voters as the deposit have decreased once.

This will at same time closes #6724

### PR DESCRIPTION
**Pull request by xlc**
Closes #7223

Add and implement NamedReservableCurrency
Also move various currency related types out of support trait.rs

TODOs:

- [x] Docs
- [x] Tests

cc @kianenigma 

polkadot companion: https://github.com/paritytech/polkadot/pull/2280

### CODE REVIEW

File: frame/support/src/traits.rs [hunk 1]
```diff
@@ -19,24 +19,28 @@
...
-use bitflags::bitflags;
 use impl_trait_for_tuples::impl_for_tuples;
 
-/// Re-expected for the macro.
+/// Re-export for backward compatibility
+pub use crate::currency::{
+	ExistenceRequirement, BalanceStatus, WithdrawReasons, OnUnbalanced, Imbalance, SignedImbalance,
+	SplitTwoWays, Currency, ReservableCurrency, ReserveIdentifier, NamedReservableCurrency,
+	LockIdentifier, LockableCurrency
+};
```
Comment (shawntabrizi) [inline frame/support/src/traits.rs:41]:
```suggestion
pub use crate::currency::*;
```

**Comment by xlc** [comment]
Not sure if we need a `MaxReserves` here similar to `MaxLocks` for weight calculation. @shawntabrizi wdyt?

**Comment by shawntabrizi** [comment]
@xlc in general yes. Would be good if your API refused to generate a reserve if max reserves was hit.

Because we are dealing with a vector, there is some cost to decoding the vector which increases with the number of items in it and stuff.

File: frame/balances/src/lib.rs [hunk 2]
```diff
@@ -1222,6 +1240,193 @@ impl<T: Config<I>, I: Instance> ReservableCurrency<T::AccountId> for Module<T, I
...
+			.binary_search_by_key(id, |data| data.id)
+			.map(|idx| reserves[idx].amount)
+			.unwrap_or_default()
+	}
+
+	/// Move `value` from the free balance from `who` to their reserved balance.
+	///
+	/// Is a no-op if value to be reserved is zero.
+	fn reserve_named(id: &ReserveIdentifier, who: &T::AccountId, value: Self::Balance) -> DispatchResult {
+		<Self as ReservableCurrency<_>>::reserve(who, value)?;
```
Comment (kianenigma) [inline frame/balances/src/lib.rs:1258]: hmm? you are doing a normal reserved and a named here?

Comment (xlc) [reply frame/balances/src/lib.rs:1258]: named reserve is also a normal reserve so that the value from `reserved_balance` still make sense (reserved balance + free balance == total_balance)

File: frame/balances/src/lib.rs [hunk 3]
```diff
@@ -1222,6 +1240,193 @@ impl<T: Config<I>, I: Instance> ReservableCurrency<T::AccountId> for Module<T, I
...
+				value
+			}
+		})
+	}
+
+	/// Slash from reserved balance, returning the negative imbalance created,
+	/// and any amount that was unable to be slashed.
+	///
+	/// Is a no-op if the value to be slashed is zero.
+	fn slash_reserved_named(
```
Comment (kianenigma) [inline frame/balances/src/lib.rs:1323]: Could foresee having a `trait NamedReserve` or sth and then dropping the `named` postifx, but then I would be worried that by changing an import (`use traits::ReservableCurrency` -> `use traits::NamedReseve`) the semantics of `T::Currency::slash`. 

But correct me if I am wrong, I think rustc is luckily not smart about this and even if only one of the traits is in scope, it would demand the universal function invocation syntax? 

sth to consider overall.

File: frame/balances/src/lib.rs (hunk 2 above)
Comment (kianenigma) [reply frame/balances/src/lib.rs:1258]: ahh okay I thought they were entirely distinct, and you could only do either `Currency::reserved_balance` (which would return only unnamed reserved stuff) and `Currency::named_reserve_balance`. 

But I guess having them linked is beneficial as you can query the grand total reserved of an account which is useful.

File: frame/balances/src/lib.rs (hunk 3 above)
Comment (xlc) [reply frame/balances/src/lib.rs:1323]: Good idea. I think it is possible to create a `struct NamedReserveAdpator<NamedReservableCurrency, Get<ReserveIdentifier>>` that converts `NamedReservableCurrency` into `ReservableCurrency`

File: frame/balances/src/lib.rs [hunk 4]
```diff
@@ -1222,6 +1240,193 @@ impl<T: Config<I>, I: Instance> ReservableCurrency<T::AccountId> for Module<T, I
...
+
+		Reserves::<T, I>::mutate_exists(who, |maybe_reserves| -> Self::Balance {
+			if let Some(reserves) = maybe_reserves.as_mut() {
+				match reserves.binary_search_by_key(id, |data| data.id) {
+					Ok(idx) => {
+						let to_change = cmp::min(reserves[idx].amount, value);
+
+						let remain = <Self as ReservableCurrency<_>>::unreserve(who, to_change);
+
+						// remain should always be zero but just to be defensive here
```
Comment (kianenigma) [inline frame/balances/src/lib.rs:1291]: Idea: write a wrapper for all of these defensive `unwrap_or_default` or `saturating_something` that we do that will still do the same thing, but flip an on-chain emergency button at some point. And one of the best ways to find them is to look for the work `_defensive_`.

@shawntabrizi I think you once mentioned a similar idea. Did it ever make it into an issue? Else I think it can be.

File: frame/balances/src/lib.rs (hunk 3 above)
Comment (xlc) [reply frame/balances/src/lib.rs:1323]: Something similar to what we have here https://github.com/open-web3-stack/open-runtime-module-library/blob/2de1e024781a7744a3aeb82229ebcb555163452a/currencies/src/lib.rs#L448

**Comment by xlc** [comment]
Can't make polkadot companion because too many dependency version conflicts. Will wait until someone updates the Substrate in Polkadot first.

**Comment by gavofyork** [comment]
That's updated now.

**Comment by gavofyork** [comment]
would like an audit on this, but the general direction looks good.

**Comment by bkchr** [comment]
@xlc I know I'm very very very late to this party here.

But what do you think about: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f43f161c9fe18a952282b3c8c0d36010

This would not only save space in the state as we would use only compact integers to represent the names, we could also use much more descriptive names from the runtime. In this example there is the "real" name registration missing. I would expect something that takes the name for the type like `ImACoolReserve` and that would be exposed to the metadata from Balances.

This boilerplate code for implementing this Names trait and the name registration could be done relative easily in some macro from the runtime, something like:

```
register_reserve_names! {
     enum ReserveNames {
         // This would expose `ImACoolReserve` as real name via the metadata
         ImACoolReserve = 1,
         // This is getting a custom name "hello_world" passed.
         ImNotThatCool "hello_world" = 2,
     }
}
```

@kianenigma @shawntabrizi

**Comment by xlc** [comment]
@bkchr Good idea. We can also apply this pattern to many other places (e.g. LockIdentifier). Will explorer it a bit (maybe in another PR).

File: frame/balances/src/lib.rs [hunk 5]
```diff
@@ -1295,6 +1317,194 @@ impl<T: Config<I>, I: Instance> ReservableCurrency<T::AccountId> for Module<T, I
 	}
 }
 
+impl<T: Config<I>, I: Instance> NamedReservableCurrency<T::AccountId> for Module<T, I>  where
+	T::Balance: MaybeSerializeDeserialize + Debug
+{
+	fn reserved_balance_named(id: &ReserveIdentifier, who: &T::AccountId) -> Self::Balance {
+		let reserves = Self::reserves(who);
```
Comment (gavofyork) [inline frame/balances/src/lib.rs:1324]: Note that despite the binary search, this is still `O(named_reservations)` (due to needing the full deserialisation of `Self::reserves`).

**Review by gavofyork — APPROVED** [review]

**Comment by gavofyork** [comment]
will need reworking for the new balances pallet.

File: frame/support/src/traits/tokens/currency/reservable.rs [hunk 6]
```diff
@@ -81,3 +81,65 @@ pub trait ReservableCurrency<AccountId>: Currency<AccountId> {
 		status: BalanceStatus,
 	) -> Result<Self::Balance, DispatchError>;
 }
+
+/// An identifier for a reserve. Used for disambiguating different reserves so that
+/// they can be individually replaced or removed.
+pub type ReserveIdentifier = [u8; 8];
```
Comment (gavofyork) [inline frame/support/src/traits/tokens/currency/reservable.rs:87]: would be better if this were an associated type since we do plan on altering this type in the future.

File: frame/balances/src/lib.rs [hunk 7]
```diff
@@ -1648,6 +1675,191 @@ impl<T: Config<I>, I: 'static> ReservableCurrency<T::AccountId> for Pallet<T, I>
...
+		reserves
+			.binary_search_by_key(id, |data| data.id)
+			.map(|index| reserves[index].amount)
+			.unwrap_or_default()
+	}
+
+	/// Move `value` from the free balance from `who` to their reserved balance.
+	///
+	/// Is a no-op if value to be reserved is zero.
+	fn reserve_named(id: &ReserveIdentifier, who: &T::AccountId, value: Self::Balance) -> DispatchResult {
```
Comment (gavofyork) [inline frame/balances/src/lib.rs:1692]: i'd like another function `ensure_reserved_named`, with the same prototype as this, but which did something roughly equivalent to the following code:

```
fn ensure_reserved_named(id: &ReserveIdentifier, who: &T::AccountId, value: Self::Balance) -> DispatchResult {
  let already = Self:: reserved_balance_named(id, who);
  if already > value { Self::unreserve(already - value); Ok(()) }
  else if value > already { Self::reserve(id, who, value - already) }
  else { Ok(()) }
}
```

File: frame/balances/src/lib.rs [hunk 8]
```diff
@@ -1648,6 +1675,191 @@ impl<T: Config<I>, I: 'static> ReservableCurrency<T::AccountId> for Pallet<T, I>
...
+			};
+			<Self as ReservableCurrency<_>>::reserve(who, value)?;
+			Ok(())
+		})
+	}
+
+	/// Unreserve some funds, returning any amount that was unable to be unreserved.
+	///
+	/// Is a no-op if the value to be unreserved is zero.
+	fn unreserve_named(id: &ReserveIdentifier, who: &T::AccountId, value: Self::Balance) -> Self::Balance {
```
Comment (gavofyork) [inline frame/balances/src/lib.rs:1714]: An additional `unreserve_all_named(id: &ReserveIdentifier, who: &T::AccountId) -> Self::Balance` would be good, roughly equivalent to:

```
fn unreserve_all_named(id: &ReserveIdentifier, who: &T::AccountId) -> Self::Balance {
  let value = Self::reserved_balance_named(id, who);
  Self::unreserve(id, who, value);
  value
}
```

File: frame/balances/src/lib.rs [hunk 9]
```diff
@@ -1648,6 +1675,191 @@ impl<T: Config<I>, I: 'static> ReservableCurrency<T::AccountId> for Pallet<T, I>
...
+				value
+			}
+		})
+	}
+
+	/// Slash from reserved balance, returning the negative imbalance created,
+	/// and any amount that was unable to be slashed.
+	///
+	/// Is a no-op if the value to be slashed is zero.
+	fn slash_reserved_named(
```
Comment (gavofyork) [inline frame/balances/src/lib.rs:1757]: Again, a `slash_all_reserved_named` would be good.

File: frame/balances/src/lib.rs [hunk 10]
```diff
@@ -1648,6 +1675,191 @@ impl<T: Config<I>, I: 'static> ReservableCurrency<T::AccountId> for Pallet<T, I>
...
+		})
+	}
+
+	/// Move the reserved balance of one account into the balance of another, according to `status`.
+	/// If `status` is `Reserved`, the balance will be reserved with given `id`.
+	///
+	/// Is a no-op if:
+	/// - the value to be moved is zero; or
+	/// - the `slashed` id equal to `beneficiary` and the `status` is `Reserved`.
+	fn repatriate_reserved_named(
```
Comment (gavofyork) [inline frame/balances/src/lib.rs:1792]: and a `repatriate_all_reserved_named`.

**Review by gavofyork — COMMENTED** [review]
A few small functions would really level this up.

File: frame/balances/src/lib.rs [hunk 11]
```diff
@@ -560,6 +577,17 @@ pub struct BalanceLock<Balance> {
 	pub reasons: Reasons,
 }
 
+pub type ReserveIdentifier = [u8; 8];
```
Comment (xlc) [inline frame/balances/src/lib.rs:580]: Or should I make this an associated type as well and define it in runtime?

Comment (gavofyork) [reply frame/balances/src/lib.rs:580]: can do; will save a little bit of work later.

File: frame/balances/src/lib.rs [hunk 12]
```diff
@@ -1648,6 +1678,193 @@ impl<T: Config<I>, I: 'static> ReservableCurrency<T::AccountId> for Pallet<T, I>
...
+
+	fn reserved_balance_named(id: &Self::ReserveIdentifier, who: &T::AccountId) -> Self::Balance {
+		let reserves = Self::reserves(who);
+		reserves
+			.binary_search_by_key(id, |data| data.id)
+			.map(|index| reserves[index].amount)
+			.unwrap_or_default()
+	}
+
+	/// Move `value` from the free balance from `who` to their reserved balance.
```
Comment (shawntabrizi) [inline frame/balances/src/lib.rs:1694]:
```suggestion
	/// Move `value` from the free balance from `who` to a named reserve balance.
```

File: frame/balances/src/lib.rs [hunk 13]
```diff
@@ -1648,6 +1678,195 @@ impl<T: Config<I>, I: 'static> ReservableCurrency<T::AccountId> for Pallet<T, I>
...
+		})
+	}
+
+	/// Move the reserved balance of one account into the balance of another, according to `status`.
+	/// If `status` is `Reserved`, the balance will be reserved with given `id`.
+	///
+	/// Is a no-op if:
+	/// - the value to be moved is zero; or
+	/// - the `slashed` id equal to `beneficiary` and the `status` is `Reserved`.
+	fn repatriate_reserved_named(
```
Comment (shawntabrizi) [inline frame/balances/src/lib.rs:1799]:
```suggestion
	fn repatriate_named_reserve(
```

probably doesnt matter, but name here is strange

Comment (xlc) [reply frame/balances/src/lib.rs:1799]: I simply add `_named` to all the methods of ReserveCurrency. Not sure if we want consistent naming convention or better method names.

File: frame/balances/src/lib.rs [hunk 14]
```diff
@@ -214,6 +215,12 @@ pub mod pallet {
 		/// The maximum number of locks that should exist on an account.
 		/// Not strictly enforced, but used for weight estimation.
 		type MaxLocks: Get<u32>;
+
+		/// The maximum number of named reserves that can exist on an account.
+		type MaxReserves: Get<u32>;
+
+		/// The id type for named reserves.
+		type ReserveIdentifier: Parameter + Member + MaxEncodedLen + Ord + Copy;
```
Comment (shawntabrizi) [inline frame/balances/src/lib.rs:223]: Is there a reason to make `ReserveIdentifier` configurable?

Sounds like it will be a lot harder to use.

`LockIdentifier` is the same and defined in the primitives.

Comment (xlc) [reply frame/balances/src/lib.rs:223]: Requested by @gavofyork 

https://github.com/paritytech/substrate/pull/7778#discussion_r642944170
https://github.com/paritytech/substrate/pull/7778#discussion_r643042191

I think the goal is make transition to fungible named holds in future easier.

**Review by shawntabrizi — APPROVED** [review]

File: frame/balances/src/lib.rs (hunk 14 above)
Comment (gavofyork) [reply frame/balances/src/lib.rs:223]: The goal is to ensure that the number of values of `ReserveIdentifier` (and thus the number of reserves than can possibly be in place at once) is capped at compile time through Rust's type system.

File: frame/balances/src/lib.rs [hunk 15]
```diff
@@ -560,6 +580,15 @@ pub struct BalanceLock<Balance> {
 	pub reasons: Reasons,
 }
 
+/// Store named reserved balance
```
Comment (gavofyork) [inline frame/balances/src/lib.rs:583]:
```suggestion
/// Store named reserved balance.
```

File: frame/balances/src/lib.rs [hunk 16]
```diff
@@ -560,6 +580,15 @@ pub struct BalanceLock<Balance> {
...
+#[derive(Encode, Decode, Clone, PartialEq, Eq, RuntimeDebug, MaxEncodedLen)]
+pub struct ReserveData<ReserveIdentifier, Balance> {
+	/// The identifier for the named reserve
```
Comment (gavofyork) [inline frame/balances/src/lib.rs:586]:
```suggestion
	/// The identifier for the named reserve.
```

File: frame/balances/src/lib.rs [hunk 17]
```diff
@@ -560,6 +580,15 @@ pub struct BalanceLock<Balance> {
...
+	pub id: ReserveIdentifier,
+	/// The amount of the named reserve
```
Comment (gavofyork) [inline frame/balances/src/lib.rs:588]:
```suggestion
	/// The amount of the named reserve.
```

**Review by gavofyork — APPROVED** [review]

File: frame/balances/src/lib.rs (hunk 14 above)
Comment (wischli) [reply frame/balances/src/lib.rs:223]: > This will obviate the need for `TooManyReserves` error type and `MaxReserves` parameter.

May I ask why the `MaxReserves` parameter was still necessary after all?
