### PR TITLE
Fixes NPoS reward, along with tests, cleanups & docs corrections

### LINKED ISSUE #3575: Exponentially growing validator rewards
I'm having issues with respect to the title. What runtime parameters should be changed to curb this?

Here's a link to the runtime and the chainspec:
- https://github.com/hicommonwealth/edgeware-node/blob/develop/node/runtime/src/lib.rs
- https://github.com/hicommonwealth/edgeware-node/blob/develop/node/service/src/chain_spec.rs

### PR DESCRIPTION
**Pull request by gavofyork**
Subsumes #3590 and the older bits of #3584.
Fixes #3575

Also includes runtime version bump.

### CODE REVIEW

File: srml/staking/src/tests.rs [hunk 1]
```diff
@@ -523,28 +523,34 @@ fn nominating_and_rewards_should_work() {
...
+			// Nominator 4: has [400 / 1800 ~ 2 / 9 from 10] + [600 / 2200 ~ 3 / 11 from 20]'s reward. ==> 2 / 9 + 3 / 11
+			assert_eq!(
+				Balances::total_balance(&4),
+				initial_balance + (2 * payout_for_10 / 9 + 3 * payout_for_20 / 11) - 2
+			);
+
+			// Validator 10: got 800 / 1800 external stake => 8 / 18 =? 4 / 9 => Validator's share = 5 / 9
+			assert_eq!(Balances::total_balance(&10), initial_balance + 5*payout_for_10 / 9 - 1);
+			// Validator 20: got 1200 / 2200 external stake => 12 / 22 =? 6 / 11 => Validator's share = 5 / 11
+			assert_eq!(Balances::total_balance(&20), initial_balance + 5*payout_for_20 / 11);
```
Comment (thiolliere) [inline srml/staking/src/tests.rs]:
```suggestion
			assert_eq!(Balances::total_balance(&20), initial_balance + 5*payout_for_20 / 11 + 1);
```
this is required to make the test `cargo test --release --verbose --no-default-features --features std` works, I don't know why it has changed though
