### PR TITLE
Graceful shutdown for the task manager

### LINKED ISSUE #6642: Service: improve support for other async runtimes
# Use case

Ideally we would like the user to be able use the async runtime they want. This is more or less possible but our current implementation doesn't allow us to use async-std.

# Problem encountered

I tried to use async-std instead of tokio. Even though it works, it produces unexpected behavior as the node's tasks are not gracefully shutdown when the main task completes. Which is a problem because some objects are not dropped before the process exit.

I first thought it was a bug but it is an intentional behavior of async-std to be closer to std::thread. See https://github.com/async-rs/async-std/issues/832 for more details.

# Solutions

## First solution

  One solution would be to support the 2 different patterns:
  - in tokio, the tasks are canceled and awaited when the tokio runtime is dropped, nothing needs to be done manually
  - in async-std, to do a graceful exit, the tasks need to be cancelled and awaited manually

  To do that we need:
  1. a custom JoinHandle trait that would have a `fn cancel()` and `impl Future` (to await the end of the task)
  2. when `fn terminate` is called on the task manager, all the JoinHandle will be called with `fn cancel()`
  3. when using the tokio runtime we would use a dummy JoinHandle that does nothing on cancel
  4. when using async-std runtime we would use a JoinHandle that calls the underlying cancellation method of async-std's JoinHandle

## Alternative solution

Right now the TaskExecutor uses a function to spawn a task that doesn't return anything. Another solution would be for the TaskExecutor to use a function that would return a cancellation function. The TaskManager would need to keep a list of all the cancellation functions gathered during the execution of the node and call them one by one (or in parallel with `join!`) when exiting.

This solution would avoid introducing a new trait.

## Concerns 

I don't know how many background tasks we spawn or even if this number is static. We might just fill up the memory with JoinHandles or cancellation functions...

cc @expenses @gnunicorn @tomaka

### PR DESCRIPTION
**Pull request by cecton**
Fixes #6642 
Related #6651 

In my attempt to create a testing helper I realized that it would be complicated to make sure the background tasks are dropped properly before dropping the async runtime. I thought maybe it would be easier to fix this clean shutdown first. Hopefully I'll be right... writing tests will reveal it.

polkadot companion: https://github.com/paritytech/polkadot/pull/1423

### CODE REVIEW

File: client/service/src/task_manager/mod.rs [hunk 1]
```diff
@@ -223,6 +237,8 @@ pub struct TaskManager {
 	essential_failed_rx: TracingUnboundedReceiver<()>,
 	/// Things to keep alive until the task manager is dropped.
 	keep_alive: Box<dyn std::any::Any + Send + Sync>,
+	task_notifier: TracingUnboundedSender<JoinFuture>,
```
Comment (cecton) [inline client/service/src/task_manager/mod.rs:240]: This can grow in memory

Comment (cecton) [reply client/service/src/task_manager/mod.rs:243]: It's fine now with for_each_concurrent :smiley:

File: client/service/src/task_manager/mod.rs [hunk 2]
```diff
@@ -193,12 +210,12 @@ impl SpawnEssentialTaskHandle {
...
 		task_type: TaskType,
 	) {
-		let mut essential_failed = self.essential_failed_tx.clone();
+		let essential_failed = self.essential_failed_tx.clone();
 		let essential_task = std::panic::AssertUnwindSafe(task)
 			.catch_unwind()
 			.map(move |_| {
 				log::error!("Essential task `{}` failed. Shutting down service.", name);
-				let _ = essential_failed.send(());
+				let _ = essential_failed.close_channel();
```
Comment (cecton) [inline client/service/src/task_manager/mod.rs:218]: Sending didn't work for some reason (it doesn't work in the current version of substrate!). I think it is fine as it as it is an internal detail. I also added a test to make sure that if we ever make this feature more sophisticated it will at least ensure that `fn future()` stops properly.

File: client/service/src/task_manager/mod.rs [hunk 3]
```diff
@@ -233,11 +252,18 @@ impl TaskManager {
...
 		let (signal, on_exit) = exit_future::signal();
+
 		// A side-channel for essential tasks to communicate shutdown.
 		let (essential_failed_tx, essential_failed_rx) = tracing_unbounded("mpsc_essential_tasks");
 
 		let metrics = prometheus_registry.map(Metrics::register).transpose()?;
 
+		let (task_notifier, background_tasks) = tracing_unbounded("mpsc_background_tasks");
+		let completion_future = executor.spawn(
+			Box::pin(background_tasks.for_each_concurrent(None, |x| x)),
```
Comment (cecton) [inline client/service/src/task_manager/mod.rs:263]: `for_each_concurrent` will await on all the JoinHandle future at the same time. It is possible to limit this but I don't think it is necessary. It's actually better for the memory foot print to await them all to not accumulate anything on that stream.

Comment (cecton) [reply client/service/src/task_manager/mod.rs:266]: added note

File: client/cli/src/runner.rs [hunk 4]
```diff
@@ -127,15 +127,13 @@ impl<C: SubstrateCli> Runner<C> {
...
-						tokio::task::spawn_blocking(move || futures::executor::block_on(fut))
-					});
-				}
+			let map_result = |_| ();
+
+			match task_type{
+				TaskType::Async => runtime_handle.spawn(fut).map(map_result),
+				TaskType::Blocking =>
+					runtime_handle.spawn_blocking(move || futures::executor::block_on(fut))
+						.map(map_result),
```
Comment (cecton) [inline client/cli/src/runner.rs:136]: The upgrade to 0.2.21 allows easier writing

File: client/cli/src/runner.rs [hunk 5]
```diff
@@ -127,15 +127,13 @@ impl<C: SubstrateCli> Runner<C> {
...
-				TaskType::Blocking => {
-					runtime_handle.spawn(async move {
-						// `spawn_blocking` is looking for the current runtime, and as such has to
-						// be called from within `spawn`.
-						tokio::task::spawn_blocking(move || futures::executor::block_on(fut))
-					});
-				}
+			let map_result = |_| ();
+
+			match task_type{
```
Comment (gnunicorn) [inline client/cli/src/runner.rs:132]:
```suggestion
			match task_type {
```

**Comment by cecton** [comment]
If we use "bot merge" it will automatically update the polkadot companion and merge both PR properly wthout the need to update sp-io?

**Comment by gavofyork** [comment]
i believe so. but the companion status should be green first.

File: client/cli/src/runner.rs [hunk 6]
```diff
@@ -127,15 +127,13 @@ impl<C: SubstrateCli> Runner<C> {
 		let runtime_handle = tokio_runtime.handle().clone();
 
 		let task_executor = move |fut, task_type| {
+			let map_result = |_| ();
+
```
Comment (bkchr) [inline client/cli/src/runner.rs:131]:
```suggestion
```

File: client/cli/src/runner.rs [hunk 7]
```diff
@@ -127,15 +127,13 @@ impl<C: SubstrateCli> Runner<C> {
...
-					runtime_handle.spawn(async move {
-						// `spawn_blocking` is looking for the current runtime, and as such has to
-						// be called from within `spawn`.
-						tokio::task::spawn_blocking(move || futures::executor::block_on(fut))
-					});
-				}
+				TaskType::Async => runtime_handle.spawn(fut).map(map_result),
+				TaskType::Blocking =>
+					runtime_handle.spawn_blocking(move || futures::executor::block_on(fut))
+						.map(map_result),
```
Comment (bkchr) [inline client/cli/src/runner.rs:136]:
```suggestion
						.map(drop),
```

File: client/cli/src/runner.rs [hunk 8]
```diff
@@ -127,15 +127,13 @@ impl<C: SubstrateCli> Runner<C> {
...
 			match task_type {
-				TaskType::Async => { runtime_handle.spawn(fut); }
-				TaskType::Blocking => {
-					runtime_handle.spawn(async move {
-						// `spawn_blocking` is looking for the current runtime, and as such has to
-						// be called from within `spawn`.
-						tokio::task::spawn_blocking(move || futures::executor::block_on(fut))
-					});
-				}
+				TaskType::Async => runtime_handle.spawn(fut).map(map_result),
```
Comment (bkchr) [inline client/cli/src/runner.rs:133]:
```suggestion
				TaskType::Async => runtime_handle.spawn(fut).map(drop),
```

**Comment by cecton** [comment]
bot merge

**Comment by cecton** [comment]
lol, I was expecting a lot of things but not that in particular :grin:

**Comment by cecton** [comment]
Bot stacktrace for you? cc @sjeohp @gabreal

**Comment by gavofyork** [comment]
bot merge

**Comment by cecton** [comment]
@sjeohp I'm super glad that this bot is in rust :hugs: I think we need more stuff in rust!

Small remark about the stacktrace: I think you [SHOULD](https://tools.ietf.org/html/rfc2119) allow some flexibility in the code and parse any unexpected state as "UnknownState" or something. I know this defies the strongly-typed quality of Rust but CIs and APIs change all the time. GitHub even has undocumented field that are there so... it's best to let the parsing be a bit flexible.

**Comment by cecton** [comment]
bot merge

**Comment by cecton** [comment]
bot merge

**Comment by cecton** [comment]
bot merge
