### PR TITLE
CheckSpecVersion reference fix

### LINKED ISSUE #8000: Outdated reference in Example pallet to Frame System
In pallet example we can find this https://github.com/paritytech/substrate/blob/a2ee0b414f29ce558155dac5cbf78b40723bcc73/frame/example/src/lib.rs#L580 referencing `CheckRuntime` in frame/system. But once in system `CheckRuntime` is not implemented anywhere.

Is documentation in pallet example talking about signed extensions in general or that reference is outdated ?

### PR DESCRIPTION
**Pull request by al3mart**
Minor fix solving and outdated reference to `CheckRuntime` signed extension in pallet example. Updated to `CheckSpecVersion` + link to system documentation.

Closes #8000

### CODE REVIEW

File: frame/example/src/lib.rs [hunk 1]
```diff
@@ -577,7 +577,7 @@ impl<T: Config> Module<T> {
 //
 // Note that a signed extension can also indicate that a particular data must be present in the
 // _signing payload_ of a transaction by providing an implementation for the `additional_signed`
-// method. This example will not cover this type of extension. See `CheckRuntime` in FRAME System
+// method. This example will not cover this type of extension. See `CheckSpecVersion` in [FRAME System](https://github.com/paritytech/substrate/tree/master/frame/system#signed-extensions)
```
Comment (kianenigma) [inline frame/example/src/lib.rs:580]:
```suggestion
// method. This example will not cover this type of extension. See `CheckSpecVersion` in 
// [FRAME System](https://github.com/paritytech/substrate/tree/master/frame/system#signed-extensions)
```

**Review by kianenigma — APPROVED** [review]

File: frame/example/src/lib.rs (hunk 1 above)
Comment (kianenigma) [reply frame/example/src/lib.rs:580]: line width is 100, maximum 120. https://gitlab.parity.io/parity/substrate/-/jobs/804042

**Review by thiolliere — APPROVED** [review]
bot merge

**Comment by thiolliere** [comment]
bot merge
