### PR TITLE
Crypto fixes/improvements

### LINKED ISSUE #2001: subkey yields inconsistent results with hard/soft mixed
`cargo run --release -- --sr25519 inspect "bottom drive obey lake curtain smoke basket hold race lonely fit walk/foo//bar"`

Run 1 -

```
  Public key (hex): 0xaaf0fac3917a39680a9e37ee3a4dd20dd6ee1c621154e0906ed809ec22291578
  Address (SS58): 5FvqanwTCeSj61C11jMt61qYxmNLaJVAyJvCa6TsmSCu9WGc
```

Run 2 -

```
  Public key (hex): 0x961266aa6653385c330c331c04d338d0062c72e4cc66f6dfb2a9fe2e3b4cd60c
  Address (SS58): 5FTUWJpxwVFX5NBdV1e7JqUUufH2i2jDrC3BUnkCJRBSw4TB
```

Further inspection reveals -

- soft/soft (e.g. /foo/bar) and hard/hard (e.g. //foo//bar) yields consistent results
- hard/soft (e.g. //foo/bar) is consistent as well
- soft/hard (e.g. /foo//bar) is inconsistent.

This could be related to the implementation of https://github.com/paritytech/substrate/blob/master/core/primitives/src/sr25519.rs#L368 and the use thereof here https://github.com/paritytech/substrate/blob/master/core/primitives/src/sr25519.rs#L454 where the full secret instead of the seed is passed in.

Basically the secretKey has a secret and nonce part, where the nonce part is non-consistent when derived from seed. (Passing in the seed portion here, when we get a seed back as well, would make it consistent)

### PR DESCRIPTION
**Pull request by gavofyork**
Fixed #2001 

- Use schnorrkel's HDKD derive
- Assume all key URIs beginning with `/` are prefixed with public root phrase.

### CODE REVIEW

File: core/primitives/src/ed25519.rs [hunk 1]
```diff
@@ -523,7 +523,16 @@ impl Pair {
 mod test {
 	use super::*;
 	use hex_literal::{hex, hex_impl};
-	use crate::Pair as _Pair;
+	use crate::{Pair as _Pair, crypto::DEV_PHRASE};
+
+	#[test]
+	fn default_phrase_should_be_used() {
+		assert_eq!(
+
```
Comment (bkchr) [inline core/primitives/src/ed25519.rs]:
```suggestion
```
