### PR TITLE
Fix an extra semi-colon yielding a wrong error

### LINKED ISSUE #6497: Telemetry --name value with a period causes substrate to error with InvalidListenMultiaddress
#### Behavior
If I specify then telemetry `--name` flag with any value including a period, such as `.notadomain`, the value prevents the `substrate` server from starting. Skimming the source didn't indicate to me if this is intentional.

#### Expectation
I could specify any value containing a period, including a domain name, as the `--name` flag.
_or_
I would receive a less ambiguous error indicating that the telemetry name for a node cannot contain a period and any other restrictions.

#### Replication
`substrate` binary
```bash
docker run parity/substrate:latest --name="test.com"
# ....other logs
# Error: InvalidListenMultiaddress
```

Also affects `polkadot`
```bash
docker run parity/polkadot:latest --name="test.com"
# Error: InvalidListenMultiaddress
```

### PR DESCRIPTION
**Pull request by tomaka**
Fix #6497 

Without the `#[from(ignore)]`, the macro generates an `impl From<()> for Error`, which accidentally gets used because of the extra semicolon.

### CODE REVIEW

File: client/cli/src/commands/run_cmd.rs [hunk 1]
```diff
@@ -325,7 +325,7 @@ impl CliConfiguration for RunCmd {
 			Error::Input(format!(
 				"Invalid node name '{}'. Reason: {}. If unsure, use none.",
 				name, msg
-			));
+			))
```
Comment (bkchr) [inline client/cli/src/commands/run_cmd.rs:328]:
```suggestion
		))
```

**Comment by bkchr** [comment]
bot merge

File: client/cli/src/commands/run_cmd.rs [hunk 2]
```diff
@@ -325,7 +325,7 @@ impl CliConfiguration for RunCmd {
 			Error::Input(format!(
 				"Invalid node name '{}'. Reason: {}. If unsure, use none.",
 				name, msg
-			));
+		))
```
Comment (tomaka) [inline client/cli/src/commands/run_cmd.rs:328]:
```suggestion
			))
```

@bkchr What was wrong? It corresponds to `Error::Input(format!(` :astonished:
