### PR TITLE
contracts: Fix possible overflow in storage size calculation

### LINKED ISSUE #2672: Contract storage size panic on u32 overflow
Storage size is u32, and has value of all values size + storage_size_offset. If this exceed u32::max_value() then it currently panics.

Even if chain like Ethereum storage might never reach 4GB it might be the case for some peculiar chain using our framework. Thus I would go to make storage_size being u64.

This would imply some more complex conversion in rent computation but nothing that complicated.

### PR DESCRIPTION
**Pull request by athei**
Fixes #2672

For the reasons explained in the linked issue we replace unchecked and saturating math by checked math. Every contract call that tries to accumulate more storage than can be hold by the `u32` type will be trapped.

It is extremely unlikely that such a large contract will be economically feasible.

### CODE REVIEW

File: frame/contracts/src/storage.rs [hunk 1]
```diff
@@ -75,15 +73,19 @@ where
 	/// `read`, this function also requires the `account` ID.
 	///
 	/// If the contract specified by the id `account` doesn't exist `Err` is returned.`
+	///
+	/// # Panics
+	///
+	/// Panics iff the `account` specified is not alive and in storage.
```
Comment (thiolliere) [inline frame/contracts/src/storage.rs:79]: I kind of prefer having a `Result<DispatchResult, ContractAbsentError>` than a panic, but I guess this is personal.

This makes the proof `.expect("...; qed")` more explicitly required IMO

**Review by thiolliere — APPROVED** [review]
I feel like I would prefer returning result than having a documented panics, but maybe in this context it is fine.

But PR is good to me

File: frame/contracts/src/storage.rs (hunk 1 above)
Comment (athei) [reply frame/contracts/src/storage.rs:79]: Yes me too. However, in this PR I added a non-panicing error (`StorageExhausted`). In order to have the `expect` at the caller side it would need to match over the `DispatchError` somehow to differentiate between the fatal and the non fatal one.

I am planning to remove all those expects soon. The plan is to load the contract info once and pass reference to those functions. Then we can get rid of all those proofs. This will be accomplished by #6439 and #6448.

Comment (thiolliere) [reply frame/contracts/src/storage.rs:79]: I mean you can still have a `Result<DispatchResult, ContractAbsentError>` to differentiate both, it is a bit a ugly, but safer
but I'm ok with current implementation especially if panic will be removed in future

Comment (athei) [reply frame/contracts/src/storage.rs:79]: You are right. I did not think about nesting them.

**Review by NikVolf — APPROVED** [review]

**Comment by athei** [comment]
bot merge
