### PR TITLE
Fix lazy initialisation bug for parametizability

### LINKED ISSUE #2022: InvalidTransaction on latest master (after first tx success, latest master)
After building current substrate master, there seems to be issues with the transaction handling. 

1. Node is started
2. Transfer is created and submitted
3. It succeeds, balances change, nonce increases
4. Another transfer is send (either the same account or a different one)
5. Transfer fails with `1010 InvalidTransaction`

To recover -

6. Stop the node
7. Restart the node
8. Submit hex value (for previous failed tx) exactly as-is again
9. Transaction succeeds, balances change, nonce increases
10. At this point any subsequent transfers gets it to point 5 again, with the same resurrection

### PR DESCRIPTION
**Pull request by thiolliere**
Lazy initialisation doesn't work on wasm for some (unknown yet) reason. This fix it by computing stuff at compile time.

Closes #2022

### CODE REVIEW

File: srml/support/procedural/src/storage/impls.rs [hunk 1]
```diff
@@ -165,8 +165,8 @@ impl<'a, I: Iterator<Item=syn::Meta>> Impls<'a, I> {
 		} = instance_opts;
 
 		let final_prefix = if let Some(instance) = instance {
-			let method_name = syn::Ident::new(&format!("build_prefix_once_for_{}", name.to_string()), proc_macro2::Span::call_site());
-			quote!{ #instance::#method_name(#prefix.as_bytes()) }
+			let const_name = syn::Ident::new(&format!("PREFIX_FOR_{}", name.to_string()), proc_macro2::Span::call_site());
```
Comment (tomusdrw) [inline srml/support/procedural/src/storage/impls.rs]: Might be good to actually move the prefixes to constants, i.e. `format!("{}{}", PREFIX_FOR, name.to_string())` so that it's not repeated in multiple places

Comment (thiolliere) [reply srml/support/procedural/src/storage/impls.rs]: yes but at the same time it would be a compile time error

**Comment by tomusdrw** [comment]
I did some tests and it indeed seems to fix the issue.
