### PR TITLE
fix : remove `_{ }` syntax from benchmark macro

### LINKED ISSUE #5219: Benchmark Improvements: Lingering Variables and `_{ }` syntax
<del>Two small issues I am seeing while writing benchmarks. First is that the very first result from the benchmarks is always an outlier.

Here are some examples:</del>

```
1,46000,30000
1,17000,17000
1,18000,16000
```

```
1,56000,36000
1,17000,17000
1,16000,16000
```

```
1,51000,31000
1,18000,16000
1,17000,17000
```

<del>We need to run our benchmark once but record nothing, and then actually do the benchmarks. We should treat this warm up cycle as **extra** to the number of cycles total we want to run. It would also be good to identify where this initial overhead is coming from.</del>

There is also an issue with the underlying macro which generates the benchmark.

Here is the benchmark code:

```rust
	_ {
		let r in 1 .. MAX_REGISTRARS => add_registrars::<T>(r)?;
		let s in 1 .. T::MaxSubAccounts::get() => {
			// Give them s many sub accounts
			let caller = account::<T>("caller", 0);
			let _ = add_sub_accounts::<T>(caller, s)?;
		};
		let x in 1 .. T::MaxAdditionalFields::get() => {
			// Create their main identity with x additional fields
			let info = create_identity_info::<T>(x);
			let caller = account::<T>("caller", 0);
			let caller_origin = <T as frame_system::Trait>::Origin::from(RawOrigin::Signed(caller));
			Identity::<T>::set_identity(caller_origin, info)?;
		};
	}

	add_registrar {
		let r in ...;
	}: _(RawOrigin::Root, account::<T>("registrar", r + 1))
```

And here is the expanded:

```rust
   #[allow(non_camel_case_types)]
    struct add_registrar;
    #[allow(unused_variables)]
    impl<T: Trait> ::frame_benchmarking::BenchmarkingSetup<T> for add_registrar {
        fn components(&self) -> Vec<(::frame_benchmarking::BenchmarkParameter, u32, u32)> {
            <[_]>::into_vec(box [(
                ::frame_benchmarking::BenchmarkParameter::r,
                {
                    let r = 1;
                    let s = 1;
                    let x = 1;
                    r
                },
                ({
                    let r = MAX_REGISTRARS;
                    let s = T::MaxSubAccounts::get();
                    let x = T::MaxAdditionalFields::get();
                    r
                }),
            )])
        }
        fn instance(
            &self,
            components: &[(::frame_benchmarking::BenchmarkParameter, u32)],
        ) -> Result<Box<dyn FnOnce() -> Result<(), &'static str>>, &'static str> {
            let r = 1;
            let s = 1;
            let x = 1;
            let r = components
                .iter()
                .find(|&c| c.0 == ::frame_benchmarking::BenchmarkParameter::r)
                .unwrap()
                .1;
            ({
                let r = || -> Result<(), &'static str> {
                    add_registrars::<T>(r)?;
                    Ok(())
                };
                let s = || -> Result<(), &'static str> {
                    {
                        let caller = account::<T>("caller", 0);
                        let _ = add_sub_accounts::<T>(caller, s)?;
                    };
                    Ok(())
                };
                let x = || -> Result<(), &'static str> {
                    {
                        let info = create_identity_info::<T>(x);
                        let caller = account::<T>("caller", 0);
                        let caller_origin =
                            <T as frame_system::Trait>::from(RawOrigin::Signed(caller));
                        Identity::<T>::set_identity(caller_origin, info)?;
                    };
                    Ok(())
                };
                r()?
            });
            Ok(Box::new(move || -> Result<(), &'static str> {
                {
                    <Call<T> as ::frame_benchmarking::Dispatchable>::dispatch(
                        Call::<T>::add_registrar(account::<T>("registrar", r + 1)),
                        RawOrigin::Root.into(),
                    )?;
                };
                Ok(())
            }))
        }
    }
```

Note there are some common parameters defined, but only `r` is used in the benchmark. However the expanded code includes all the other variables and even some code blocks which are not used.

One intention could be that we want all of these storage functions to run for every benchmark, whether or not we use them. If that is the case, then the default value should be the `MAX` value.

Otherwise, these unused variables should not appear (this is what I think we should do).

The problem here is that these variables are added completely hidden to the user, and the user may use some variable which is already defined, the Rust would otherwise hide the error.

### PR DESCRIPTION
**Pull request by stanly-johnson**
Remove `_{ }` syntax from bechmark macro and replace use in all files

Resolves #5219 

cc @shawntabrizi 

polkadot companion: https://github.com/paritytech/polkadot/pull/2202

### CODE REVIEW

File: frame/staking/src/benchmarking.rs [hunk 1]
```diff
@@ -113,8 +113,7 @@ pub fn create_validator_with_nominators<T: Config>(
 const USER_SEED: u32 = 999666;
 
 benchmarks! {
-	_{}
-
+	,
```
Comment (bkchr) [inline frame/staking/src/benchmarking.rs:116]: Can this not be removed here and in the other files?

Comment (stanly-johnson) [reply frame/staking/src/benchmarking.rs:116]: Yes that is a very ugly hack to fix `local ambiguity: multiple parsing options: built-in NTs tt ('rest') or 1 other option` error thrown. Need to improve that :)

Comment (shawntabrizi) [reply frame/staking/src/benchmarking.rs:116]: The comma is a hack because he was running into some macro issues. He as asked me to help fix that, but maybe you can look and also make a quick suggestion?

The issue is related to parsing the `where` clause. I am thinking to just make a separate matching arm for this.

Comment (bkchr) [reply frame/staking/src/benchmarking.rs:116]: I'm wondering why it works for the instance macro, but not for the normal one :thinking:

**Comment by shawntabrizi** [comment]
@stanly-johnson fixed the issue related to the hanging comma.

You just need to fix up `example`, `identity`, and `proxy` pallets.

Also delete some of the out of date docs now :)

File: frame/staking/src/benchmarking.rs (hunk 1 above)
Comment (shawntabrizi) [reply frame/staking/src/benchmarking.rs]: it wasnt working :)

File: frame/benchmarking/src/lib.rs [hunk 2]
```diff
@@ -88,12 +88,6 @@ pub use sp_storage::TrackedStorageKey;
 /// benchmarks! {
 ///   where_clause {  where T::A: From<u32> } // Optional line to give additional bound on `T`.
 ///
-///   // common parameter; just one for this example.
-///   // will be `1`, `MAX_LENGTH` or any value inbetween
-///   _ {
-///     let l in 1 .. MAX_LENGTH => initialize_l(l);
-///   }
-///
```
Comment (shawntabrizi) [inline frame/benchmarking/src/lib.rs:96]: More to clean up below. Note the `...` notation used.

**Review by shawntabrizi — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by shawntabrizi** [comment]
bot merge
