### PR TITLE
Fix very wrong staking test

### LINKED ISSUE #5838: Test case not working as expected: `nominators_also_get_slashed`
The intent of https://github.com/paritytech/substrate/blob/268450a946d3d7346ac0052d211009cb82316f1c/frame/staking/src/tests.rs#L536

is to make sure that nominators also get slashed but in the test, `nominator_slash` is equal to 0 and the test is checking that a slash of 0 is applied which is equivalent of no slash at all.

In addition, the `others` vector in the validator's exposure is an empty array which suggests that no nominators are going to be slashed.

I'm not sure if it's just some misconfigured test case or a bug in the code but in any case, I don't think the test case is verifying what it was meant to verify.

### PR DESCRIPTION
**Pull request by kianenigma**
closes #5838

--- 

while doing this, I once more saw how confusing and bad some tests have become. Mostly because some tests are not well isolated, so numerous PRs from numerous people changed one tests case, and this naturally leads to a bad test. For example this one that I fixed here was first written by me and Shawn waaaaay back last year, then there are signs of it being changed with the reward PR and then the slashing PR, all in the same unit test. Some assertions (about rewards for example) made no sense anymore. 

I already have a few issues open about staking tests, but even without that, I will start an endeavour soon to read all of them A to the very damn Z and make sure they make sense.

### CODE REVIEW

File: frame/staking/src/tests.rs [hunk 1]
```diff
@@ -52,6 +50,7 @@ fn force_unstake_works() {
 	});
 }
 
+
```
Comment (kianenigma) [inline frame/staking/src/tests.rs:53]:
```suggestion
```

File: frame/staking/src/tests.rs [hunk 2]
```diff
@@ -533,59 +532,61 @@ fn nominating_and_rewards_should_work() {
...
-		assert_ok!(Staking::nominate(Origin::signed(2), vec![20, 10]));
-
-		let total_payout = current_total_payout_for_duration(3000);
-		assert!(total_payout > 100); // Test is meaningful if reward something
-		<Module<Test>>::reward_by_ids(vec![(11, 1)]);
-
-		// new era, pay rewards,
+fn nominators_also_get_slashed_pro_rata() {
+	ExtBuilder::default().build_and_execute(|| {
 		mock::start_era(1);
```
Comment (kianenigma) [inline frame/staking/src/tests.rs:537]: This is pretty much optional, All conditions apply in Era 0 as well as far as I can tell.

**Comment by shawntabrizi** [comment]
Sorry, can you be a bit more explicit about what in the old test was totally wrong? How was it passing?

**Comment by kianenigma** [comment]
1- as stated in the issue, the slash portion of nominator was zero, so nothing was being really tested.
2- it had a lot of totally unrelated stuff such as rewards or bonding a new nominator. Now it does one thing and it does it clearly: a nominator is slashed pro rata.

**Comment by gnunicorn** [comment]
bot merge
