### PR TITLE
Fixed ancestry search/block queue interaction

### LINKED ISSUE #1311: Unrecoverable verification errors while syncing CC
```
2018-12-21 10:47:47 Syncing  5.2 bps, target=#52650 (7 peers), best: #45629 (0x1e58…967f)
2018-12-21 10:47:52 Syncing  5.2 bps, target=#52651 (7 peers), best: #45655 (0x652a…34d9)
2018-12-21 10:47:57 Syncing  5.2 bps, target=#52652 (7 peers), best: #45681 (0x1f98…201b)
2018-12-21 10:48:02 Syncing  4.8 bps, target=#52653 (7 peers), best: #45705 (0xcbeb…5e51)
2018-12-21 10:48:07 Syncing  5.0 bps, target=#52654 (7 peers), best: #45730 (0x7b48…a02f)
2018-12-21 10:48:12 Syncing  5.2 bps, target=#52654 (7 peers), best: #45756 (0x18f6…76e6)
2018-12-21 10:48:17 Syncing  5.0 bps, target=#52655 (7 peers), best: #45781 (0xc5ae…bea7)
2018-12-21 10:48:22 Syncing  5.0 bps, target=#52656 (7 peers), best: #45806 (0x5f54…8c12)
2018-12-21 10:48:27 Syncing  5.2 bps, target=#52657 (7 peers), best: #45832 (0x21e2…171f)
2018-12-21 10:48:32 Syncing  5.0 bps, target=#52658 (7 peers), best: #45857 (0xed84…5171)
2018-12-21 10:48:37 Syncing  5.2 bps, target=#52659 (7 peers), best: #45883 (0x4137…a7be)
2018-12-21 10:48:42 Syncing  5.0 bps, target=#52660 (7 peers), best: #45908 (0xe550…ff09)
2018-12-21 10:48:47 Syncing  4.8 bps, target=#52660 (7 peers), best: #45932 (0xe6aa…dc4a)
2018-12-21 10:48:50 Purposefully dropping 4 ; reason: Useless("Verification failed: Could not fetch authorities at 0x2b55a5732aa90747b751cf02db759c4e6deb7689b76868e5e00e62127da14ae9: Error(UnknownBlock(\"Hash(0x2b55a5732aa90747b751cf02db759c4e6deb7689b76868e5e00e62127da14ae9)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:\n   0:     0x560fc76ad78c - backtrace::backtrace::trace::h93cca26bba879c3a\n   1:     0x560fc76ac1c2 - backtrace::capture::Backtrace::new_unresolved::hf72abda8acffd24b\n   2:     0x560fc761c777 - error_chain::backtrace::imp::InternalBacktrace::new::h174fd8f03ac1720f\n   3:     0x560fc761cad4 - <error_chain::State as core::default::Default>::default::h0a3fabe83c835c5e\n   4:     0x560fc75852c3 - <substrate_client::error::Error as core::convert::From<substrate_client::error::ErrorKind>>::from::h64fe6f1a235ecdf3\n   5:     0x560fc6bd8292 - <substrate_client_db::Backend<Block> as substrate_client::backend::Backend<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::state_at::h9323664ac81be0c0\n   6:     0x560fc6bcf7fe - <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call::hb5dd5f71a7c4c053\n   7:     0x560fc6c6e8ff - <substrate_client::client::Client<B, E, Block, RA>>::authorities_at::h077be30f4e60dfdb\n   8:     0x560fc6ba4cf7 - <substrate_consensus_aura::AuraVerifier<C, E, MakeInherent> as substrate_network::import_queue::Verifier<B>>::verify::h1fae80eae601d508\n   9:     0x560fc6bc018f - substrate_network::import_queue::import_thread::h23826662968fac89\n  10:     0x560fc6bccd54 - std::panicking::try::do_call::hf1e7876b797fdf16\n  11:     0x560fc77bc519 - __rust_maybe_catch_panic\n                        at libpanic_unwind/lib.rs:103\n  12:     0x560fc6d6b130 - <F as alloc::boxed::FnBox<A>>::call_box::h8b6dacb8971ccb3f\n  13:     0x560fc77ad8da - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + \'a)> as core::ops::function::FnOnce<A>>::call_once::hd022a0500f5eee13\n                        at liballoc/boxed.rs:656\n                         - std::sys_common::thread::start_thread::hb77935aee02382da\n                        at libstd/sys_common/thread.rs:24\n  14:     0x560fc7799b25 - std::sys::unix::thread::Thread::new::thread_start::hd61f7429b3de1d75\n                        at libstd/sys/unix/thread.rs:90\n  15:     0x7fd83d09e6da - start_thread\n  16:     0x7fd83cbaf88e - __clone\n  17:                0x0 - <unknown>) } })")
2018-12-21 10:48:50 Dropped PeerId(QmQT4tqbFaRu1wQ6HbUym3Jy19ugB3RYnUBAM2LVphxygk)
2018-12-21 10:48:50 Purposefully dropping 1 ; reason: Useless("Verification failed: Could not fetch authorities at 0x433dbfe6a884451bef28c3c0aead9dc018b573fce0921b40b2041d53eb4f90bd: Error(UnknownBlock(\"Hash(0x433dbfe6a884451bef28c3c0aead9dc018b573fce0921b40b2041d53eb4f90bd)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:\n   0:     0x560fc76ad78c - backtrace::backtrace::trace::h93cca26bba879c3a\n   1:     0x560fc76ac1c2 - backtrace::capture::Backtrace::new_unresolved::hf72abda8acffd24b\n   2:     0x560fc761c777 - error_chain::backtrace::imp::InternalBacktrace::new::h174fd8f03ac1720f\n   3:     0x560fc761cad4 - <error_chain::State as core::default::Default>::default::h0a3fabe83c835c5e\n   4:     0x560fc75852c3 - <substrate_client::error::Error as core::convert::From<substrate_client::error::ErrorKind>>::from::h64fe6f1a235ecdf3\n   5:     0x560fc6bd8292 - <substrate_client_db::Backend<Block> as substrate_client::backend::Backend<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::state_at::h9323664ac81be0c0\n   6:     0x560fc6bcf7fe - <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call::hb5dd5f71a7c4c053\n   7:     0x560fc6c6e8ff - <substrate_client::client::Client<B, E, Block, RA>>::authorities_at::h077be30f4e60dfdb\n   8:     0x560fc6ba4cf7 - <substrate_consensus_aura::AuraVerifier<C, E, MakeInherent> as substrate_network::import_queue::Verifier<B>>::verify::h1fae80eae601d508\n   9:     0x560fc6bc018f - substrate_network::import_queue::import_thread::h23826662968fac89\n  10:     0x560fc6bccd54 - std::panicking::try::do_call::hf1e7876b797fdf16\n  11:     0x560fc77bc519 - __rust_maybe_catch_panic\n                        at libpanic_unwind/lib.rs:103\n  12:     0x560fc6d6b130 - <F as alloc::boxed::FnBox<A>>::call_box::h8b6dacb8971ccb3f\n  13:     0x560fc77ad8da - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + \'a)> as core::ops::function::FnOnce<A>>::call_once::hd022a0500f5eee13\n                        at liballoc/boxed.rs:656\n                         - std::sys_common::thread::start_thread::hb77935aee02382da\n                        at libstd/sys_common/thread.rs:24\n  14:     0x560fc7799b25 - std::sys::unix::thread::Thread::new::thread_start::hd61f7429b3de1d75\n                        at libstd/sys/unix/thread.rs:90\n  15:     0x7fd83d09e6da - start_thread\n  16:     0x7fd83cbaf88e - __clone\n  17:                0x0 - <unknown>) } })")
2018-12-21 10:48:50 Dropped PeerId(QmWxNqJeKEBWjJXeX8s882ZdphuVPgUV43THfGAJn7UBWB)
2018-12-21 10:48:50 Purposefully dropping 0 ; reason: Useless("Verification failed: Could not fetch authorities at 0x2203268cee030753b831cfbba682960bc9f11ed6c8306f11ed5c263b1973de94: Error(UnknownBlock(\"Hash(0x2203268cee030753b831cfbba682960bc9f11ed6c8306f11ed5c263b1973de94)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:\n   0:     0x560fc76ad78c - backtrace::backtrace::trace::h93cca26bba879c3a\n   1:     0x560fc76ac1c2 - backtrace::capture::Backtrace::new_unresolved::hf72abda8acffd24b\n   2:     0x560fc761c777 - error_chain::backtrace::imp::InternalBacktrace::new::h174fd8f03ac1720f\n   3:     0x560fc761cad4 - <error_chain::State as core::default::Default>::default::h0a3fabe83c835c5e\n   4:     0x560fc75852c3 - <substrate_client::error::Error as core::convert::From<substrate_client::error::ErrorKind>>::from::h64fe6f1a235ecdf3\n   5:     0x560fc6bd8292 - <substrate_client_db::Backend<Block> as substrate_client::backend::Backend<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::state_at::h9323664ac81be0c0\n   6:     0x560fc6bcf7fe - <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call::hb5dd5f71a7c4c053\n   7:     0x560fc6c6e8ff - <substrate_client::client::Client<B, E, Block, RA>>::authorities_at::h077be30f4e60dfdb\n   8:     0x560fc6ba4cf7 - <substrate_consensus_aura::AuraVerifier<C, E, MakeInherent> as substrate_network::import_queue::Verifier<B>>::verify::h1fae80eae601d508\n   9:     0x560fc6bc018f - substrate_network::import_queue::import_thread::h23826662968fac89\n  10:     0x560fc6bccd54 - std::panicking::try::do_call::hf1e7876b797fdf16\n  11:     0x560fc77bc519 - __rust_maybe_catch_panic\n                        at libpanic_unwind/lib.rs:103\n  12:     0x560fc6d6b130 - <F as alloc::boxed::FnBox<A>>::call_box::h8b6dacb8971ccb3f\n  13:     0x560fc77ad8da - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + \'a)> as core::ops::function::FnOnce<A>>::call_once::hd022a0500f5eee13\n                        at liballoc/boxed.rs:656\n                         - std::sys_common::thread::start_thread::hb77935aee02382da\n                        at libstd/sys_common/thread.rs:24\n  14:     0x560fc7799b25 - std::sys::unix::thread::Thread::new::thread_start::hd61f7429b3de1d75\n                        at libstd/sys/unix/thread.rs:90\n  15:     0x7fd83d09e6da - start_thread\n  16:     0x7fd83cbaf88e - __clone\n  17:                0x0 - <unknown>) } })")
2018-12-21 10:48:50 Dropped PeerId(QmV2zjgFRfxbgYZQC9qFr4aHsQt7tDBJRAdgqqxqTq1Kta)
2018-12-21 10:48:50 Purposefully dropping 2 ; reason: Useless("Verification failed: Could not fetch authorities at 0x74503c40c136a1b7ff989ce7dcd88238fb6e63ad4edb6e17d335225f33978113: Error(UnknownBlock(\"Hash(0x74503c40c136a1b7ff989ce7dcd88238fb6e63ad4edb6e17d335225f33978113)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:\n   0:     0x560fc76ad78c - backtrace::backtrace::trace::h93cca26bba879c3a\n   1:     0x560fc76ac1c2 - backtrace::capture::Backtrace::new_unresolved::hf72abda8acffd24b\n   2:     0x560fc761c777 - error_chain::backtrace::imp::InternalBacktrace::new::h174fd8f03ac1720f\n   3:     0x560fc761cad4 - <error_chain::State as core::default::Default>::default::h0a3fabe83c835c5e\n   4:     0x560fc75852c3 - <substrate_client::error::Error as core::convert::From<substrate_client::error::ErrorKind>>::from::h64fe6f1a235ecdf3\n   5:     0x560fc6bd8292 - <substrate_client_db::Backend<Block> as substrate_client::backend::Backend<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::state_at::h9323664ac81be0c0\n   6:     0x560fc6bcf7fe - <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call::hb5dd5f71a7c4c053\n   7:     0x560fc6c6e8ff - <substrate_client::client::Client<B, E, Block, RA>>::authorities_at::h077be30f4e60dfdb\n   8:     0x560fc6ba4cf7 - <substrate_consensus_aura::AuraVerifier<C, E, MakeInherent> as substrate_network::import_queue::Verifier<B>>::verify::h1fae80eae601d508\n   9:     0x560fc6bc018f - substrate_network::import_queue::import_thread::h23826662968fac89\n  10:     0x560fc6bccd54 - std::panicking::try::do_call::hf1e7876b797fdf16\n  11:     0x560fc77bc519 - __rust_maybe_catch_panic\n                        at libpanic_unwind/lib.rs:103\n  12:     0x560fc6d6b130 - <F as alloc::boxed::FnBox<A>>::call_box::h8b6dacb8971ccb3f\n  13:     0x560fc77ad8da - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + \'a)> as core::ops::function::FnOnce<A>>::call_once::hd022a0500f5eee13\n                        at liballoc/boxed.rs:656\n                         - std::sys_common::thread::start_thread::hb77935aee02382da\n                        at libstd/sys_common/thread.rs:24\n  14:     0x560fc7799b25 - std::sys::unix::thread::Thread::new::thread_start::hd61f7429b3de1d75\n                        at libstd/sys/unix/thread.rs:90\n  15:     0x7fd83d09e6da - start_thread\n  16:     0x7fd83cbaf88e - __clone\n  17:                0x0 - <unknown>) } })")
2018-12-21 10:48:50 Dropped PeerId(QmQbPCeurXuKhzCw6Ar6ovizNKATMTnkkqFJKgZzbF2MJs)
2018-12-21 10:48:50 Purposefully dropping 6 ; reason: Useless("Verification failed: Could not fetch authorities at 0x5085a1c049a7c8c954446767bd51259f6dbb3ea8fdda526bd79a121d753b1da4: Error(UnknownBlock(\"Hash(0x5085a1c049a7c8c954446767bd51259f6dbb3ea8fdda526bd79a121d753b1da4)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:\n   0:     0x560fc76ad78c - backtrace::backtrace::trace::h93cca26bba879c3a\n   1:     0x560fc76ac1c2 - backtrace::capture::Backtrace::new_unresolved::hf72abda8acffd24b\n   2:     0x560fc761c777 - error_chain::backtrace::imp::InternalBacktrace::new::h174fd8f03ac1720f\n   3:     0x560fc761cad4 - <error_chain::State as core::default::Default>::default::h0a3fabe83c835c5e\n   4:     0x560fc75852c3 - <substrate_client::error::Error as core::convert::From<substrate_client::error::ErrorKind>>::from::h64fe6f1a235ecdf3\n   5:     0x560fc6bd8292 - <substrate_client_db::Backend<Block> as substrate_client::backend::Backend<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::state_at::h9323664ac81be0c0\n   6:     0x560fc6bcf7fe - <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call::hb5dd5f71a7c4c053\n   7:     0x560fc6c6e8ff - <substrate_client::client::Client<B, E, Block, RA>>::authorities_at::h077be30f4e60dfdb\n   8:     0x560fc6ba4cf7 - <substrate_consensus_aura::AuraVerifier<C, E, MakeInherent> as substrate_network::import_queue::Verifier<B>>::verify::h1fae80eae601d508\n   9:     0x560fc6bc018f - substrate_network::import_queue::import_thread::h23826662968fac89\n  10:     0x560fc6bccd54 - std::panicking::try::do_call::hf1e7876b797fdf16\n  11:     0x560fc77bc519 - __rust_maybe_catch_panic\n                        at libpanic_unwind/lib.rs:103\n  12:     0x560fc6d6b130 - <F as alloc::boxed::FnBox<A>>::call_box::h8b6dacb8971ccb3f\n  13:     0x560fc77ad8da - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + \'a)> as core::ops::function::FnOnce<A>>::call_once::hd022a0500f5eee13\n                        at liballoc/boxed.rs:656\n                         - std::sys_common::thread::start_thread::hb77935aee02382da\n                        at libstd/sys_common/thread.rs:24\n  14:     0x560fc7799b25 - std::sys::unix::thread::Thread::new::thread_start::hd61f7429b3de1d75\n                        at libstd/sys/unix/thread.rs:90\n  15:     0x7fd83d09e6da - start_thread\n  16:     0x7fd83cbaf88e - __clone\n  17:                0x0 - <unknown>) } })")
2018-12-21 10:48:50 Dropped PeerId(QmUpsU1H5jA16zheRHtXaw7xDais6nxcSzsQE24ToNzoWW)
2018-12-21 10:48:50 Purposefully dropping 2 ; reason: Useless("Verification failed: Could not fetch authorities at 0x1bd3ff04cedc3807c4170b27e2b69e72c44a6602c75349d21b3e2e4ee9e4c22a: Error(UnknownBlock(\"Hash(0x1bd3ff04cedc3807c4170b27e2b69e72c44a6602c75349d21b3e2e4ee9e4c22a)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:\n   0:     0x560fc76ad78c - backtrace::backtrace::trace::h93cca26bba879c3a\n   1:     0x560fc76ac1c2 - backtrace::capture::Backtrace::new_unresolved::hf72abda8acffd24b\n   2:     0x560fc761c777 - error_chain::backtrace::imp::InternalBacktrace::new::h174fd8f03ac1720f\n   3:     0x560fc761cad4 - <error_chain::State as core::default::Default>::default::h0a3fabe83c835c5e\n   4:     0x560fc75852c3 - <substrate_client::error::Error as core::convert::From<substrate_client::error::ErrorKind>>::from::h64fe6f1a235ecdf3\n   5:     0x560fc6bd8292 - <substrate_client_db::Backend<Block> as substrate_client::backend::Backend<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::state_at::h9323664ac81be0c0\n   6:     0x560fc6bcf7fe - <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call::hb5dd5f71a7c4c053\n   7:     0x560fc6c6e8ff - <substrate_client::client::Client<B, E, Block, RA>>::authorities_at::h077be30f4e60dfdb\n   8:     0x560fc6ba4cf7 - <substrate_consensus_aura::AuraVerifier<C, E, MakeInherent> as substrate_network::import_queue::Verifier<B>>::verify::h1fae80eae601d508\n   9:     0x560fc6bc018f - substrate_network::import_queue::import_thread::h23826662968fac89\n  10:     0x560fc6bccd54 - std::panicking::try::do_call::hf1e7876b797fdf16\n  11:     0x560fc77bc519 - __rust_maybe_catch_panic\n                        at libpanic_unwind/lib.rs:103\n  12:     0x560fc6d6b130 - <F as alloc::boxed::FnBox<A>>::call_box::h8b6dacb8971ccb3f\n  13:     0x560fc77ad8da - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + \'a)> as core::ops::function::FnOnce<A>>::call_once::hd022a0500f5eee13\n                        at liballoc/boxed.rs:656\n                         - std::sys_common::thread::start_thread::hb77935aee02382da\n                        at libstd/sys_common/thread.rs:24\n  14:     0x560fc7799b25 - std::sys::unix::thread::Thread::new::thread_start::hd61f7429b3de1d75\n                        at libstd/sys/unix/thread.rs:90\n  15:     0x7fd83d09e6da - start_thread\n  16:     0x7fd83cbaf88e - __clone\n  17:                0x0 - <unknown>) } })")
2018-12-21 10:48:51 Purposefully dropping 5 ; reason: Useless("Verification failed: Could not fetch authorities at 0x9e1b7f329a133a8972662fb1e791adf2569edc29631d3571aa19a98d7cce87ff: Error(UnknownBlock(\"Hash(0x9e1b7f329a133a8972662fb1e791adf2569edc29631d3571aa19a98d7cce87ff)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:\n   0:     0x560fc76ad78c - backtrace::backtrace::trace::h93cca26bba879c3a\n   1:     0x560fc76ac1c2 - backtrace::capture::Backtrace::new_unresolved::hf72abda8acffd24b\n   2:     0x560fc761c777 - error_chain::backtrace::imp::InternalBacktrace::new::h174fd8f03ac1720f\n   3:     0x560fc761cad4 - <error_chain::State as core::default::Default>::default::h0a3fabe83c835c5e\n   4:     0x560fc75852c3 - <substrate_client::error::Error as core::convert::From<substrate_client::error::ErrorKind>>::from::h64fe6f1a235ecdf3\n   5:     0x560fc6bd8292 - <substrate_client_db::Backend<Block> as substrate_client::backend::Backend<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::state_at::h9323664ac81be0c0\n   6:     0x560fc6bcf7fe - <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call::hb5dd5f71a7c4c053\n   7:     0x560fc6c6e8ff - <substrate_client::client::Client<B, E, Block, RA>>::authorities_at::h077be30f4e60dfdb\n   8:     0x560fc6ba4cf7 - <substrate_consensus_aura::AuraVerifier<C, E, MakeInherent> as substrate_network::import_queue::Verifier<B>>::verify::h1fae80eae601d508\n   9:     0x560fc6bc018f - substrate_network::import_queue::import_thread::h23826662968fac89\n  10:     0x560fc6bccd54 - std::panicking::try::do_call::hf1e7876b797fdf16\n  11:     0x560fc77bc519 - __rust_maybe_catch_panic\n                        at libpanic_unwind/lib.rs:103\n  12:     0x560fc6d6b130 - <F as alloc::boxed::FnBox<A>>::call_box::h8b6dacb8971ccb3f\n  13:     0x560fc77ad8da - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + \'a)> as core::ops::function::FnOnce<A>>::call_once::hd022a0500f5eee13\n                        at liballoc/boxed.rs:656\n                         - std::sys_common::thread::start_thread::hb77935aee02382da\n                        at libstd/sys_common/thread.rs:24\n  14:     0x560fc7799b25 - std::sys::unix::thread::Thread::new::thread_start::hd61f7429b3de1d75\n                        at libstd/sys/unix/thread.rs:90\n  15:     0x7fd83d09e6da - start_thread\n  16:     0x7fd83cbaf88e - __clone\n  17:                0x0 - <unknown>) } })")
2018-12-21 10:48:51 Dropped PeerId(QmfXk5T66mqPP7SUJwt7iwKyTxigT5Bz35WrnZySRdWkFz)
2018-12-21 10:48:51 Purposefully dropping 3 ; reason: Useless("Verification failed: Could not fetch authorities at 0x84d85817b67056988e309be07ea50f78188b1b0fca51245ca7f50d91a118b302: Error(UnknownBlock(\"Hash(0x84d85817b67056988e309be07ea50f78188b1b0fca51245ca7f50d91a118b302)\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:\n   0:     0x560fc76ad78c - backtrace::backtrace::trace::h93cca26bba879c3a\n   1:     0x560fc76ac1c2 - backtrace::capture::Backtrace::new_unresolved::hf72abda8acffd24b\n   2:     0x560fc761c777 - error_chain::backtrace::imp::InternalBacktrace::new::h174fd8f03ac1720f\n   3:     0x560fc761cad4 - <error_chain::State as core::default::Default>::default::h0a3fabe83c835c5e\n   4:     0x560fc75852c3 - <substrate_client::error::Error as core::convert::From<substrate_client::error::ErrorKind>>::from::h64fe6f1a235ecdf3\n   5:     0x560fc6bd8292 - <substrate_client_db::Backend<Block> as substrate_client::backend::Backend<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::state_at::h9323664ac81be0c0\n   6:     0x560fc6bcf7fe - <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::hasher::blake2::Blake2Hasher>>::call::hb5dd5f71a7c4c053\n   7:     0x560fc6c6e8ff - <substrate_client::client::Client<B, E, Block, RA>>::authorities_at::h077be30f4e60dfdb\n   8:     0x560fc6ba4cf7 - <substrate_consensus_aura::AuraVerifier<C, E, MakeInherent> as substrate_network::import_queue::Verifier<B>>::verify::h1fae80eae601d508\n   9:     0x560fc6bc018f - substrate_network::import_queue::import_thread::h23826662968fac89\n  10:     0x560fc6bccd54 - std::panicking::try::do_call::hf1e7876b797fdf16\n  11:     0x560fc77bc519 - __rust_maybe_catch_panic\n                        at libpanic_unwind/lib.rs:103\n  12:     0x560fc6d6b130 - <F as alloc::boxed::FnBox<A>>::call_box::h8b6dacb8971ccb3f\n  13:     0x560fc77ad8da - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + \'a)> as core::ops::function::FnOnce<A>>::call_once::hd022a0500f5eee13\n                        at liballoc/boxed.rs:656\n                         - std::sys_common::thread::start_thread::hb77935aee02382da\n                        at libstd/sys_common/thread.rs:24\n  14:     0x560fc7799b25 - std::sys::unix::thread::Thread::new::thread_start::hd61f7429b3de1d75\n                        at libstd/sys/unix/thread.rs:90\n  15:     0x7fd83d09e6da - start_thread\n  16:     0x7fd83cbaf88e - __clone\n  17:                0x0 - <unknown>) } })")
2018-12-21 10:48:51 Dropped PeerId(QmXd7MQAuXkQK1r3ejSbaXKgjXmT2FvbJ3yNfLZpsQ2t8S)
2018-12-21 10:48:52 Idle (0 peers), best: #45946 (0x9028…65d0)
2018-12-21 10:48:57 Syncing, target=#52662 (7 peers), best: #45946 (0x9028…65d0)
```

After all the peers where dropped, it reconnected but never started syncing again. Restart fixed this.

### PR DESCRIPTION
**Pull request by arkpar**
FIxes #1311

### CODE REVIEW

File: core/network/src/sync.rs [hunk 1]
```diff
@@ -144,13 +143,22 @@ impl<B: BlockT> ChainSync<B> {
 				(Ok(BlockStatus::Unknown), b) if b == As::sa(0) => {
 					protocol.report_peer(who, Severity::Bad(&format!("New peer with unknown genesis hash {} ({}).", info.best_hash, info.best_number)));
 				},
+				(Ok(BlockStatus::Unknown), _) if self.import_queue.status().importing_count > 5 => {
```
Comment (gavofyork) [inline core/network/src/sync.rs]: bare literal in logic - best to use a const, no?

File: core/network/src/sync.rs [hunk 2]
```diff
@@ -144,13 +143,22 @@ impl<B: BlockT> ChainSync<B> {
 				(Ok(BlockStatus::Unknown), b) if b == As::sa(0) => {
```
Comment (gavofyork) [inline core/network/src/sync.rs]: `b.is_zero()` is preferable (though you'll need to `use primitives::traits::Zero;`
