### PR TITLE
Fix #2403

### LINKED ISSUE #2403: Rare state inconsistency between PSM and network: "Already connected to this peer"
Example logs:

```
14:21:01.058 libp2p-1 DEBUG sub-libp2p  PSM => Connect(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW")): Enabling previously-idle connection through Listener { listen_addr: "/ip4/0.0.0.0/tcp/30333", send_back_addr: "/ip4/138.197.130.240/tcp/41692" }
14:21:01.058 libp2p-1 DEBUG sub-libp2p  Handler(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW")) <= Enable
14:21:01.322 libp2p-0 DEBUG sub-libp2p  Handler(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW")) => Severe protocol error: Upgrade(Select(NoProtocolFound))
14:21:01.322 libp2p-0 DEBUG sub-libp2p  PSM <= Dropped(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW"))
14:21:01.322 libp2p-0 DEBUG sub-libp2p  Handler(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW")) <= Disable
14:21:28.045 libp2p-0 DEBUG sub-libp2p  PSM => Connect(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW")): Enabling previously-idle connection through Listener { listen_addr: "/ip4/0.0.0.0/tcp/30333", send_back_addr: "/ip4/138.197.130.240/tcp/41692" }
14:21:28.045 libp2p-0 DEBUG sub-libp2p  Handler(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW")) <= Enable
14:21:28.314 libp2p-2 DEBUG sub-libp2p  Handler(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW")) => Severe protocol error: Upgrade(Select(NoProtocolFound))
14:21:28.314 libp2p-2 DEBUG sub-libp2p  PSM <= Dropped(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW"))
14:21:28.314 libp2p-2 DEBUG sub-libp2p  Handler(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW")) <= Disable
14:21:40.897 libp2p-1 DEBUG sub-libp2p  Libp2p => Disconnected(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW")): Was disabled (through Listener { listen_addr: "/ip4/0.0.0.0/tcp/30333", send_back_addr: "/ip4/138.197.130.240/tcp/41692" })
14:21:41.729 libp2p-0 DEBUG sub-libp2p  Libp2p => Connected(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW")): Connection requested by PSM (through Listener { listen_addr: "/ip4/0.0.0.0/tcp/30333", send_back_addr: "/ip4/138.197.130.240/tcp/43896" })
14:21:41.729 libp2p-0 DEBUG sub-libp2p  Handler(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW")) <= Enable
14:21:42.075 libp2p-2 DEBUG sub-libp2p  PSM <= Discovered(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW"))
14:21:47.841 libp2p-3 WARN sub-libp2p  PSM => Connect(PeerId("Qmeh8SsfCqxTJCCHkeG7kVwdAf4QoZq3PrbYv7S2ALBorW")): Already connected to this peer 
```

### PR DESCRIPTION
**Pull request by tomaka**
Fix issue #2403 
When connected to a `Banned` node, treat it the same way as "vacant entry".

### CODE REVIEW

File: core/network-libp2p/src/custom_proto/behaviour.rs [hunk 1]
```diff
@@ -612,31 +612,24 @@ where
...
-							already-connected node; state is {:?}", st);
-						*entry.into_mut() = st;
-						return
-					}
-				}
+		match (self.peers.entry(peer_id.clone()).or_insert(PeerState::Poisoned), connected_point) {
+			(st @ &mut PeerState::Requested, connected_point) |
+			(st @ &mut PeerState::PendingRequest { .. }, connected_point) => {
+				debug!(target: "sub-libp2p", "Libp2p => Connected({:?}): Connection \
+					requested by PSM (through {:?})", peer_id, connected_point);
```
Comment (bkchr) [inline core/network-libp2p/src/custom_proto/behaviour.rs]:
```suggestion
					requested by PSM (through {:?})", peer_id, connected_point
				);
```

File: core/network-libp2p/src/custom_proto/behaviour.rs [hunk 2]
```diff
@@ -646,27 +639,39 @@ where
...
 					event: CustomProtoHandlerIn::Disable,
 				});
-				entry.insert(PeerState::Disabled { open: false, connected_point, banned_until: None });
+				*st = PeerState::Disabled { open: false, connected_point, banned_until };
+			}
+
+			st => {
+				// This is a serious bug either in this state machine or in libp2p.
+				error!(target: "sub-libp2p", "Received inject_connected for \
+					already-connected node; state is {:?}", st);
```
Comment (bkchr) [inline core/network-libp2p/src/custom_proto/behaviour.rs]:
```suggestion
					already-connected node; state is {:?}", st
				);
```

**Comment by tomaka** [comment]
> A more general note to the PeerId, it seems that it is copied always every time. Why not implement Copy for the type. I know that it internally stores a Vec<u8>, but as it it cloned anyway most of the times I don't see any big difference. We could switch to use Bytes internally, to make Clone/Copy just an Arc Clone.

Well, normally the solution would be to not clone the id.
Very often, the obstacle to not cloning is that `HashMap::entry` requires passing by ownership, but this is getting fixed with the a `HashMap` API.
