### PR TITLE
Fix error during build: failed to run custom build command for sc-net…

### LINKED ISSUE #12493: Error during build: failed to run custom build command for sc-network-bitswap
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Compiling sc-network-bitswap v0.10.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.30#a3ed0119)
error: failed to run custom build command for `sc-network-bitswap v0.10.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.30#a3ed0119)`
Caused by:
  process didn't exit successfully: `/home/ezio/Desktop/RustProjects/substrate-node-template/target/release/build/sc-network-bitswap-b1a8656c9520e03c/build-script-build` (exit status: 101)
  --- stdout
  Running: "/usr/bin/protoc" "--include_imports" "--include_source_info" "-o" "/tmp/prost-buildBdb2Wu/prost-descriptor-set" "-I" "src/schema" "bitswap.v1.2.0.proto"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: bitswap.v1.2.0.proto: No such file or directory\n" }', /home/ezio/.cargo/git/checkouts/substrate-7e08433d4c370a21/a3ed011/client/network/bitswap/build.rs:4:58
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
     2: core::result::unwrap_failed
               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
     3: core::result::Result<T,E>::unwrap
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

### Steps to reproduce

```
git clone https://github.com/substrate-developer-hub/substrate-node-template
cargo build --release
```

### PR DESCRIPTION
**Pull request by anonymousGiga**
Resolves #12493

### CODE REVIEW

File: client/network/bitswap/build.rs [hunk 1]
```diff
@@ -1,4 +1,4 @@
-const PROTOS: &[&str] = &["bitswap.v1.2.0.proto"];
+const PROTOS: &[&str] = &["src/schema/bitswap.v1.2.0.proto"];
```
Comment (altonen) [inline client/network/bitswap/build.rs:1]: I'm fine with this change because it seems to work either way and for some reason the [example code](https://docs.rs/prost-build/latest/prost_build/index.html) `prost-build` also adds the include path to the source files. But it would be interesting to know why the code as it was before is not working for you.

Comment (bkchr) [reply client/network/bitswap/build.rs:1]: If we look some lines below, we give the path `src/schema` as includes. Looking at the docs, the files given in `PROTOS` should be found in the given includes. So, it should work. 

So, I also want to know why it doesn't work for you and then we need to report this to upstream.

Comment (bkchr) [reply client/network/bitswap/build.rs:1]: https://docs.rs/prost-build/latest/prost_build/fn.compile_protos.html 

If you read the docs there, we do it exactly as explained in the docs. Others have reported that maybe deleting the `target` dir fixed it for them. There is clearly some bug, but I don't think in our code. None of our devs also reported this issue.

Comment (anonymousGiga) [reply client/network/bitswap/build.rs:1]: Yes, I read this document. I will ask the developer of prost-build for the usage of this parameter.

Comment (anonymousGiga) [reply client/network/bitswap/build.rs:1]: I asked PROST about the issue, and maybe they can answer the questions.    https://github.com/tokio-rs/prost/issues/734

Comment (bkchr) [reply client/network/bitswap/build.rs:1]: Ty @anonymousGiga :heart:

Comment (anonymousGiga) [reply client/network/bitswap/build.rs:1]: I got a response from this issue（https://github.com/tokio-rs/prost/issues/734） ,  may be we should use "```src/schema/bitswap.v1.2.0.proto```" instead of "```bitswap.v1.2.0.proto```".   @bkchr

Comment (bkchr) [reply client/network/bitswap/build.rs:1]: @anonymousGiga could you then please update all usages of `compile_protos`?

Comment (anonymousGiga) [reply client/network/bitswap/build.rs:1]: I checked that all the other places where  ```compile_protos```  is used are correct, and they all use in the way "prefix the protos with the path".     In addition, I also updated to the latest master branch.    @bkchr

**Review by bkchr — APPROVED** [review]

**Review by altonen — APPROVED** [review]

**Comment by altonen** [comment]
bot merge
