### PR TITLE
pallet-contracts: State rent fixes

### LINKED ISSUE #5107: State rent and empty values
At the moment of writing the storage rent computes the effective rent based on the byte size of each storage entry the contract occupies.

However, https://github.com/paritytech/substrate/pull/5103 raised a question: how are zero sized storage values interact with storage rent? For now, they won't affect the final cost. That doesn't seem right because in reality even an empty mapping occupies some DB space.

@Robbepop proposed to just ban this sort of interactions for now and allow them when we deem they are actually useful. While this sounds tempting, I am not sure if we should go this way - this seems to be a bit more limiting, especially considering there is already one use-case discovered: sets that leverage KV storage.

<details>
Imagine a contract that has to maintain a set of, say, u32 values. The set of values is potentially unbounded. If we were to save such a set in a single storage entry, as a serialized vector without repeated values, then such a vector will have to be serialized, deserialized, and filled at least once per contract run. 

A solution would be to leverage the key to encode the value and then just check if the value under that key exist. If all values of the set are kept under prefix `0xFFFFFFFFFFFFFFFFFF` then a value `0x12345678` would have key `0xFFFFFFFFFFFFFFFFFF12345678`. If such a key exists then the value in the set. If empty values were banned we would have to have a one byte dummy value in each entry, which seems to be awkward.
</details>

### PR DESCRIPTION
**Pull request by pepyakin**
This PR basically fixes two things:

This a long standing annoyance that `T::StorageOffsetSize` was assigned at a contract creation time. If we were to change this parameter it would have been a nightmare since we would have to alter each storage item. With this PR, the `storage_size` reflects the actual sum of all KV pairs and `T::StorageOffsetSize` is only accounted for during computing the fees for state rent.

Apart from that

Fixes #5107

### CODE REVIEW

File: frame/contracts/src/lib.rs [hunk 1]
```diff
@@ -338,8 +345,10 @@ pub trait Trait: frame_system::Trait + pallet_transaction_payment::Trait {
 	/// The minimum amount required to generate a tombstone.
 	type TombstoneDeposit: Get<BalanceOf<Self>>;
 
-	/// Size of a contract at the time of instantiation. This is a simple way to ensure
-	/// that empty contracts eventually gets deleted.
+	/// A size offset for an contract. A just created account with untouched storage will have that
+	/// much of storage from the perspective of the state rent.
+	///
+	/// This is a simple way to ensure that empty contracts eventually gets deleted.
```
Comment (athei) [inline frame/contracts/src/lib.rs:351]:
```suggestion
	/// This is a simple way to ensure that contracts with empty storage eventually get deleted by making them pay rent. This creates an incentive to remove them early in order to save rent.
```

File: frame/contracts/src/lib.rs [hunk 2]
```diff
@@ -420,8 +429,10 @@ decl_module! {
 		/// The minimum amount required to generate a tombstone.
 		const TombstoneDeposit: BalanceOf<T> = T::TombstoneDeposit::get();
 
-		/// Size of a contract at the time of instantiation. This is a simple way to ensure that
-		/// empty contracts eventually gets deleted.
+		/// A size offset for an contract. A just created account with untouched storage will have that
+		/// much of storage from the perspective of the state rent.
+		///
+		/// This is a simple way to ensure that empty contracts eventually gets deleted.
```
Comment (athei) [inline frame/contracts/src/lib.rs:435]: See above.

File: frame/contracts/src/account_db.rs [hunk 3]
```diff
@@ -210,18 +218,70 @@ impl<T: Trait> AccountDb<T> for DirectAccountDb {
...
+						.map(|old_value| old_value.len() as u32)
+						.unwrap_or(0);
+					let new_value_len = opt_new_value
+						.as_ref()
+						.map(|new_value| new_value.len() as u32)
+						.unwrap_or(0);
+					new_info.storage_size = new_info
+						.storage_size
+						.saturating_sub(prev_value_len)
+						.saturating_add(new_value_len);
```
Comment (athei) [inline frame/contracts/src/account_db.rs:278]: We are unsigned. You need to swap those in order to prevent the value to saturate to zero in between.

File: frame/contracts/src/lib.rs [hunk 4]
```diff
@@ -203,8 +203,15 @@ pub type AliveContractInfo<T> =
...
-	/// The size of stored value in octet.
+	/// The total number of bytes used by this contract.
+	///
+	/// It is a sum of each key-value pair stored by this contract.
 	pub storage_size: u32,
+	/// The number of key-value pairs that have values of zero length.
+	/// The condition `empty_pair_count ≤ total_pair_count` always holds.
+	pub empty_pair_count: u32,
+	/// The total number of key-value pairs in storage of this contract.
+	pub total_pair_count: u32,
```
Comment (athei) [inline frame/contracts/src/lib.rs:214]: What to we need this value for? I see that it is updated but never used for anything. Only the empty values are used.

File: frame/contracts/src/account_db.rs [hunk 5]
```diff
@@ -285,7 +348,9 @@ impl<'a, T: Trait> OverlayAccountDb<'a, T> {
 		}
 
 		let mut local = self.local.borrow_mut();
-		let contract = local.entry(account.clone()).or_insert_with(|| Default::default());
+		let contract = local
+			.entry(account.clone())
+			.or_insert_with(|| Default::default());
```
Comment (NikVolf) [inline frame/contracts/src/account_db.rs:353]:
```suggestion
		let contract = local.entry(account.clone()).or_default();
```

File: frame/contracts/src/lib.rs (hunk 1 above)
Comment (pepyakin) [reply frame/contracts/src/lib.rs:351]: Thanks! I apply it by myself though since otherwise it'd exceed the line width

File: frame/contracts/src/lib.rs (hunk 4 above)
Comment (pepyakin) [reply frame/contracts/src/lib.rs:214]: Well noticed! 

I figured that since we are counting `empty_pair_count` it might be useful to collect the total pair count in case we (or the governance) find itself in need of the number of non-empty pairs. For example, charge a constant fee per a kv pair. 

If we don't introduce it here they (the governance) would need to painfully collect and submit that info should the need arise. OTOH, the difference in performance should be negligible and the logic seems to be straightforward.

However, I don't feel strong about this. I can roll this back as well if you think that is not a good reason.

File: frame/contracts/src/account_db.rs (hunk 3 above)
Comment (pepyakin) [reply frame/contracts/src/account_db.rs:278]: Sure! But fwiw note that we must never underflow here, it must be guaranteed by the foregoing logic.

Comment (athei) [reply frame/contracts/src/account_db.rs]: Did not know that. Still think that is makes sense to swap it for clarity.

File: frame/contracts/src/lib.rs (hunk 4 above)
Comment (athei) [reply frame/contracts/src/lib.rs:214]: From a runtime standpoint is is negligible of course. I was thinking about storage overhead. But I think that is also OK when compared to all the other data that is stored. I am OK with keeping it.
