### PR TITLE
contracts: Remove weight pre charging

### LINKED ISSUE #8693: pallet-contracts: Gas estimation is too low
@athei We thought it's an UI issue at first (https://github.com/polkadot-js/apps/issues/5156, https://github.com/paritytech/canvas-ui/issues/95), but now it seems like a `contracts` pallet bug.

The estimated "max gas value" which the UI's pre-fill for contract calls is for some calls significantly lower than the required gas. So the pre-filling is actually incorrect and the call cannot be executed with the default settings (breaking e.g. our tutorials, which should work with default settings).

## How to reproduce

We've found that at least the ink! examples `delegator` and `contract-terminate` are affected. `contract-terminate` is the easiest to reproduce the bug with. I've attached the contract which can be used for deployment here: [contract_terminate.contract.zip](https://github.com/paritytech/substrate/files/6393496/contract_terminate.contract.zip).

The contract has only one method `terminate_me`, the polkadot-js UI suggests a default `Max Gas Allowed` of 1417, but the contract then fails with `system.ExtrinsicFailed: contracts.OutOfGas`.

It works if the max gas is set manually to 2500.

You can e.g. use the latest [`canvas-node`](https://github.com/paritytech/canvas-node), it has been adjusted to the Substrate `HEAD` just this week. `canvas-ui` is also affected by this.

screenshot-polkadot js org-2021 04 28-10_51_34

For the simple contracts (`flipper`, etc.) the estimation seems to work fine. Those two affected contracts do either cross-contract calls or call `seal_terminate`.

### PR DESCRIPTION
**Pull request by athei**
Fixes #8693

Please see the linked issue for an explanation of the rationale. I merely describe the three chunks of work this fix consists of that also correspond to the initial commits:

### Remove pre-charging for code size

#8086 added a mechanism that charges weight when accessing a wasm blob based off its size. See this PR for a detailed explanation.  The way this was done is by pre charging a maximum weight (based on the maximum allowed size for a wasm blob) and refund it after the blob was loaded and the size was determined. This approach was chosen to keep the methodical approach of charging weight on **entry** (extrinsinc, contract API) where the code size is unknown rather than spreading weight charging all over the code.

However, this pre charging was problematic for all the reasons already explained in #8693.  As a result we move to a model of charging the weight much deeper into the execution where we can easily access the size of the wasm blob without loading it from storage. This gets rid of the pre charging and also removes the need for passing around the wasm size.

### Remove pre-charging when reading values of fixed size

Reading values of a fixed type like `T::Balance` from a contract places us in a difficult position. Those have a fixed size in SCALE encoded form but the latter is unknown at compile time. This means when reading those values from contract memory we still need the untrusted contract to supply the size of encoded value it is passing. This requires us to account for the case where the contract passes a too large size for the passed value inducing processing costs for copying the data before decoding it. This is awkward to benchmark because in reality the value has a fixed size. In order to prevent the creation of many basically useless benchmarks we opted for charging some generic costs based off the supplied size and refund that after a successful decoding. Refunding is performed because the costs of reading fixed size types are included by any benchmark making use of that value. It is only to defend against an attack where a too large input size if supplied for a given type (which will fail because of `decode_all`).

With the introduction of [`MaxEncodeLen`](https://github.com/paritytech/substrate/pull/8720) we finally gain the ability to determine the fixed size at compile time. We use this trait to ignore the length passed by the contract and use the length exposed by the trait instead. This makes pre charging no longer needed because we don't use any untrusted length parameters anymore.

### Add new versions of API functions that leave out parameters

With the addition of `MaxEncodeLen` we can remove all length parameters belonging to fixed sized types. We added a new version for each API where this is the case. The unstable new `call` API is als modified to have those parameters removed ( cc @cmichi ).

### CODE REVIEW

**Review by cmichi — APPROVED** [review]
I'm not too familiar with the `contracts` pallet code, can't see any obvious issues though.

File: frame/contracts/src/exec.rs [hunk 1]
```diff
@@ -336,6 +331,10 @@ pub trait Executable<T: Config>: Sized {
 	/// A code module is re-instrumented on-load when it was originally instrumented with
 	/// an older schedule. This skips this step for cases where the code storage is
 	/// queried for purposes other than execution.
+	///
+	/// # Note
+	///
+	/// Does not charge from the gas meter. Do not in contexts where this is important.
```
Comment (apopiak) [inline frame/contracts/src/exec.rs:337]:
```suggestion
	/// Does not charge from the gas meter. Do not call in contexts where this is important.
```

File: frame/contracts/src/wasm/code_cache.rs [hunk 2]
```diff
@@ -185,14 +199,50 @@ fn increment_64(refcount: &mut u64) {
...
-		T::WeightInfo::instrument(self.0 / 1024)
+		use self::CodeToken::*;
+		// In case of `Load` and `UpdateRefcount` we already covered the general costs of
+		// accessing the storage but still need to account for the actual size of the
+		// contract code. This is why we substract `T::*::(0)`. We need to do this at this
+		// point because when charging the general weight we do not know the size of
+		// the contract.
+		match *self {
+			Instrument(len) => T::WeightInfo::instrument(len / 1024),
+			Load(len) => T::WeightInfo::code_load(len / 1024) - T::WeightInfo::code_load(0),
```
Comment (apopiak) [inline frame/contracts/src/wasm/code_cache.rs:243]:
```suggestion
			Load(len) => T::WeightInfo::code_load(len / 1024).saturating_sub(T::WeightInfo::code_load(0)),
```

File: frame/contracts/src/wasm/code_cache.rs [hunk 3]
```diff
@@ -185,14 +199,50 @@ fn increment_64(refcount: &mut u64) {
...
+			UpdateRefcount(len) =>
+				T::WeightInfo::code_refcount(len / 1024) - T::WeightInfo::code_refcount(0),
```
Comment (apopiak) [inline frame/contracts/src/wasm/code_cache.rs:245]:
```suggestion
				T::WeightInfo::code_refcount(len / 1024).saturating_sub(T::WeightInfo::code_refcount(0)),
```
or a comment why it's safe :-)

File: frame/contracts/src/wasm/runtime.rs [hunk 4]
```diff
@@ -1487,10 +1545,9 @@ define_env!(Env, <E: Ext>,
 	// - value_ptr: a pointer to the buffer with value, how much to allow for rent
 	//   Should be decodable as a `T::Balance`. Traps otherwise.
 	// - value_len: length of the value buffer.
-	[seal0] seal_set_rent_allowance(ctx, value_ptr: u32, value_len: u32) => {
+	[seal0] seal_set_rent_allowance(ctx, value_ptr: u32, _value_len: u32) => {
```
Comment (apopiak) [inline frame/contracts/src/wasm/runtime.rs:1548]: why not introduce a v1 for this?

Comment (athei) [reply frame/contracts/src/wasm/runtime.rs:1554]: Good catch. Added.

**Review by thiolliere — APPROVED** [review]
One nitpick and one note, but otherwise looks good to me

File: frame/contracts/src/weights.rs [hunk 5]
```diff
@@ -152,1311 +153,1299 @@ pub trait WeightInfo {
...
+			// Standard Error: 114_000
+			.saturating_add((164_981_000 as Weight).saturating_mul(r as Weight))
 			.saturating_add(T::DbWeight::get().reads(4 as Weight))
 			.saturating_add(T::DbWeight::get().writes(1 as Weight))
 	}
 	fn seal_set_storage(r: u32, ) -> Weight {
-		(47_131_000 as Weight)
-			// Standard Error: 931_000
-			.saturating_add((4_033_062_000 as Weight).saturating_mul(r as Weight))
+		(549_424_000 as Weight)
```
[the remark this answers is not in the document]
Comment (athei) [reply frame/contracts/src/weights.rs:401]: I have no idea how this was causes. But the value is not important. It is never used because it is the start-up time of the sandbox and not the cost of the actual call. The final value is calculated as  `seal_set_storage(1) - seal_set_storage(0)`.

Mind the error. It is pretty big. I think this is expected and OK.

[the remark this answers is not in the document]
Comment (thiolliere) [reply frame/contracts/src/weights.rs:401]: ah it is used like this, then yes it is definitely ok

**Comment by athei** [comment]
Sorry for pinging you all. I fucked up the merge. Will fix.

**Comment by athei** [comment]
bot merge
