### PR TITLE
Expunge error-chain (feat. tomaka)

### LINKED ISSUE #1547: Replace `error-chain`
With the latest nightlies, rust spits out a warning about using a deprecated method of the `Error` trait. See [here](https://github.com/rust-lang-nursery/error-chain/issues/254) for more information. 
As `error-chain` is in maintenance mode and its unlikely that there will be any real new stuff, we should watch out for what is the new way of error reporting in rust. (Failure probably already failed).

### PR DESCRIPTION
**Pull request by tomusdrw**
Resolves #1547 

A lot of difficult stuff has been done by @tomaka as we started to work on that in parallel, but luckily on different crates so it happily converged :)

Note there are quite some changes in error APIs (no more `ErrorKind` stuff)

### CODE REVIEW

File: core/consensus/slots/src/lib.rs [hunk 1]
```diff
@@ -66,8 +66,9 @@ pub trait SlotCompatible {
 }
 
 /// Convert an inherent error to common error.
+#[deprecated(note = "This method doesn't make sense")]
```
Comment (tomaka) [inline core/consensus/slots/src/lib.rs]: I think I'm the one who wrote that, but the message isn't great :sweat_smile:

Comment (bkchr) [reply core/consensus/slots/src/lib.rs]: If it is deprecated, remove it.
