### PR TITLE
Emit error when construct_runtime imports a non-existent pallet part

### LINKED ISSUE #8945: Issue compiler error when construct_runtime attempts to import a non-existing pallet part
When I have the following pallet defined:

```rust
#[frame_support::pallet]
pub mod pallet {
    #[pallet::pallet]
    pub struct Pallet<T>(_);

    #[pallet::config]
    pub trait Config: frame_system::Config {}
}
```

and have this corresponding runtime:

```rust
construct_runtime!(
    //...
    Pallet: pallet::{Pallet, Call},
)
```

Compilation should fail, since `pallet` does not contain a `#[pallet::call]` defining the calls for the pallet.

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #8945.

This PR causes an error to be thrown during compilation when Substrate detects that your `construct_runtime` is importing a pallet part that has not been declared by the pallet in question. 

The expected UI for this error looks like the following:

```
error: Pallet does not have #[pallet::call] defined, perhaps you should remove it from `construct_runtime`?
  --> $DIR/undefined_call_part.rs:3:1
   |
3  |   #[frame_support::pallet]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^
...
12 | / construct_runtime! {
13 | |     pub enum Runtime where
14 | |         Block = Block,
15 | |         NodeBlock = Block,
...  |
20 | |     }
21 | | }
   | |_- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

polkadot companion: paritytech/polkadot#3216

### CODE REVIEW

**Comment by KiChjang** [comment]
I wanted to add a UI test for this, and I had the following under the `construct_runtime_ui` directory:

```rust
use frame_support::construct_runtime;

#[frame_support::pallet]
mod pallet {
	#[pallet::config]
	pub trait Config: frame_system::Config {}

	#[pallet::pallet]
	pub struct Pallet<T>(_);
}

construct_runtime! {
	pub enum Runtime where
		Block = Block,
		NodeBlock = Block,
		UncheckedExtrinsic = UncheckedExtrinsic
	{
		System: system::{Pallet},
		Pallet: pallet::{Pallet, Call},
	}
}

fn main() {}
```

This does generate the compiler error that I expect, but with a lot more junk associated with it:

<details>

```
error: Pallet does not have #[pallet::call] defined. Did you forget to include it?
  --> $DIR/undefined_call_part.rs:3:1
   |
3  |   #[frame_support::pallet]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^
...
12 | / construct_runtime! {
13 | |     pub enum Runtime where
14 | |         Block = Block,
15 | |         NodeBlock = Block,
...  |
20 | |     }
21 | | }
   | |_- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `system`
  --> $DIR/undefined_call_part.rs:18:11
   |
18 |         System: system::{Pallet},
   |                 ^^^^^^ use of undeclared crate or module `system`

error[E0412]: cannot find type `UncheckedExtrinsic` in this scope
  --> $DIR/undefined_call_part.rs:16:24
   |
16 |         UncheckedExtrinsic = UncheckedExtrinsic
   |                              ^^^^^^^^^^^^^^^^^^ not found in this scope
   |
help: consider importing this struct
   |
1  | use sp_runtime::generic::UncheckedExtrinsic;
   |

error[E0412]: cannot find type `Block` in this scope
  --> $DIR/undefined_call_part.rs:15:15
   |
15 |         NodeBlock = Block,
   |                     ^^^^^ not found in this scope
   |
help: consider importing one of these items
   |
1  | use sp_runtime::generic::Block;
   |
1  | use sp_runtime::testing::Block;
   |
1  | use sp_runtime::traits::Block;
   |

error[E0412]: cannot find type `Block` in this scope
  --> $DIR/undefined_call_part.rs:14:11
   |
14 |         Block = Block,
   |                 ^^^^^ not found in this scope
   |
help: consider importing one of these items
   |
1  | use sp_runtime::generic::Block;
   |
1  | use sp_runtime::testing::Block;
   |
1  | use sp_runtime::traits::Block;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `system`
  --> $DIR/undefined_call_part.rs:12:1
   |
12 | / construct_runtime! {
13 | |     pub enum Runtime where
14 | |         Block = Block,
15 | |         NodeBlock = Block,
...  |
20 | |     }
21 | | }
   | |_^ not found in `system`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this enum
   |
1  | use frame_system::RawOrigin;
   |

error[E0277]: the trait bound `Runtime: pallet::Config` is not satisfied
  --> $DIR/undefined_call_part.rs:12:1
   |
12 | / construct_runtime! {
13 | |     pub enum Runtime where
14 | |         Block = Block,
15 | |         NodeBlock = Block,
...  |
20 | |     }
21 | | }
   | |_^ the trait `pallet::Config` is not implemented for `Runtime`
   |
   = note: required because of the requirements on the impl of `Callable<Runtime>` for `pallet::Pallet<Runtime>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Runtime: pallet::Config` is not satisfied
  --> $DIR/undefined_call_part.rs:12:1
   |
12 | / construct_runtime! {
13 | |     pub enum Runtime where
14 | |         Block = Block,
15 | |         NodeBlock = Block,
...  |
20 | |     }
21 | | }
   | |_^ the trait `pallet::Config` is not implemented for `Runtime`
   |
   = note: required because of the requirements on the impl of `Callable<Runtime>` for `pallet::Pallet<Runtime>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Runtime: pallet::Config` is not satisfied
  --> $DIR/undefined_call_part.rs:12:1
   |
12 | / construct_runtime! {
13 | |     pub enum Runtime where
14 | |         Block = Block,
15 | |         NodeBlock = Block,
...  |
20 | |     }
21 | | }
   | |_^ the trait `pallet::Config` is not implemented for `Runtime`
   |
   = note: required because of the requirements on the impl of `Callable<Runtime>` for `pallet::Pallet<Runtime>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Runtime: pallet::Config` is not satisfied
   --> $DIR/undefined_call_part.rs:12:1
    |
12  | / construct_runtime! {
13  | |     pub enum Runtime where
14  | |         Block = Block,
15  | |         NodeBlock = Block,
...   |
20  | |     }
21  | | }
    | |_^ the trait `pallet::Config` is not implemented for `Runtime`
    |
   ::: /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-scale-codec-2.1.0/src/codec.rs:270:19
    |
270 |   pub trait Decode: Sized {
    |                     ----- required by this bound in `Decode`
    |
    = note: required because of the requirements on the impl of `Callable<Runtime>` for `pallet::Pallet<Runtime>`
    = note: required because it appears within the type `Call`
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Runtime: pallet::Config` is not satisfied
  --> $DIR/undefined_call_part.rs:12:1
   |
12 | / construct_runtime! {
13 | |     pub enum Runtime where
14 | |         Block = Block,
15 | |         NodeBlock = Block,
...  |
20 | |     }
21 | | }
   | |_^ the trait `pallet::Config` is not implemented for `Runtime`
   |
  ::: /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-scale-codec-2.1.0/src/encode_like.rs:73:41
   |
73 |   pub trait EncodeLike<T: Encode = Self>: Sized + Encode {}
   |                                           ----- required by this bound in `EncodeLike`
   |
   = note: required because of the requirements on the impl of `Callable<Runtime>` for `pallet::Pallet<Runtime>`
   = note: required because it appears within the type `Call`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Runtime: pallet::Config` is not satisfied
   --> $DIR/undefined_call_part.rs:12:1
    |
12  | / construct_runtime! {
13  | |     pub enum Runtime where
14  | |         Block = Block,
15  | |         NodeBlock = Block,
...   |
20  | |     }
21  | | }
    | |_^ the trait `pallet::Config` is not implemented for `Runtime`
    |
   ::: $RUST/core/src/clone.rs
    |
    |   pub trait Clone: Sized {
    |                    ----- required by this bound in `Clone`
    |
    = note: required because of the requirements on the impl of `Callable<Runtime>` for `pallet::Pallet<Runtime>`
    = note: required because it appears within the type `Call`
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Runtime: pallet::Config` is not satisfied
  --> $DIR/undefined_call_part.rs:12:1
   |
12 | / construct_runtime! {
13 | |     pub enum Runtime where
14 | |         Block = Block,
15 | |         NodeBlock = Block,
...  |
20 | |     }
21 | | }
   | |_^ the trait `pallet::Config` is not implemented for `Runtime`
   |
   = note: required because of the requirements on the impl of `Callable<Runtime>` for `pallet::Pallet<Runtime>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Runtime: pallet::Config` is not satisfied
  --> $DIR/undefined_call_part.rs:12:1
   |
12 | / construct_runtime! {
13 | |     pub enum Runtime where
14 | |         Block = Block,
15 | |         NodeBlock = Block,
...  |
20 | |     }
21 | | }
   | |_^ the trait `pallet::Config` is not implemented for `Runtime`
   |
   = note: required because of the requirements on the impl of `Callable<Runtime>` for `pallet::Pallet<Runtime>`
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Runtime: pallet::Config` is not satisfied
   --> $DIR/undefined_call_part.rs:12:1
    |
12  | / construct_runtime! {
13  | |     pub enum Runtime where
14  | |         Block = Block,
15  | |         NodeBlock = Block,
...   |
20  | |     }
21  | | }
    | |_^ the trait `pallet::Config` is not implemented for `Runtime`
    |
   ::: $RUST/core/src/result.rs
    |
    |   pub enum Result<T, E> {
    |                   - required by this bound in `Result`
    |
    = note: required because of the requirements on the impl of `Callable<Runtime>` for `pallet::Pallet<Runtime>`
    = note: required because it appears within the type `Call`
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

</details>

File: frame/support/src/dispatch.rs [hunk 1]
```diff
@@ -2173,6 +2173,7 @@ macro_rules! impl_outer_dispatch {
 			)*
 		}
 	) => {
+		$($module::__is_call_part_defined!();)*
```
Comment (KiChjang) [inline frame/support/src/dispatch.rs:2176]: This really shouldn't be here since this file's part of FRAMEv1. I don't think FRAMEv1 macros can actually support this, so I'll have to migrate this logic to FRAMEv2.

File: frame/support/procedural/src/pallet/expand/call.rs [hunk 2]
```diff
@@ -89,7 +107,27 @@ pub fn expand_call(def: &mut Def) -> proc_macro2::TokenStream {
 		&docs[..]
 	};
 
+	let maybe_compile_error = if def.call.is_none() {
+		quote::quote!{
+			compile_error!("Pallet does not have #[pallet::call] defined. Did you forget to include it?");
```
Comment (shawntabrizi) [inline frame/support/procedural/src/pallet/expand/call.rs:112]: Can we name the pallet here?

More likely the response should be "Maybe you should remove `Call`" rather than "did you forget to include it"

Comment (KiChjang) [reply frame/support/procedural/src/pallet/expand/call.rs]: The latest changes have made it so that `#[pallet::call]` is entirely optional, so their pallet wouldn't be broken if they missed it out.

However I do agree that it's better to shift the perspective from the pallet author and into the runtime creator. I've reworded the compiler error message accordingly.

**Comment by thiolliere** [comment]
yes this is an improvment,

a sidenote: when we implement this: https://github.com/paritytech/substrate/issues/8084 use will only give part not to include, and construct_runtime should be able to get all the available part of a pallet. Thus we can check that the "part not to include" specified by the user are sensible.

That makes me think of yet another improvement: currently when people forget to specify in their cargo.toml to compile the pallet crate with "std" feature, then the genesis config type is not available, when they are confused why the compiler say it can't find GenesisConfig.
With a similar trick as you propose we can have a macro: `__is_std_enabled!` which would be called before accessing the genesis config type. The macro `__is_std_enabled!` would fail saying that the pallet is not compile with std, in case ppl failed their cargo.toml definition.

File: frame/support/src/dispatch.rs (hunk 1 above)
Comment (thiolliere) [reply frame/support/src/dispatch.rs]: I guess as long as we support FRAMEv1 then the FRAMEv1 macro should at least create a dummy `__is_call_part_defined` in order to be forward compatible

Comment (KiChjang) [reply frame/support/src/dispatch.rs]: For the case of the `Call` part, this is relatively easy since `decl_module` is mandatory (I think?) for every pallet, but for parts that aren't, they would not be able to create a dummy macro for forwards compatibility.

I think what we can do instead is since `decl_module` is mandatory, we just generate all necessary dummy macro definitions there.

**Comment by KiChjang** [comment]
> User @Boiethios, please sign the CLA [here](https://cla.parity.io/sign_cla/18555389/3).

wat

**Comment by KiChjang** [comment]
So I'm really liking the suggestion made by @shawntabrizi over the FRAME steering call, where we create a brand new `construct_runtime_v2` macro and document it so that it only works for FRAMEv2 macros, instead of trying to make FRAMEv1 macros forward-compatible with this PR.

This has an intended side effect of telling people "hey, look at all the cool stuff you can do with FRAMEv2" and incentivizing them to migrate over to v2 as soon as possible.

**Comment by KiChjang** [comment]
I just realized, we actually do not generate any code for `Storage` parts, so IMO we can actually remove this from the list of parts that we can import.

**Comment by KiChjang** [comment]
> With a similar trick as you propose we can have a macro: `__is_std_enabled!` which would be called before accessing the genesis config type. The macro `__is_std_enabled!` would fail saying that the pallet is not compile with std, in case ppl failed their cargo.toml definition.

There's actually an even neater trick: by the usage of conditional compilation with `#[cfg(not(feature = "std"))]`, we can actually make it so that the `compile_error!` appears whenever the crate itself is not compiled using the std feature.

**Comment by thiolliere** [comment]
> > With a similar trick as you propose we can have a macro: `__is_std_enabled!` which would be called before accessing the genesis config type. The macro `__is_std_enabled!` would fail saying that the pallet is not compile with std, in case ppl failed their cargo.toml definition.
> 
> There's actually an even neater trick: through the usage of conditional compilation with `#[cfg(not(feature = "std"))]`, we can actually make it so that the `compile_error!` appears whenever the crate itself is not compiled using the std feature.

yes this is what I meant, if the runtime is compiled with std, but the pallet is not compiled with std.

**Comment by thiolliere** [comment]
Do you want to implement the std check in this PR ?

**Comment by KiChjang** [comment]
Let's keep the `std` check separate, it'd be easier to audit commits/PRs if anything goes wrong in the implementation.

**Comment by shawntabrizi** [comment]
@KiChjang Hey, sorry for the delay in looking at this again.

I like the idea to have a new `construct_runtime_v2` macro, but my though is that the whole V2 macro stuff is supposed to move us away from "custom syntax" and have everything be attribute macros to what would otherwise be real rust code.

I think when creating this new macro, you should follow in those footsteps.

So something like:

```
#[construct_runtime]
pub enum Runtime<Block, Block, UncheckedExtrinsic>
{
	System(frame_system),
	Balances(pallet_balances),
}
```

Is this possible?

**Comment by KiChjang** [comment]
From the surface of it, we would really need a new syntax that conforms to Rust conventions when importing pallet parts, and since pallet parts themselves are fragments of source code (instead of a Rust data structure neatly packaged into one), it isn't quite clear to me how exactly we can import/include them with a Rust-like syntax.

**Comment by thiolliere** [comment]
> So something like:
> 
> ```
> #[construct_runtime]
> pub enum Runtime<Block, Block, UncheckedExtrinsic>
> {
> 	System(frame_system),
> 	Balances(pallet_balances),
> }
> ```
> 
> Is this possible?

yes it is possible, if we are thinking about a v2 for construct_runtime these are my thougths:
* maybe remove `UncheckedExtrinsic` type, as the trait `Block` has `Extrinsic` associated type, so one can simply use: `<Block as BlockTrait>::Extrinsic`. But I have to double check that unchecked extrinsic is not needed in some specific context.

*  I am not sure we can make a rust-idiomatic syntax. The macro is taking: a set of pallets and their configuration, some types (block, node block), and is generating:
  * `AllPallets`, `AllPalletsWithSystem` (we should probably use AllPalletsWithSystem everywhere, I didn't look deeply but it seems there is no need to exclude it now).
  * `Event`, `Origin`, `Call`, `GenesisConfig` those are enum type which aggregate pallets ones
  * `check_extrinsic` `create_extrinsic` methods for checking inherent data
  * some handy type alias like `$(PalletName)Config`.
  * `Runtime` which is just a placeholder
  I personally don't know how any of these generation could look like real rust and be not boilerplate.

* IMHO if it looks like rust but the generation is actually something different, it can be more confusing than helpful. Like in your example the `Runtime` struct is not generic, and is not an enum and doesn't have a variant for each pallet. People would get confused that the runtime type doesn't look like how it is declared.

* Best should be to ask the input in a specific syntax which allows to easily configure stuff per pallet
  (currently we have `= $n` syntax to give the index to use when deriving codec, but I expect we would have more of these kind of configuration in the future: like the order of on_initialize maybe).
  
Maybe something like this, but I don't like that it is too verbose:
```rust
construct_runtime!(
	NodeBlock = $type;
	Block = $type; // Maybe rename to runtime block ?
	Pallets = {
		System = { // Name of the pallet
			patch = $path; // Path to the pallet
			instance = $type; // Optional instance type
			codec_index = $n; // Optional index used for variant index
			parts = { Config, Storage }; // Optional if not specified then use the default parts when implement
			without_parts = { Call }; // Optional
		},
		...
	}
);
```

But actually I find the current construct_runtime not bad, what is the main complain about it ?

**Comment by thiolliere** [comment]
This PR https://github.com/paritytech/substrate/pull/9044 should be merged before.

File: frame/support/procedural/src/construct_runtime/expand/call.rs [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+					}
+				}
+			}
+
+			impl From<#scrate::dispatch::CallableCallFor<#pallet_names, #runtime>> for Call {
+				fn from(call: #scrate::dispatch::CallableCallFor<#pallet_names, #runtime>) -> Self {
+					#variant_patterns
+				}
+			}
+		)*
```
Comment (thiolliere) [inline frame/support/procedural/src/construct_runtime/expand/call.rs:147]: I think there should be a test for each of those functions somewhere, probably in "frame/support/test/tests/construct_runtime.rs",
Some test existed in frame/support/src/dispatch.rs but some might be missing. A single test per method should be enough

File: frame/support/procedural/src/construct_runtime/expand/config.rs [hunk 4]
```diff
@@ -24,14 +24,18 @@ pub fn expand_outer_config(
 	runtime: &Ident,
 	pallet_decls: &[Pallet],
 	scrate: &TokenStream,
+	use_v2: bool,
```
Comment (thiolliere) [inline frame/support/procedural/src/construct_runtime/expand/config.rs:27]: as concluded offline we can activate it everywhere I think.

File: frame/support/procedural/src/construct_runtime/expand/inherent.rs [hunk 5]
```diff
@@ -0,0 +1,206 @@
...
+					}
+
+					if first_signed_observed && is_inherent {
+						return Err(i as u32)
+					}
+				}
+
+				Ok(())
+			}
+		}
```
Comment (thiolliere) [inline frame/support/procedural/src/construct_runtime/expand/inherent.rs:204]: this expansion should be tested, there is test in frame/support/src/inherents.rs you can take inspiration from them.

File: frame/support/procedural/src/construct_runtime/expand/unsigned.rs [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+				source: #scrate::unsigned::TransactionSource,
+				call: &Self::Call,
+			) -> #scrate::unsigned::TransactionValidity {
+				#[allow(unreachable_patterns)]
+				match call {
+					#( Call::#pallet_names(inner_call) => #pallet_names::validate_unsigned(source, inner_call), )*
+					_ => #scrate::unsigned::UnknownTransaction::NoUnsignedValidator.into(),
+				}
+			}
+		}
```
Comment (thiolliere) [inline frame/support/procedural/src/construct_runtime/expand/unsigned.rs:72]: I know there wasn't test for it in frame/support/src/validate_unsigned, but a small test for them in frame/support/test/test/construct_runtime.rs would be better.

**Review by thiolliere — COMMENTED** [review]
some test for the new generation code should be written, and v2 can be activated everywhere, otherwise looks good to me

**Comment by KiChjang** [comment]
```
error: `Authorship` does not have #[pallet::inherent] defined, perhaps you should remove `Inherent` from construct_runtime?
   --> frame/authorship/src/lib.rs:128:1
    |
128 |   #[frame_support::pallet]
    |   ^^^^^^^^^^^^^^^^^^^^^^^^
...
430 | /     frame_support::construct_runtime!(
431 | |         pub enum Test where
432 | |             Block = Block,
433 | |             NodeBlock = Block,
...   |
438 | |         }
439 | |     );
    | |______- in this macro invocation
```

Holy crud, it's actually catching real errors in the pallets that we wrote!

**Comment by KiChjang** [comment]
```
error[E0659]: `__is_call_part_defined` is ambiguous (glob import vs macro-expanded name in the same module during import/macro resolution)
   --> frame/sudo/src/mock.rs:104:1
    |
104 | / frame_support::construct_runtime!(
105 | |     pub enum Test where
106 | |         Block = Block,
107 | |         NodeBlock = Block,
...   |
113 | |     }
114 | | );
    | |__^ ambiguous name
    |
note: `__is_call_part_defined` could refer to the macro imported here
   --> frame/sudo/src/mock.rs:45:12
    |
45  |     #[pallet::call]
    |               ^^^^
note: `__is_call_part_defined` could also refer to the macro imported here
   --> frame/sudo/src/mock.rs:34:6
    |
34  |     use super::*;
    |         ^^^^^^^^
    = help: consider adding an explicit import of `__is_call_part_defined` to disambiguate
```

Sounds like I should box the macros inside a module to solve this problem...

**Comment by thiolliere** [comment]
> Holy crud, it's actually catching real errors in the pallets that we wrote!

What is good is that any pallet which uses construct_runtime is its test with all its parts, will ensure its declaration is correct

File: frame/support/test/tests/pallet.rs [hunk 7]
```diff
@@ -320,22 +320,40 @@ pub mod pallet {
...
+				Call::foo(..) => Ok(()),
+				_ => unreachable!("other calls are not inherents"),
+			}
+		}
+
+		fn is_inherent_required(d: &InherentData) -> Result<Option<Self::Error>, Self::Error> {
+			match d.get_data::<bool>(b"required") {
+				Ok(Some(true)) => Ok(Some(InherentError::Fatal)),
+				Ok(Some(false)) | Ok(None) => Ok(None),
+				Err(_) => unreachable!("should now happen in tests"),
```
Comment (thiolliere) [inline frame/support/test/tests/pallet.rs:346]:
```suggestion
				Err(_) => unreachable!("should not happen in tests"),
```

File: frame/support/procedural/src/pallet/expand/call.rs [hunk 8]
```diff
@@ -31,7 +32,7 @@ pub fn expand_call(def: &mut Def) -> proc_macro2::TokenStream {
 
 			(span, where_clause, methods, docs)
 		}
-		None => (def.pallet_struct.attr_span, None, Vec::new(), Vec::new()),
+		None => (def.item.span(), None, Vec::new(), Vec::new()),
 	};
```
Comment (thiolliere) [inline frame/support/procedural/src/pallet/expand/call.rs:36]: I'm not sure it makes sense anymore to declare a dummy Call enum in case `#[pallet::call]` is not define, because construct_runtime will forbid its usage.
So the dummy Call enum should not be usable anymore. Maybe we can do in a follow-up though

**Review by thiolliere — APPROVED** [review]
looks good to me

**Comment by KiChjang** [comment]
```
EXPECTED:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0277]: the trait bound `Bar: MaxEncodedLen` is not satisfied
  --> $DIR/storage_info_unsatisfied_nmap.rs:10:12
   |
10 |     #[pallet::generate_storage_info]
   |               ^^^^^^^^^^^^^^^^^^^^^ the trait `MaxEncodedLen` is not implemented for `Bar`
   |
   = note: required because of the requirements on the impl of `KeyGeneratorMaxEncodedLen` for `NMapKey<frame_support::Twox64Concat, Bar>`
   = note: required because of the requirements on the impl of `StorageInfoTrait` for `frame_support::pallet_prelude::StorageNMap<_GeneratedPrefixForStorageFoo<T>, NMapKey<frame_support::Twox64Concat, Bar>, u32>`
   = note: required by `storage_info`
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
ACTUAL OUTPUT:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0277]: the trait bound `Bar: MaxEncodedLen` is not satisfied
  --> $DIR/storage_info_unsatisfied_nmap.rs:10:12
   |
10 |     #[pallet::generate_storage_info]
   |               ^^^^^^^^^^^^^^^^^^^^^ the trait `MaxEncodedLen` is not implemented for `Bar`
   |
   = note: required because of the requirements on the impl of `KeyGeneratorMaxEncodedLen` for `Key<frame_support::Twox64Concat, Bar>`
   = note: required because of the requirements on the impl of `StorageInfoTrait` for `frame_support::pallet_prelude::StorageNMap<_GeneratedPrefixForStorageFoo<T>, Key<frame_support::Twox64Concat, Bar>, u32>`
   = note: required by `storage_info`
```

WTF? How did my PR change the renamed import of `NMapKey` back to `Key`?

**Comment by shawntabrizi** [comment]
@KiChjang UI tests have been really funky in the last few days... just make the CI happy and we can figure out the specific details later

File: bin/node/runtime/src/lib.rs [hunk 9]
```diff
@@ -1152,8 +1152,8 @@ construct_runtime!(
 		Contracts: pallet_contracts::{Pallet, Call, Storage, Event<T>},
 		Sudo: pallet_sudo::{Pallet, Call, Config<T>, Storage, Event<T>},
 		ImOnline: pallet_im_online::{Pallet, Call, Storage, Event<T>, ValidateUnsigned, Config<T>},
-		AuthorityDiscovery: pallet_authority_discovery::{Pallet, Call, Config},
-		Offences: pallet_offences::{Pallet, Call, Storage, Event},
+		AuthorityDiscovery: pallet_authority_discovery::{Pallet, Config},
+		Offences: pallet_offences::{Pallet, Storage, Event},
```
Comment (shawntabrizi) [inline bin/node/runtime/src/lib.rs:1156]: 👍

File: frame/support/procedural/src/construct_runtime/expand/call.rs [hunk 10]
```diff
@@ -0,0 +1,145 @@
...
+		}
+
+		#(
+			impl #scrate::traits::IsSubType<#scrate::dispatch::CallableCallFor<#pallet_names, #runtime>> for Call {
+				#[allow(unreachable_patterns)]
+				fn is_sub_type(&self) -> Option<&#scrate::dispatch::CallableCallFor<#pallet_names, #runtime>> {
+					match self {
+						#variant_patterns => Some(call),
+						// May be unreachable
+						_ => None,
```
Comment (shawntabrizi) [inline frame/support/procedural/src/construct_runtime/expand/call.rs:133]: Why is it maybe?

File: frame/support/procedural/src/construct_runtime/expand/inherent.rs [hunk 11]
```diff
@@ -0,0 +1,204 @@
...
+	}
+}
```
Comment (shawntabrizi) [inline frame/support/procedural/src/construct_runtime/expand/inherent.rs:204]: update your editor to add a EOL to the end of files

File: frame/support/procedural/src/construct_runtime/expand/call.rs (hunk 10 above)
Comment (KiChjang) [reply frame/support/procedural/src/construct_runtime/expand/call.rs:133]: I simply copied and pasted code from `frame/support/src/call.rs`, but reading the code here, it may be the case where `variant_patterns` already contains an exhaustive list of the enum variants for `Call`, or it may not. I think this can happen in cases where a pallet has a defined `Call` part, but for whatever reason `construct_runtime` chose not to import said pallet's Call part, which would result in `variant_patterns` not being an exhaustive list.

Comment (shawntabrizi) [reply frame/support/procedural/src/construct_runtime/expand/call.rs:133]: That makes sense

**Review by shawntabrizi — APPROVED** [review]

**Comment by KiChjang** [comment]
Ok, CI keeps choking on the `tests/pallet_ui/storage_info_unsatisfied_nmap.rs` test. Tried changing the test expectations for that file, but then the output matches the unchanged UI expectation. This is a real Heisenbug.

**Comment by TriplEight** [comment]
I see
```
test storage_info_unsatisfied_nmap.rs [should fail to compile] ... error
Expected test case to fail to compile, but it succeeded.
```

in the logs of the latest pipeline

**Comment by KiChjang** [comment]
bot merge
