### PR TITLE
Fix --import-blocks

### LINKED ISSUE #1794: --import-blocks does not work
The following happens on `master`:

```
$ cargo run --release -- export-blocks --to 1000 > 1k-blocks.bin

$ cargo run --release -- import-blocks 1k-blocks.bin
2019-02-14 10:32:53 Importing 1000 blocks
2019-02-14 10:32:53 Error reading block data at 0.
2019-02-14 10:32:53 Imported 0 blocks. Best: #1896
```
I always run into `Error reading block data at 0.`. It also doesn't change anything if I export as JSON. Piping the file into the process makes no difference either.

Also tried `cargo clean`, a `cargo run --release -- purge-chain` between export/import, etc.. The database also contains enough blocks.

The import always fails at a `None` returned here: https://github.com/paritytech/substrate/blob/master/core/service/src/chain_ops.rs#L127.

### PR DESCRIPTION
**Pull request by cmichi**
Closes #1794.

### CODE REVIEW

File: core/service/src/chain_ops.rs [hunk 1]
```diff
@@ -103,13 +118,18 @@ pub fn import_blocks<F, E, R>(
...
 	// FIXME #1134 this shouldn't need a mutable config.
 	let queue = components::FullComponents::<F>::build_import_queue(&mut config, client.clone())?;
-	queue.start(DummyLink)?;
+
+	let (wait_send, wait_recv) = std::sync::mpsc::channel();
+	impl<B: Block> Link<B> for WaitLink {
+		fn block_imported(&self, _hash: &B::Hash, _number: NumberFor<B>) {
+			self.wait_send.send(()).expect("Unable to notify about imported block");
+		}
+	}
```
Comment (pepyakin) [inline core/service/src/chain_ops.rs]: pedantic, but I don't see any reason for this impl being placed here rather than next to the definition. 

Or you can move the definition here. I think in this case you can omit `new` since it would be rather verbose.

File: core/service/src/chain_ops.rs [hunk 2]
```diff
@@ -103,13 +118,18 @@ pub fn import_blocks<F, E, R>(
...
-
 	let client = new_client::<F>(&config)?;
 	// FIXME #1134 this shouldn't need a mutable config.
 	let queue = components::FullComponents::<F>::build_import_queue(&mut config, client.clone())?;
-	queue.start(DummyLink)?;
+
+	let (wait_send, wait_recv) = std::sync::mpsc::channel();
+	impl<B: Block> Link<B> for WaitLink {
+		fn block_imported(&self, _hash: &B::Hash, _number: NumberFor<B>) {
+			self.wait_send.send(()).expect("Unable to notify about imported block");
```
Comment (pepyakin) [inline core/service/src/chain_ops.rs]: Can you provide a proof why this expect won't fail?

File: core/service/src/chain_ops.rs [hunk 3]
```diff
@@ -155,6 +175,13 @@ pub fn import_blocks<F, E, R>(
 			info!("#{}", b);
 		}
 	}
+
+	let mut blocks_imported = 0;
+	while blocks_imported < count {
+		wait_recv.recv().expect("Unable to receive info about imported block");
```
Comment (pepyakin) [inline core/service/src/chain_ops.rs]: re expect: ditto

File: core/service/src/chain_ops.rs [hunk 4]
```diff
@@ -66,7 +66,10 @@ pub fn export_blocks<F, E, W>(
 	});
 	info!("Exporting blocks from #{} to #{}", block, last);
 	if !json {
-		output.write(&(last - block + As::sa(1)).encode())?;
+		let last_: u64 = last.as_();
+		let block_: u64 = block.as_();
+		let len: u32 = (last_ - block_) as u32 + 1;
+		output.write(&(len).encode())?;
```
Comment (pepyakin) [inline core/service/src/chain_ops.rs]: I wonder if these parens are needed here?

File: core/service/src/chain_ops.rs [hunk 5]
```diff
@@ -155,6 +175,13 @@ pub fn import_blocks<F, E, R>(
 			info!("#{}", b);
 		}
 	}
+
+	let mut blocks_imported = 0;
+	while blocks_imported < count {
+		wait_recv.recv().expect("Unable to receive info about imported block");
+		blocks_imported += 1;
+	}
```
Comment (pepyakin) [inline core/service/src/chain_ops.rs]: As an idea: you could create a `WaitLink` and then count imported blocks there and send a signal only when all blocks were imported.

Not blocking on this though.

File: core/service/src/chain_ops.rs (hunk 2 above)
Comment (cmichi) [reply core/service/src/chain_ops.rs]: Hmm hmm, this would panic if the receiving side in the main thread is no longer there ‒ but then the process, incl. the thread where this `send` is invoked, would be dead either way. Does this sound like an acceptable proof to you?

So basically it can't happen because when the receiver in the main thread is no longer there then this thread would also be dead.

File: core/service/src/chain_ops.rs (hunk 5 above)
Comment (cmichi) [reply core/service/src/chain_ops.rs]: Good idea, the `block_imported` function of the `Link` trait doesn't take a mutable `self` though. So I think this would require a more extensive refactoring.

**Comment by cmichi** [comment]
> is there a possibility to overload the import queue? What would happen then?

In the main thread all incoming blocks are one by one added to a the queue, on the heap. A separate thread then processes them as fast as possible. There is no rate limiting in place (or at least I couldn't find one). The importer doesn't use any fixed bucket sizes or anything like that, if you were thinking about something like that. I guess depending on memory constraints it could happen that a huge number of blocks is loaded in memory and then only slowly consumed by the importer thread.

**Comment by rphmeier** [comment]
@cmichi that is indeed possible and what the parity-ethereum implementation does is to rate-limit loading from the file based on backpressure from the queue. we should do the same.

**Comment by bkchr** [comment]
@rphmeier do you want to create an issue for this? :D Backpressure should be easily implementable with futures.

**Comment by cmichi** [comment]
I have just created a follow-up with two more shortcomings that I had in mind: https://github.com/paritytech/substrate/issues/1860.

**Comment by WB-Expert5007** [comment]
Everyone. Please help me.

When I run my substrate node server by running this command "./target/release/node-template --dev --ws-external --rpc-external", server works well and start generating blocks first. But after few hours, my server is been stopped and also stopped generating blocks automatically. How can I solve this problem? Here is Terminal Error.
Error
Best Regards.
