### PR TITLE
sync: Fixed clearing subsequent ranges

### LINKED ISSUE #11812: `sync_to_tip_when_we_sync_together_with_multiple_peers` hangs test-linux-stable
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

As noted by https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/1668403#L3170, which timed out after 2h, and the ongoing https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/1668967#L3178 which is headed in the same direction, one of the tests is taking an unreasonable amount of time and that causes the job to fail.

` SLOW [>6720.000s]                                                                         sc-network-test sync::sync_to_tip_when_we_sync_together_with_multiple_peers`

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by arkpar**
Fixes another issue introduced in #11094
`queued_blocks` records ranges using `from`, which can be arbitrary. Sync calls this function with `from` set to current best block to make sure no blocks will be returned if there's a gap in the downloaded ranges. The correct way to record a returned range here is using `start` rather than `from`.  Furthermore, all ranges need to be recorded and not just the first one.

Fixes #11812

### CODE REVIEW

File: client/network/sync/src/blocks.rs [hunk 1]
```diff
@@ -399,4 +397,34 @@ mod test {
...
+
+		// Request 2 ranges
+		assert_eq!(bc.needed_blocks(peer.clone(), 5, 50, 39, 0, 200), Some(40..45));
+		assert_eq!(bc.needed_blocks(peer.clone(), 5, 50, 39, 0, 200), Some(45..50));
+
+		// got a response on the request for `40..50`
+		bc.clear_peer_download(&peer);
+		bc.insert(40, blocks.to_vec(), peer.clone());
+
+		let ready = bc.ready_blocks(1000);
```
Comment (cheme) [inline client/network/sync/src/blocks.rs:417]: Maybe a comment indicating why we use 1000 rather than 41.

**Review by cheme — APPROVED** [review]
change make sense. Even if I find the name `from` for ready_block function is a bit confusing.

File: client/network/sync/src/blocks.rs [hunk 2]
```diff
@@ -193,6 +193,10 @@ impl<B: BlockT> BlockCollection<B> {
 					let len = (blocks.len() as u32).into();
 					prev = start + len;
 					// Remove all elements from `blocks` and add them to `ready`
+					if let Some(BlockData { block, .. }) = blocks.first() {
+						self.queued_blocks
+							.insert(block.hash, (start, start + (blocks.len() as u32).into()));
```
Comment (bkchr) [inline client/network/sync/src/blocks.rs:198]: IMHO this should be documented. The "problem" is now that `clear_queued` should be called for every hash of `ready`. We already do this, but someone could forget this in the future.

**Review by bkchr — APPROVED** [review]

**Comment by arkpar** [comment]
bot merge
