### PR TITLE
Fix #1825

### LINKED ISSUE #1825: Infinite loop in libp2p connection routine
With latest version of substrate I've get 100% usage of one CPU core.

Debug log:
```
2019-02-19 15:06:26.310 tokio-runtime-worker-0 DEBUG libp2p_tcp  Instantly refusing dialing /ip4/0.0.0.0/tcp/30333, as it is invalid   
2019-02-19 15:06:26.311 tokio-runtime-worker-0 DEBUG sub-libp2p  Failed to reach peer PeerId(Qmc12kXP66ABUK9C3N5Kq4TV826x9kdc7kLTwpoeS7Fjid) through /ip4/0.0.0.0/tcp/30333 => Transport(Other(Custom { kind: Other, error: Other(A(Transport(Underlying(B(Kind(ConnectionRefuse
d)))))) }))                                                                                                                            
2019-02-19 15:06:26.312 tokio-runtime-worker-0 DEBUG libp2p_tcp  Instantly refusing dialing /ip4/0.0.0.0/tcp/30333, as it is invalid   
2019-02-19 15:06:26.312 tokio-runtime-worker-0 DEBUG sub-libp2p  Failed to reach peer PeerId(Qmc12kXP66ABUK9C3N5Kq4TV826x9kdc7kLTwpoeS7Fjid) through /ip4/0.0.0.0/tcp/30333 => Transport(Other(Custom { kind: Other, error: Other(A(Transport(Underlying(B(Kind(ConnectionRefuse
d)))))) }))                                                                                                                            
2019-02-19 15:06:26.314 tokio-runtime-worker-0 DEBUG libp2p_tcp  Instantly refusing dialing /ip4/0.0.0.0/tcp/30333, as it is invalid   
2019-02-19 15:06:26.314 tokio-runtime-worker-0 DEBUG sub-libp2p  Failed to reach peer PeerId(Qmc12kXP66ABUK9C3N5Kq4TV826x9kdc7kLTwpoeS7Fjid) through /ip4/0.0.0.0/tcp/30333 => Transport(Other(Custom { kind: Other, error: Other(A(Transport(Underlying(B(Kind(ConnectionRefuse
d)))))) }))                                                                                                                            
2019-02-19 15:06:26.316 tokio-runtime-worker-0 DEBUG libp2p_tcp  Instantly refusing dialing /ip4/0.0.0.0/tcp/30333, as it is invalid   
2019-02-19 15:06:26.316 tokio-runtime-worker-0 DEBUG sub-libp2p  Failed to reach peer PeerId(Qmc12kXP66ABUK9C3N5Kq4TV826x9kdc7kLTwpoeS7Fjid) through /ip4/0.0.0.0/tcp/30333 => Transport(Other(Custom { kind: Other, error: Other(A(Transport(Underlying(B(Kind(ConnectionRefuse
d)))))) }))                                                                                                                            
2019-02-19 15:06:26.318 tokio-runtime-worker-0 DEBUG libp2p_tcp  Instantly refusing dialing /ip4/0.0.0.0/tcp/30333, as it is invalid   
2019-02-19 15:06:26.318 tokio-runtime-worker-0 DEBUG sub-libp2p  Failed to reach peer PeerId(Qmc12kXP66ABUK9C3N5Kq4TV826x9kdc7kLTwpoeS7Fjid) through /ip4/0.0.0.0/tcp/30333 => Transport(Other(Custom { kind: Other, error: Other(A(Transport(Underlying(B(Kind(ConnectionRefuse
d)))))) }))                                                                                                                            
2019-02-19 15:06:26.320 tokio-runtime-worker-0 DEBUG libp2p_tcp  Instantly refusing dialing /ip4/0.0.0.0/tcp/30333, as it is invalid   
2019-02-19 15:06:26.320 tokio-runtime-worker-0 DEBUG sub-libp2p  Failed to reach peer PeerId(Qmc12kXP66ABUK9C3N5Kq4TV826x9kdc7kLTwpoeS7Fjid) through /ip4/0.0.0.0/tcp/30333 => Transport(Other(Custom { kind: Other, error: Other(A(Transport(Underlying(B(Kind(ConnectionRefuse
d)))))) }))  
```

### PR DESCRIPTION
**Pull request by tomaka**
I'm not sure why this `if self.connected_peers.contains(peer_id)` is there.
We want to decrease the reputation and add a fail back for the address we failed to reach even when we're not connected to the peer that's expected to be there.

### CODE REVIEW

File: core/network-libp2p/src/custom_proto/behaviour.rs [hunk 1]
```diff
@@ -499,12 +499,14 @@ where
 	fn inject_dial_failure(&mut self, peer_id: Option<&PeerId>, addr: &Multiaddr, error: &dyn error::Error) {
 		if let Some(peer_id) = peer_id.as_ref() {
 			debug!(target: "sub-libp2p", "Failed to reach peer {:?} through {} => {:?}", peer_id, addr, error);
-			if self.connected_peers.contains(peer_id) {
-				self.topology.set_unreachable(addr);
-			}
+			self.topology.set_unreachable(addr);
 
 			// Trigger a `connect_to_nodes` round.
 			self.next_connect_to_nodes = Delay::new(Instant::now());
```
Comment (arkpar) [inline core/network-libp2p/src/custom_proto/behaviour.rs]: Why is it not triggered in the `else` case?

Comment (arkpar) [inline core/network-libp2p/src/custom_proto/behaviour.rs]: Why is not triggered in the `else` case?

Comment (tomaka) [reply core/network-libp2p/src/custom_proto/behaviour.rs]: The `else` only happens if we dial an address without knowing the `PeerId` that we expect to found, which only happens in one specific case: if the user passes a bootstrap node with the format `IP:PORT`.

Comment (gavofyork) [reply core/network-libp2p/src/custom_proto/behaviour.rs]: If it's a non-obvious implication of a logical assertion, then perhaps a comment would serve to inform future generations of maintainers? :-)
