### PR TITLE
Use default in-memory keystore for commands that don't use keystore

### LINKED ISSUE #4623: (some) node subcommands are broken
...and they fail with `keystore` not being configured. Namely `import-blocks` and `factory` at least.

Also it would be nice to actually write some tests for the sub-commands so that we don't run into that issue in the future.

### PR DESCRIPTION
**Pull request by NikVolf**
Probably as a workaround until better refactoring

Fixes #4623

### CODE REVIEW

File: client/cli/src/lib.rs [hunk 1]
```diff
@@ -749,6 +754,16 @@ fn input_keystore_password() -> Result<String, String> {
 		.map_err(|e| format!("{:?}", e))
 }
 
+/// Use in memory keystore config when it is not required at all.
+fn fill_config_keystore_in_memory<C, G, E>(config: &mut sc_service::Configuration<C, G, E>)
+	-> Result<(), String>
+{
+	match &mut config.keystore {
+		cfg @ KeystoreConfig::None => { *cfg = KeystoreConfig::InMemory; Ok(()) },
+		_ => Err(format!("Keystore config specified when it should not be!")),
```
Comment (bkchr) [inline client/cli/src/lib.rs]:
```suggestion
		_ => Err("Keystore config specified when it should not be!".into()),
```
