### PR TITLE
Remove limitation to 256 transactions, don't construct a vector.

### LINKED ISSUE #2308: Limit of number of transactions in a block
As per my tests, it seems like the default limit is only 257 transactions/limit. 
I tested it using the below script
```
// Required imports
// @ts-check
const { ApiPromise, WsProvider } = require('@polkadot/api');
const { Keyring } = require('@polkadot/keyring');
const BN = require('bn.js');

const BOB = '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty';

async function main () {
  const provider = new WsProvider('ws://127.0.0.1:9944');
  const api = await ApiPromise.create(provider);
  const keyring = new Keyring();
  const test5 = keyring.addFromMnemonic('enhance embody priority wise tree pig trash reform drum sure zebra canoe', {"name": "test4"}, "sr25519");
  let rawNonce = await api.query.system.accountNonce(keyring.getPairs()[0].address());
  let nonce = new BN(rawNonce.toString());
  for (let i = 0; i < 260; i++) {
    const transfer = api.tx.balances.transfer(BOB, 100000);
    transfer.signAndSend(test5, { nonce });
    nonce = nonce.add(new BN(1));
  }
  const transfer = api.tx.balances.transfer(BOB, 100000);
  await transfer.signAndSend(test5, { nonce });
  console.timeEnd('test');
 // 4 tx will fail bcz one block can only have 257 tx.
}

main().catch(console.error).then(() => process.exit());
```

This seems like a bug somewhere. 256 would have been a natural limit but 257 is just weird.
Error shown by the script is
```
RPC-CORE: submitExtrinsic (extrinsic: Extrinsic): Hash:: 1011: Unknown Transaction Validity (2)
ExtError: submitExtrinsic (extrinsic: Extrinsic): Hash:: 1011: Unknown Transaction Validity (2)
```
Error in node logs is
```
Extrinsic invalid: 0x1957c4f88ebd8b21ba0a95289062b390c6e8b2e199fad532530c25e7f110f417
```

### PR DESCRIPTION
**Pull request by tomusdrw**
For account based systems it's fine if we only require one previous transaction, the rest (everything else between `expected_nonce .. index - 1` is required transitvely)

This allows us to remove the limitation of max 257 queued transactions, cause the vector is now always bounded.

Fixes #2308

### CODE REVIEW

File: srml/executive/src/lib.rs [hunk 1]
```diff
@@ -311,24 +311,23 @@ impl<
...
-			}
 
-			let mut deps = Vec::new();
-			while expected_index < *index {
-				deps.push((sender, expected_index).encode());
-				expected_index = expected_index + One::one();
-			}
+			let index = *index;
+			let provides = vec![(sender, index).encode()];
+			let requires = if expected_index < index {
```
Comment (DemiMarie-parity) [inline srml/executive/src/lib.rs]: This vector should really be an `Option`, since it now has only 0 or 1 element.

**Comment by DemiMarie-parity** [comment]
CI is complaining that `impl_version` has not been bumped.

**Comment by bkchr** [comment]
As @DemiMarie-parity mentioned, you should update the `impl_version`.

File: srml/executive/src/lib.rs (hunk 1 above)
Comment (tomusdrw) [reply srml/executive/src/lib.rs]: We can't change it to `Option` - `TransactionValidity` is a generic type that might be used by many different runtimes, some of them might need multiple `required` tags (UTXO for instance).
