### PR TITLE
Fixed panic handling

### LINKED ISSUE #1470: Panic should abort
Right now unhandled panic only aborts execution when thrown in the main thread. Panics thrown from any other thread only kill that thread leaving the program running in invalid state. 
Any unhandled panic from any thread should kill the process as well.

### PR DESCRIPTION
**Pull request by arkpar**
Closes #1470

### CODE REVIEW

File: core/panic-handler/src/lib.rs [hunk 1]
```diff
@@ -19,20 +19,51 @@
...
+	() => ("
 This is a bug. Please report it at:
 
-    https://github.com/paritytech/polkadot/issues/new
-";
+	{}
+")}
+
+/// Set aborting flag. Returns previous value of the flag.
+pub fn set_abort(enabled: bool) -> bool {
```
Comment (bkchr) [inline core/panic-handler/src/lib.rs]: I think this function should not be public?

File: core/state-machine/src/ext.rs [hunk 2]
```diff
@@ -181,35 +181,41 @@ where
 	H::Out: Ord + HeapSizeOf,
 {
 	fn storage(&self, key: &[u8]) -> Option<Vec<u8>> {
+		let _guard = panic_handler::AbortGuard::new(true);
```
Comment (bkchr) [inline core/state-machine/src/ext.rs]: Why do we need to abort here?

File: core/panic-handler/src/lib.rs (hunk 1 above)
Comment (rphmeier) [reply core/panic-handler/src/lib.rs]: panics in the runtime should not abort, but panics in client code, including exernalities, should.

Comment (arkpar) [reply core/panic-handler/src/lib.rs]: @bkchr I'd leave it public in case someone needs to set and forget. The crate API aims to be universal.

File: core/state-machine/src/ext.rs (hunk 2 above)
Comment (arkpar) [reply core/state-machine/src/ext.rs]: As @rphmeier answered in the wrong comment, client code panic should not lead to runtime error and potential consensus issues. Also panic behaviour between native and wasm runtimes needs to be consistent.

Comment (bkchr) [reply core/state-machine/src/ext.rs]: Okay. :)
