### PR TITLE
Move the legacy protocol handshake to the legacy substream

### LINKED ISSUE #2010: Make the Status networking message the handshake message
cc #1692 

Will write better description, or ping me if I forget.

### LINKED ISSUE #5592: Called on_block_announce with a bad PeerId
I'm trying to debug this error log being printed at the moment.

For example, here is a selection of logs concerning a faulty peer:

> 2020-04-09 05:28:04.113 main-tokio- DEBUG sub-libp2p  Libp2p => Connection (ConnectionId(TaskId(48824)),Listener { local_addr: "/ip4/10.128.0.9/tcp/30333", send_back_addr: "/ip4/35.198.126.58/tcp/46740" }) to Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8 closed.
> 2020-04-09 05:28:04.113 main-tokio- DEBUG sub-libp2p  Libp2p => Disconnected(Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8): Was disabled.
> 2020-04-09 05:29:16.519 main-tokio- DEBUG sub-libp2p  Libp2p => Connection (ConnectionId(TaskId(48992)),Listener { local_addr: "/ip4/10.128.0.9/tcp/30333", send_back_addr: "/ip4/35.198.126.58/tcp/47480" }) to Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8 established.
> 2020-04-09 05:29:16.520 main-tokio- DEBUG sub-libp2p  Libp2p => Connected(Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8, Listener { local_addr: "/ip4/10.128.0.9/tcp/30333", send_back_addr: "/ip4/35.198.126.58/tcp/47480" }): Incoming connection
> 2020-04-09 05:29:16.520 main-tokio- DEBUG sub-libp2p  PSM <= Incoming(Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8, IncomingIndex(24268)).
> 2020-04-09 05:29:16.520 main-tokio- DEBUG sub-libp2p  PSM => Accept(IncomingIndex(24268), PeerId("Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8")): Enabling connections.
> 2020-04-09 05:29:16.520 main-tokio- DEBUG sub-libp2p  Handler(PeerId("Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8")) <= Enable
> 2020-04-09 05:29:17.146 main-tokio- DEBUG sub-libp2p  Handler(PeerId("Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8")) => Endpoint Listener { local_addr: "/ip4/10.128.0.9/tcp/30333", send_back_addr: "/ip4/35.198.126.58/tcp/47480" } open for custom protocols.
> 2020-04-09 05:29:17.146 main-tokio- DEBUG sub-libp2p  External API <= Open(PeerId("Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8"))
> 2020-04-09 05:29:17.146 main-tokio- TRACE sync  Connecting Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8
> 2020-04-09 05:29:17.146 main-tokio- TRACE sync  New peer Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8 Status { version: 6, min_supported_version: 3, roles: AUTHORITY, best_number: 1807687, best_hash: 0x0b5673dee66fa81b6c6d81bc9259865deda933b4c11d297e252bb160bf07c1c5, genesis_hash: 0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe, chain_status: [] }
> 2020-04-09 05:29:17.146 main-tokio- DEBUG sync  Connected Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8
> 2020-04-09 06:03:42.423 main-tokio- DEBUG sub-libp2p  Libp2p => Connection (ConnectionId(TaskId(51883)),Listener { local_addr: "/ip4/10.128.0.9/tcp/30333", send_back_addr: "/ip4/35.198.126.58/tcp/49894" }) to Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8 established.
> 2020-04-09 06:03:42.423 main-tokio- DEBUG sub-libp2p  Handler(Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8,ConnectionId(TaskId(51883))) <= Enable secondary connection
> 2020-04-09 06:03:42.677 main-tokio- DEBUG sub-libp2p  Libp2p => Connection (ConnectionId(TaskId(51883)),Listener { local_addr: "/ip4/10.128.0.9/tcp/30333", send_back_addr: "/ip4/35.198.126.58/tcp/49894" }) to Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8 closed.
> 2020-04-09 06:03:42.678 main-tokio- DEBUG sub-libp2p  External API <= Closed(Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8)
> 2020-04-09 06:03:42.678 main-tokio- TRACE sync  Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8 disconnected
> 2020-04-09 06:03:49.304 main-tokio- DEBUG sync  Received block announcement 0x3e521bdd4f3b6bdb16e3c545b0bd7acb79a4686e8acf0d5305c301f8f7038462 with number 1808030 from Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8
> 2020-04-09 06:03:49.305 main-tokio- ERROR sync  💔 Called on_block_announce with a bad peer ID

(I made the effort to find all the entries that are possibly relevant to this peer, but the logs are huge and it's not impossible that I have missed some)
(also, feel free to copy-paste these logs for better readability)

It seems to me that:

- A first connection to `Qmar25qYxcoLzPuzHDZ9nM7o38mNPqnKrZaksf3aY8rdM8` is established with task ID 48992.
- The PSM approves it.
- We report to the external API that the substream has been opened.
- A second connection with task ID 51883 gets established to the same peer.
- That second connection (task ID 51883) gets closed shortly after (200ms)
- We report to the external API that the substream has been closed.

The last step seems wrong to me, as the first connection should still be alive. I didn't find anything in the logs about task ID 48992 other than what is above.

cc @romanb is that related to https://github.com/libp2p/rust-libp2p/pull/1546?

### PR DESCRIPTION
**Pull request by tomaka**
Fix #2010 
Fix #5592 

Before this PR: the per-node tasks opens a substream, then report to the code in `protocol.rs` that a substream is open. According to the per-node task, the substream is fully open but according to `protocol.rs` it is still in "handshaking mode". `protocol.rs` sends a status message, and it is only when a status is received back that it considers the connection fully open.

In order to continue working on #5670, the fact that a connection can be either in "handshaking mode" or "fully open" complicates quite a lot of things. For example, what if a peer opens a notifications substream first, and then only a legacy substream?

This PR moves the Status messages exchange to the per-node tasks. The per-node tasks report that the substream is open only after we have received a Status message back.

In details:

- Removes the `handshaking_peers` field and metrics from `protocol.rs`. As explained, the `protocol.rs` isn't aware of handshaking peers anymore.
- The `on_status_message` has been renamed to `on_peer_connected`.
- The status message is now passed to the per-node tasks. Every time the import queue tells us that we have imported a block, we update that status message.
- The `InboundUpgrade` and `OutboundUpgrade` trait implementations now returns the handshake as part of their output.
- The test that I removed was checking that we don't emit notifications for handshaking nodes. Bu design, this can't happen anymore.

While this is ready for reviewing, I'd like to let it tun on my node as long as possible to detect potential weirdnesses.

### CODE REVIEW

**Comment by tomaka** [comment]
Update: investigating why the tests are failing. It seems non trivial.

**Comment by tomaka** [comment]
The sync integration test is failing because the test infrastructure doesn't call `on_block_imported` after importing blocking, despite what the API surface of `sc_network` documents.

**Comment by tomaka** [comment]
I have no idea how to fix that without introducing hacks in `sc_network::Service` that expose some internals

**Comment by arkpar** [comment]
> The sync integration test is failing because the test infrastructure doesn't call `on_block_imported` after importing blocks, despite what the API surface of `sc_network` documents.

It is supposed to be called here: https://github.com/paritytech/substrate/blob/a2512e837003db3d3267764283edf31cf95a206c/client/network/test/src/lib.rs#L813

**Comment by tomaka** [comment]
The code used in the integration test is this one however:
https://github.com/paritytech/substrate/blob/master/client/service/test/src/lib.rs

It's very redundant with the one on `sc_network/test`

**Comment by tomaka** [comment]
Putting on ice again. I'd like to upgrade to libp2p v0.19 soon. Both this PR and the PR that will upgrade to libp2p 0.19 should be extensively tested, and the libp2p upgrade would take the priority here.

**Comment by tomaka** [comment]
I've reworked this PR a bit in lights of channelgate (#6080)

When `set_notifications_handshake` or `set_legacy_handshake` is called, we instead just modify the content of an `Arc<RwLock<>>` from the network worker. This `Arc` is then read by the node tasks.

**Comment by tomaka** [comment]
Now based on top of https://github.com/paritytech/substrate/pull/6232

**Comment by tomaka** [comment]
Tests should now pass but please don't merge. This PR changes the behaviour in case we have multiple connections, and I need to figure out whether it still works well enough.

File: client/network/src/protocol.rs [hunk 1]
```diff
@@ -349,6 +335,22 @@ impl<B: BlockT> BlockAnnouncesHandshake<B> {
 	}
 }
 
+/// Builds a SCALE-encoded "Status" message to send as handshake for the legacy protocol.
+fn build_status_message<B: BlockT>(protocol_config: &ProtocolConfig, chain: &Arc<dyn Client<B>>) -> Vec<u8> {
```
Comment (mxinden) [inline client/network/src/protocol.rs:339]: Do I understand correctly that this function is called for each block that is imported even though we probably shake less than one hand per ~6 seconds? 

This decouples `protocol/generic_proto/behaviour.rs` from any upper layer logic, thus in case performance is irrelevant I prefer this push-approach over a pull-approach where the lower layer requests a new handshake message.

Comment (tomaka) [reply client/network/src/protocol.rs:339]: > even though we probably shake less than one hand per ~6 seconds?

We do around two handshakes per second at the moment.

File: client/network/src/protocol/generic_proto/handler/group.rs [hunk 2]
```diff
@@ -346,12 +338,17 @@ impl ProtocolsHandler for NotifsHandler {
 				self.enabled = EnabledState::Enabled;
 				self.legacy.inject_event(LegacyProtoHandlerIn::Enable);
 				for (handler, initial_message) in &mut self.out_handlers {
+					// We create `initial_message` on a separate line to be sure that the lock
```
[the remark this answers is not in the document]
Comment (tomaka) [reply client/network/src/protocol/generic_proto/handler/group.rs:341]: I think that if you do `inject_event(message.read().clone())` (where `message.read()` locks the `RwLock`), then the lock stays alive until `inject_event` returns.

File: client/network/src/protocol.rs (hunk 1 above)
Comment (tomaka) [reply client/network/src/protocol.rs:339]: > I prefer this push-approach over a pull-approach where the lower layer requests a new handshake message

The problem with this "push approach" which consists in holding a copy of the handshake message on each background task is that we have to send one message to each background task, which causes all the background tasks to wake up, and clogs a bit more the channel between the worker and tasks.

File: client/network/src/protocol/generic_proto/handler/group.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (mxinden) [reply client/network/src/protocol/generic_proto/handler/group.rs:341]: Yes, you are right, my mistake. Function parameters [are dropped at the end of the function scope](https://github.com/rust-lang/reference/blob/master/src/destructors.md#scopes-of-function-parameters) thus delaying unlocking of the Mutex.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=33babb07c7718cf51c7ef811f1022003

Wasn't aware of this, thanks for the pointer @tomaka and @spacejam.

**Comment by tomaka** [comment]
> This PR changes the behaviour in case we have multiple connections, and I need to figure out whether it still works well enough.

Coming back to this.
The problem arises if a second connection with the same peer is open.
Before, we open the legacy substream on that second connection too, but don't send or expect any `Status` message.
After this PR, however, if a substream is open on the second connection, it will then send a `Status` message, which will get us banned by the remote.

I'm going to tweak the PR so that the network worker indicates to the connection whether it is "primary" or not.

**Comment by mxinden** [comment]
Rephrasing the above to ensure that I understand the problem at hand correctly. Would you ind giving this a look @tomaka?

The previous `Protocol::on_status_message` expects to receive at most one status message from each remote peer. In particular the code below would log an error and decrease a peers reputation.

```rust
// This would evaluate to true as the peer is already connected.
if self.context_data.peers.contains_key(&who) {
	log!(
		target: "sync",
		if self.important_peers.contains(&who) { Level::Warn } else { Level::Debug },
		"Unexpected status packet from {}", who
	);
	self.peerset_handle.report_peer(who, rep::UNEXPECTED_STATUS);
	return CustomMessageOutcome::None;
}
```

Given that `rep::UNEXPECTED_STATUS` is high (`-(1 << 20)`) the peer will get banned.

### Possible ways forward

#### Don't send handshake on non-primary connections

Each time the new logic sends a `NotifsHandlerIn::Enable` within `generic_proto/behaviour.rs` it checks `GenericProto.peers`. If the entry for the peer is `Enabled` and `open.len() > 0` the about-to-be-enabled connection is not primary. A not-primary connection should not do a handshake. Instead of sending a `NotifsHandlerIn::Enable` it would send a `NotifsHandlerIn::Enable(NotPrimary)` down to the `NotifsHandler` which would then skip `send_handshake` in `NotifsInHandler` and `NotifsOutHandler`.


#### Decrease reputation change

Release a version with a lower reputation change on unexpected status receive and only after a grace period release the logic in this pull request.

**Comment by tomaka** [comment]
Your analysis is mostly correct.
The other problem is that after this PR we will wait for a `Status` handshake to arrive on non-primary connections, but older nodes won't send any.

**Comment by mxinden** [comment]
@tomaka as far as I can tell https://github.com/paritytech/substrate/pull/5938/commits/2b892e6a7637c0b1297e6ecdbb919321c9098ff5 is not needed anymore now that https://github.com/paritytech/substrate/pull/6377 is merged.

Would you mind reverting it?

**Comment by tomaka** [comment]
> @tomaka as far as I can tell 2b892e6 is not needed anymore now that #6377 is merged.

Yes sorry, that commit wasn't supposed to be pushed in the first place.

**Comment by mxinden** [comment]
@tomaka what do you think of including https://github.com/tomaka/polkadot/pull/4 in this pull request?

**Comment by tomaka** [comment]
I don't really understand how https://github.com/tomaka/polkadot/pull/4 is related to this PR

**Comment by tomaka** [comment]
I think that this PR is ready as it is, but we should first wait for #6377 to be sufficiently deployed, then test this PR.

**Comment by mxinden** [comment]
Not directly related. We can also merge it (if we reach consensus on merging it in the first place) once this pull request is merged.

It might help judging whether this patch is safe to roll out to all nodes even though not all of them run with https://github.com/paritytech/substrate/pull/6377 yet.

**Comment by tomaka** [comment]
This PR is unfortunately missing the fact that the first message that we receive on a legacy substream might not be the `Status` message.

We might have to add another step and first release a version where we send the Status message unconditionally, *then* only merge this one.

**Comment by mxinden** [comment]
> We might have to add another step and first release a version where we send the Status message unconditionally, then only merge this one.

@tomaka are you suggesting to emit a `GenericProtoOut::CustomProtocolOpen` within `protocol/generic_proto/behaviour` detached from whether it is the first or non-first connection and thus have `<Protocol as NetworkBehaviour>::poll` call `on_peer_connected` in either case and thus have `on_peer_connected` call `send_status` in either case?

Something along the lines of:

```diff
diff --git a/client/network/src/protocol/generic_proto/behaviour.rs b/client/network/src/protocol/generic_proto/behaviour.rs
index be2451c3f..5ba882833 100644
--- a/client/network/src/protocol/generic_proto/behaviour.rs
+++ b/client/network/src/protocol/generic_proto/behaviour.rs
@@ -1293,11 +1293,12 @@ impl NetworkBehaviour for GenericProto {
 
                                if first {
                                        debug!(target: "sub-libp2p", "External API <= Open({:?})", source);
-                                       let event = GenericProtoOut::CustomProtocolOpen { peer_id: source };
-                                       self.events.push_back(NetworkBehaviourAction::GenerateEvent(event));
                                } else {
                                        debug!(target: "sub-libp2p", "Secondary connection opened custom protocol.");
                                }
+
+                               let event = GenericProtoOut::CustomProtocolOpen { peer_id: source };
+                               self.events.push_back(NetworkBehaviourAction::GenerateEvent(event));
                        }
 
                        NotifsHandlerOut::CustomMessage { message } => {
```

**Comment by tomaka** [comment]
@mxinden Indeed

However I have now fixed that, and we won't need a separate round.

When a secondary connection is open, we report the handshake to the upper layers as if it was a regular message.

File: client/network/src/protocol/generic_proto/behaviour.rs [hunk 3]
```diff
@@ -1280,8 +1280,32 @@ impl NetworkBehaviour for GenericProto {
...
+						target: "sub-libp2p",
+						"Handler({:?}) => Secondary connection opened custom protocol",
+						source
+					);
+					trace!(target: "sub-libp2p", "External API <= Message({:?})", source);
+					let ev = GenericProtoOut::LegacyMessage {
+						peer_id: source,
+						message: From::from(&received_handshake[..]),
+					};
+					self.events.push_back(NetworkBehaviourAction::GenerateEvent(ev));
```
Comment (mxinden) [inline client/network/src/protocol/generic_proto/behaviour.rs:1308]: Nit pick to align with above's `event` declaration.

```suggestion
					let event = GenericProtoOut::LegacyMessage {
						peer_id: source,
						message: From::from(&received_handshake[..]),
					};
					self.events.push_back(NetworkBehaviourAction::GenerateEvent(event));
```

**Comment by tomaka** [comment]
One thing to be aware of:

In case of a secondary connection opened, a node without this PR will not send any message (not even a Status message) while a node with this PR will wait for a message. After 30 seconds, the timeout will trigger and the secondary connection will close.

If this secondary connection happened to be used for notifications or Kademlia, then some notifications or requests might be lost. In other words, nodes with this PR and nodes without this PR might have some troubles communicating with each other.

For this reason, I'm bumping to medium.

**Comment by mxinden** [comment]
:stop_sign: Don't merge before https://github.com/paritytech/substrate/pull/6377 has been deployed widely :stop_sign:

**Comment by mxinden** [comment]
https://github.com/paritytech/substrate/pull/6377 as been deployed with Polkadot `v0.8.11`. [The majority of nodes on Kusama and Polkadot is running `v0.8.12`](https://telemetry.polkadot.io/#list/Polkadot%20CC1).

@tomaka what do you think of merging this pull request for `v0.8.13`?

**Comment by tomaka** [comment]
Screenshot from 2020-06-30 16-44-20

I deployed this PR on my node this morning, and here is the number of peers.
There might be something wrong, but I don't know what.

**Comment by tomaka** [comment]
Screenshot from 2020-07-01 10-43-16

It stabilized itself over night.

It's hard to tell whether things are completely ok or not.
A graph like this could totally be produced by a well-behaviour node, but it's also a bit suspicious that it took so long to stabilize again.

**Comment by tomaka** [comment]
I've just tested Polkadot 0.8.10 with this PR, and they seem to stay connected just fine.
I'm still confused as to why the number of peers is lower with this PR.

**Comment by tomaka** [comment]
I've examined the logs for a couple hours.
The main errors I see are "Timeout when opening protocol", which is the known issue with the `Status` message not being sent, and "Upgrade(Select(Failed))" from Edgeware nodes.

For all I can tell, this PR works properly.

**Comment by tomaka** [comment]
Update: Polkadot 0.8.14 should be published soon, and after enough nodes have deployed it we can see if this PR works well enough.

**Comment by tomaka** [comment]
I've been testing this on my node over night.

Screenshot from 2020-07-15 10-38-33

While we don't reach 150 peers, the number of peers is stable and number of disconnections is the same as usual. I can only assume that everything is working as expected. Notably there is no difference between this PR and #6593.

I would therefore suggest to merge this.
@mxinden Did you want to review again?

**Comment by tomaka** [comment]
bot merge
