### PR TITLE
benchmarking f32 step calculation

### LINKED ISSUE #11667: pallet benchmarking: Incorrect step-size rounding
Just writing this down so i dont forget it...

## Current Situation

Suppose you have a step size of 50 for a parameter `c` in range `[0, 999]`.  
The step size will be calculated as integer division: `⌊999 / 50⌋ = ⌊19.98⌋ = 19`.  
When the multiplied with up to 50, the final value is 950 instead of 998.  

## Fix

Calculate the step size as float and then round the result of the following multiplication.    
Then re-benchmark the pallets.

### PR DESCRIPTION
**Pull request by bernardoaraujor**
fix #11667

Step size calculation on benchmarking cli is currently innacurate. This solution sticks to the provided number of steps during the for loop, and rounding from `f32` to `u32` only happens for the calculation of each `component_value`.

### CODE REVIEW

File: utils/frame/benchmarking-cli/src/pallet/command.rs [hunk 1]
```diff
@@ -239,11 +239,11 @@ impl PalletCmd {
 					let diff = highest - lowest;
 
 					// Create up to `STEPS` steps for that component between high and low.
-					let step_size = (diff / self.steps).max(1);
-					let num_of_steps = diff / step_size + 1;
-					for s in 0..num_of_steps {
+					let step_size = (diff as f32 / (self.steps - 1) as f32).max(1.0);
```
Comment (ggwpez) [inline utils/frame/benchmarking-cli/src/pallet/command.rs:242]: Could you still please handle the edge-cases?  
Does this just panic when called with `steps <= 1`?  
In the `1` case the step size is irrelevant anyway.

Comment (bernardoaraujor) [reply utils/frame/benchmarking-cli/src/pallet/command.rs:242]: when `steps == 1` it does panic, but it's not because of a division by `0`.
doing the following did not solve the issue:
```
let step_size = if self.steps == 1 {
    1.0
} else {
    (diff as f32 / (self.steps - 1) as f32).max(1.0)
};
```

actually, it seems that the logic under [`median_slopes`](https://github.com/paritytech/substrate/blob/dbdbef95c84644328bee60bd170d79814c04e32b/frame/benchmarking/src/analysis.rs#L106) function isn't prepared to handle such edge case.

```
$ cargo run --features runtime-benchmarks -- benchmark pallet --pallet pallet_utility --extrinsic batch --steps 1 --low 0 --high 50
   Compiling frame-benchmarking-cli v4.0.0-dev (/home/bear/develop/substrate/utils/frame/benchmarking-cli)
   Compiling node-cli v3.0.0-dev (/home/bear/develop/substrate/bin/node/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 4m 17s
     Running `target/debug/substrate benchmark pallet --pallet pallet_utility --extrinsic batch --steps 1 --low 0 --high 50`
2022-07-22 17:40:03 [0] 💸 generated 1 npos voters, 1 from validators and 0 nominators    
Pallet: "pallet_utility", Extrinsic: "batch", Lowest values: [0], Highest values: [50], Steps: 1, Repeat: 1
Raw Storage Info
========

Median Slopes Analysis
========

====================

Version: 3.0.0-dev-b9a764afbf3

   0: sp_panic_handler::panic_hook
             at primitives/panic-handler/src/lib.rs:166:18
...
  19: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/b17226fcc11587fed612631be372a5b4cb89988a/library/alloc/src/vec/mod.rs:2547:9
  20: core::iter::traits::iterator::Iterator::collect
             at /rustc/b17226fcc11587fed612631be372a5b4cb89988a/library/core/src/iter/traits/iterator.rs:1778:9
  21: frame_benchmarking::analysis::Analysis::median_slopes
             at frame/benchmarking/src/analysis.rs:151:16
  22: frame_benchmarking_cli::pallet::command::<impl frame_benchmarking_cli::pallet::PalletCmd>::print_summary
             at utils/frame/benchmarking-cli/src/pallet/command.rs:460:6
  23: frame_benchmarking_cli::pallet::command::<impl frame_benchmarking_cli::pallet::PalletCmd>::run
             at utils/frame/benchmarking-cli/src/pallet/command.rs:399:4
  24: node_cli::command::run::{{closure}}
             at bin/node/cli/src/command.rs:114:7
...
```
would someone ever want to benchmark with a single step? is it worth investigating on the necessary adaptations to `median_slopes` logic?


for now I'm just adding a check that avoids `steps <= 1`.

Comment (ggwpez) [reply utils/frame/benchmarking-cli/src/pallet/command.rs:246]: Okay I see. Its because the slope logic needs at least two points to work.  
I will push a fix that should make it work together.   
A small comparison of the `sr25519_verification` benchmark which formerly overshot a lot:

```pre
...
Running Benchmark: frame_benchmarking.sr25519_verification 99/50 1/1
Running Benchmark: frame_benchmarking.sr25519_verification 100/50 1/1
```

Now its on point. This should also reduce the runtime of the benchmarks.
```pre
... 
Running Benchmark: frame_benchmarking.sr25519_verification 46/50 1/1
Running Benchmark: frame_benchmarking.sr25519_verification 48/50 1/1
```

**Comment by ggwpez** [comment]
Please have a look @bernardoaraujor. It should be fixed now.

File: utils/frame/benchmarking-cli/src/pallet/command.rs (hunk 1 above)
Comment (shawntabrizi) [reply utils/frame/benchmarking-cli/src/pallet/command.rs]: yes, reduction of benchmarks will be great!

File: utils/frame/benchmarking-cli/src/pallet/command.rs [hunk 2]
```diff
@@ -364,13 +372,15 @@ impl PalletCmd {
...
+								"Running Benchmark: {}.{}({} args) {}/{} {}/{}",
 								String::from_utf8(pallet.clone())
 									.expect("Encoded from String; qed"),
 								String::from_utf8(extrinsic.clone())
 									.expect("Encoded from String; qed"),
+								components.len(),
 								s + 1, // s starts at 0. todo show step
-								self.steps,
+								// `steps` is the number of steps *per* component.
+								all_components.len(),
```
Comment (shawntabrizi) [inline utils/frame/benchmarking-cli/src/pallet/command.rs:383]: is this TODO still needed?

Seems like it may be removed

also the comments references `steps`, but where?

File: utils/frame/benchmarking-cli/src/pallet/command.rs [hunk 3]
```diff
@@ -236,14 +236,22 @@ impl PalletCmd {
...
-					// Create up to `STEPS` steps for that component between high and low.
-					let step_size = (diff / self.steps).max(1);
-					let num_of_steps = diff / step_size + 1;
-					for s in 0..num_of_steps {
+					if self.steps < 2 {
+						return Err("`steps` must be at least 2.".into())
+					}
+
+					// The slope logic needs at least two points
+					// to compute a slope.
```
Comment (shawntabrizi) [inline utils/frame/benchmarking-cli/src/pallet/command.rs:247]: feels this comment should be above the check above

**Review by shawntabrizi — APPROVED** [review]
comments look a little out of place, logic looks nice

File: utils/frame/benchmarking-cli/src/pallet/command.rs (hunk 2 above)
Comment (shawntabrizi) [reply utils/frame/benchmarking-cli/src/pallet/command.rs:383]: i think todo can be removed

Comment (bernardoaraujor) [reply utils/frame/benchmarking-cli/src/pallet/command.rs:383]: todo seems old, I couldn't figure out the context it was added even by looking at the old commit history

as for L382, it was introduced https://github.com/bernardoaraujor/substrate/commit/c029dc6216d39905f7a3e4c88947fb511694e337 what was the rationale there @ggwpez ?

Comment (ggwpez) [reply utils/frame/benchmarking-cli/src/pallet/command.rs]: I meant `s`, not `steps` :man_facepalming:   
Will fix

**Comment by ggwpez** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_contracts

**Comment by ggwpez** [comment]
/cmd queue -c bench-bot $ pallet dev pallet_contracts

**Comment by ggwpez** [comment]
The generated weights are quite bad. But somehow this already happens on master.  
Master re-benchmarked on `bm2`:  

<details>
  <summary>Staking</summary>  

```pre
+------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------+
| File                         | Extrinsic                      | Old     | New     | Change [%] | Old Weight Term                                                                                 | New Weight Term                                                                                 | Used variables                                               |
+===================================================================================================================================================================================================================================================================================================================================================================+
| frame/staking/src/weights.rs | set_invulnerables              | 14.42M  | 17.19M  | +19.23     | 4.32M + 10.00K * v + WRITE                                                                      | 7.09M + 10.00K * v + WRITE                                                                      | READ = 25.00K, WRITE = 100.00K, v = 1.00K                    |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | get_npos_voters                | 46.89G  | 59.24G  | +26.35     | 23.75M * v + 22.50M * n + 20.68M * s + 202 * READ + 5 * v * READ + 4 * n * READ + s * READ      | 30.76M * v + 27.77M * n + 23.98M * s + 202 * READ + 5 * v * READ + 4 * n * READ + s * READ      | READ = 25.00K, WRITE = 100.00K, n = 1.00K, s = 20, v = 1.00K |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | get_npos_targets               | 8.12G   | 10.53G  | +29.60     | 8.10M * v + READ + v * READ                                                                     | 10.50M * v + READ + v * READ                                                                    | READ = 25.00K, WRITE = 100.00K, v = 1.00K                    |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | new_era                        | 5.26G   | 6.84G   | +29.91     | 213.10M * v + 31.12M * n + 208 * READ + 5 * v * READ + 4 * n * READ + 3 * WRITE + 3 * v * WRITE | 274.81M * v + 40.69M * n + 208 * READ + 5 * v * READ + 4 * n * READ + 3 * WRITE + 3 * v * WRITE | READ = 25.00K, WRITE = 100.00K, n = 100, v = 10              |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | withdraw_unbonded_update       | 41.86M  | 54.83M  | +30.96     | 35.76M + 57.00K * s + 4 * READ + 3 * WRITE                                                      | 49.02M + 54.00K * s + 4 * READ + 3 * WRITE                                                      | READ = 25.00K, WRITE = 100.00K, s = 100                      |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | nominate                       | 116.20M | 154.71M | +33.14     | 56.60M + 3.64M * n + 12 * READ + n * READ + 6 * WRITE                                           | 77.58M + 4.74M * n + 12 * READ + n * READ + 6 * WRITE                                           | READ = 25.00K, WRITE = 100.00K, n = 16                       |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | set_history_depth              | 2.35G   | 3.14G   | +33.42     | 22.83M * e + 2 * READ + 4 * WRITE + 7 * e * WRITE                                               | 30.70M * e + 2 * READ + 4 * WRITE + 7 * e * WRITE                                               | READ = 25.00K, WRITE = 100.00K, e = 100                      |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | set_controller                 | 20.20M  | 27.40M  | +35.65     | 19.83M + 3 * READ + 3 * WRITE                                                                   | 27.03M + 3 * READ + 3 * WRITE                                                                   | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | rebond                         | 77.94M  | 108.32M | +38.98     | 74.86M + 64.00K * l + 9 * READ + 8 * WRITE                                                      | 105.15M + 67.00K * l + 9 * READ + 8 * WRITE                                                     | READ = 25.00K, WRITE = 100.00K, l = 32                       |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | chill                          | 51.92M  | 72.31M  | +39.28     | 51.12M + 8 * READ + 6 * WRITE                                                                   | 71.51M + 8 * READ + 6 * WRITE                                                                   | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | kick                           | 1.06G   | 1.49G   | +39.58     | 23.26M + 8.01M * k + READ + k * READ + k * WRITE                                                | 28.90M + 11.25M * k + READ + k * READ + k * WRITE                                               | READ = 25.00K, WRITE = 100.00K, k = 128                      |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | withdraw_unbonded_kill         | 68.36M  | 95.42M  | +39.59     | 66.94M + 13 * READ + 11 * WRITE                                                                 | 94.00M + 13 * READ + 11 * WRITE                                                                 | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | chill_other                    | 62.89M  | 88.06M  | +40.02     | 62.01M + 11 * READ + 6 * WRITE                                                                  | 87.18M + 11 * READ + 6 * WRITE                                                                  | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | bond_extra                     | 76.73M  | 107.45M | +40.04     | 75.83M + 8 * READ + 7 * WRITE                                                                   | 106.55M + 8 * READ + 7 * WRITE                                                                  | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | payout_stakers_alive_staked    | 9.04G   | 12.66G  | +40.17     | 98.84M + 34.48M * n + 11 * READ + 5 * n * READ + 3 * WRITE + 3 * n * WRITE                      | 129.21M + 48.54M * n + 11 * READ + 5 * n * READ + 3 * WRITE + 3 * n * WRITE                     | READ = 25.00K, WRITE = 100.00K, n = 256                      |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | unbond                         | 82.17M  | 115.29M | +40.30     | 81.08M + 12 * READ + 8 * WRITE                                                                  | 114.19M + 12 * READ + 8 * WRITE                                                                 | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | validate                       | 53.72M  | 75.66M  | +40.85     | 52.94M + 11 * READ + 5 * WRITE                                                                  | 74.89M + 11 * READ + 5 * WRITE                                                                  | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | force_apply_min_commission     | 12.96M  | 18.27M  | +40.96     | 12.81M + 2 * READ + WRITE                                                                       | 18.12M + 2 * READ + WRITE                                                                       | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | bond                           | 44.52M  | 62.97M  | +41.44     | 43.99M + 5 * READ + 4 * WRITE                                                                   | 62.44M + 5 * READ + 4 * WRITE                                                                   | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | set_payee                      | 11.35M  | 16.06M  | +41.50     | 11.22M + READ + WRITE                                                                           | 15.93M + READ + WRITE                                                                           | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | force_unstake                  | 179.64M | 256.58M | +42.83     | 65.27M + 1.03M * s + 11 * READ + 12 * WRITE + s * WRITE                                         | 90.51M + 1.55M * s + 11 * READ + 12 * WRITE + s * WRITE                                         | READ = 25.00K, WRITE = 100.00K, s = 100                      |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | reap_stash                     | 184.53M | 265.26M | +43.75     | 70.93M + 1.02M * s + 12 * READ + 12 * WRITE + s * WRITE                                         | 99.06M + 1.55M * s + 12 * READ + 12 * WRITE + s * WRITE                                         | READ = 25.00K, WRITE = 100.00K, s = 100                      |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | payout_stakers_dead_controller | 6.34G   | 9.29G   | +46.70     | 87.57M + 24.23M * n + 10 * READ + 3 * n * READ + 2 * WRITE + n * WRITE                          | 101.07M + 35.74M * n + 10 * READ + 3 * n * READ + 2 * WRITE + n * WRITE                         | READ = 25.00K, WRITE = 100.00K, n = 256                      |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | set_staking_configs_all_remove | 7.09M   | 10.59M  | +49.22     | 6.50M + 6 * WRITE                                                                               | 9.99M + 6 * WRITE                                                                               | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | set_staking_configs_all_set    | 7.64M   | 11.50M  | +50.54     | 7.04M + 6 * WRITE                                                                               | 10.90M + 6 * WRITE                                                                              | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | set_validator_count            | 3.89M   | 6.15M   | +58.19     | 3.79M + WRITE                                                                                   | 6.05M + WRITE                                                                                   | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | force_new_era                  | 3.90M   | 6.31M   | +61.69     | 3.80M + WRITE                                                                                   | 6.21M + WRITE                                                                                   | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | force_new_era_always           | 3.86M   | 6.28M   | +62.71     | 3.76M + WRITE                                                                                   | 6.18M + WRITE                                                                                   | READ = 25.00K, WRITE = 100.00K                               |
|------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------|
| frame/staking/src/weights.rs | force_no_eras                  | 3.89M   | 6.37M   | +63.60     | 3.79M + WRITE                                                                                   | 6.27M + WRITE                                                                                   | READ = 25.00K, WRITE = 100.00K                               |
+------------------------------+--------------------------------+---------+---------+------------+-------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+--------------------------------------------------------------+
```
</details>

<details>
  <summary>Contracts</summary>  

```pre
+--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------+
| File                           | Extrinsic                             | Old     | New     | Change [%] | Old Weight Term                                                                         | New Weight Term                                                                          | Used variables                                   |
+=================================================================================================================================================================================================================================================================================================================================================+
| frame/contracts/src/weights.rs | upload_code                           | 3.13G   | 3.29G   | +5.05      | 51.72M + 48.00K * c + READ + 3 * WRITE                                                  | 81.48M + 50.00K * c + READ + 3 * WRITE                                                   | READ = 25.00K, WRITE = 100.00K, c = 64.23K       |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_hash_blake2_256_per_kb           | 97.63G  | 102.61G | +5.10      | 255.96M + 95.09M * n + 4 * READ + WRITE                                                 | 100.21M * n + 4 * READ + WRITE                                                           | READ = 25.00K, WRITE = 100.00K, n = 1.02K        |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | call_with_code_per_byte               | 7.15G   | 7.54G   | +5.36      | 205.19M + 53.00K * c + 4 * READ + 2 * WRITE                                             | 326.13M + 55.00K * c + 4 * READ + 2 * WRITE                                              | READ = 25.00K, WRITE = 100.00K, c = 131.07K      |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_hash_keccak_256_per_kb           | 251.82G | 266.16G | +5.69      | 208.86M + 245.72M * n + 4 * READ + WRITE                                                | 259.93M * n + 4 * READ + WRITE                                                           | READ = 25.00K, WRITE = 100.00K, n = 1.02K        |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_instantiate_per_transfer_salt_kb | 132.33G | 143.11G | +8.15      | 12.28G + 720.79M * t + 124.27M * s + 167 * READ + t * READ + 165 * WRITE + t * WRITE    | 19.03G + 152.69M * t + 129.07M * s + 167 * READ + t * READ + 165 * WRITE + t * WRITE     | READ = 25.00K, WRITE = 100.00K, s = 960, t = 1   |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | on_initialize_per_trie_key            | 999.92M | 1.11G   | +10.57     | 8.56M + 868.00K * k + READ + WRITE + k * WRITE                                          | 14.96M + 965.00K * k + READ + WRITE + k * WRITE                                          | READ = 25.00K, WRITE = 100.00K, k = 1.02K        |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_hash_sha2_256_per_kb             | 328.70G | 368.58G | +12.13     | 349.92M + 320.65M * n + 4 * READ + WRITE                                                | 359.94M * n + 4 * READ + WRITE                                                           | READ = 25.00K, WRITE = 100.00K, n = 1.02K        |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_caller_is_origin                 | 548.71M | 645.43M | +17.63     | 205.61M + 17.14M * r + 4 * READ + WRITE                                                 | 324.41M + 16.04M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_take_storage_per_kb              | 1.86G   | 2.21G   | +18.71     | 532.41M + 164.94M * n + 55 * READ + 5 * n * READ + 53 * WRITE + 5 * n * WRITE           | 725.26M + 184.41M * n + 55 * READ + 5 * n * READ + 53 * WRITE + 5 * n * WRITE            | READ = 25.00K, WRITE = 100.00K, n = 8            |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_get_storage_per_kb               | 1.71G   | 2.04G   | +19.24     | 465.29M + 155.11M * n + 55 * READ + 5 * n * READ + WRITE                                | 629.03M + 175.74M * n + 55 * READ + 5 * n * READ + WRITE                                 | READ = 25.00K, WRITE = 100.00K, n = 8            |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_take_storage                     | 4.62G   | 5.52G   | +19.60     | 188.88M + 432.78M * r + 5 * READ + 80 * r * READ + 2 * WRITE + 80 * r * WRITE           | 307.48M + 511.40M * r + 5 * READ + 80 * r * READ + 2 * WRITE + 80 * r * WRITE            | READ = 25.00K, WRITE = 100.00K, r = 10           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_clear_storage                    | 4.33G   | 5.23G   | +20.61     | 184.80M + 404.93M * r + 5 * READ + 80 * r * READ + 2 * WRITE + 80 * r * WRITE           | 306.24M + 482.14M * r + 5 * READ + 80 * r * READ + 2 * WRITE + 80 * r * WRITE            | READ = 25.00K, WRITE = 100.00K, r = 10           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_hash_keccak_256                  | 1.68G   | 2.03G   | +20.68     | 209.22M + 73.73M * r + 4 * READ + WRITE                                                 | 327.10M + 85.25M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_set_storage                      | 4.50G   | 5.46G   | +21.27     | 161.25M + 424.00M * r + 4 * READ + 80 * r * READ + WRITE + 80 * r * WRITE               | 284.52M + 507.43M * r + 4 * READ + 80 * r * READ + WRITE + 80 * r * WRITE                | READ = 25.00K, WRITE = 100.00K, r = 10           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_clear_storage_per_kb             | 1.12G   | 1.36G   | +21.79     | 500.96M + 76.00M * n + 55 * READ + 5 * n * READ + 52 * WRITE + 5 * n * WRITE            | 683.86M + 83.65M * n + 55 * READ + 5 * n * READ + 52 * WRITE + 5 * n * WRITE             | READ = 25.00K, WRITE = 100.00K, n = 8            |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_set_storage_per_old_kb           | 1.14G   | 1.39G   | +22.11     | 529.81M + 74.55M * n + 55 * READ + 5 * n * READ + 53 * WRITE + 5 * n * WRITE            | 720.59M + 82.16M * n + 55 * READ + 5 * n * READ + 53 * WRITE + 5 * n * WRITE             | READ = 25.00K, WRITE = 100.00K, n = 8            |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_call                            | 432.08M | 528.26M | +22.26     | 74.88M + 7.14M * r                                                                      | 119.71M + 8.17M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_contains_storage_per_kb          | 982.83M | 1.21G   | +22.86     | 423.06M + 69.67M * n + 54 * READ + 5 * n * READ + WRITE                                 | 598.23M + 75.86M * n + 54 * READ + 5 * n * READ + WRITE                                  | READ = 25.00K, WRITE = 100.00K, n = 8            |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_get_storage                      | 3.58G   | 4.41G   | +23.15     | 177.68M + 338.17M * r + 4 * READ + 80 * r * READ + WRITE                                | 294.89M + 409.32M * r + 4 * READ + 80 * r * READ + WRITE                                 | READ = 25.00K, WRITE = 100.00K, r = 10           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_deposit_event_per_topic_and_kb   | 2.62G   | 3.23G   | +23.34     | 439.78M + 264.69M * t + 67.64M * n + 4 * READ + 80 * t * READ + WRITE + 80 * t * WRITE  | 745.16M + 331.68M * t + 70.03M * n + 4 * READ + 80 * t * READ + WRITE + 80 * t * WRITE   | READ = 25.00K, WRITE = 100.00K, n = 16, t = 4    |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_call_indirect                   | 545.76M | 683.23M | +25.19     | 88.67M + 9.14M * r                                                                      | 125.93M + 11.15M * r                                                                     | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_set_storage_per_new_kb           | 1.22G   | 1.53G   | +25.22     | 529.25M + 85.28M * n + 55 * READ + 5 * n * READ + 53 * WRITE + 5 * n * WRITE            | 737.90M + 97.76M * n + 55 * READ + 5 * n * READ + 53 * WRITE + 5 * n * WRITE             | READ = 25.00K, WRITE = 100.00K, n = 8            |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_contains_storage                 | 3.31G   | 4.15G   | +25.31     | 179.12M + 311.08M * r + 4 * READ + 80 * r * READ + WRITE                                | 289.72M + 383.81M * r + 4 * READ + 80 * r * READ + WRITE                                 | READ = 25.00K, WRITE = 100.00K, r = 10           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_debug_message                    | 794.82M | 1.00G   | +26.20     | 140.28M + 32.72M * r + 4 * READ + WRITE                                                 | 213.74M + 39.46M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_call_per_transfer_clone_kb       | 20.63G  | 26.26G  | +27.29     | 9.20G + 1.46G * t + 9.72M * c + 85 * READ + 81 * t * READ + 81 * WRITE + 81 * t * WRITE | 14.33G + 1.97G * t + 9.69M * c + 85 * READ + 81 * t * READ + 81 * WRITE + 81 * t * WRITE | READ = 25.00K, WRITE = 100.00K, c = 1.02K, t = 1 |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_hash_blake2_128                  | 1.23G   | 1.58G   | +28.23     | 208.15M + 51.26M * r + 4 * READ + WRITE                                                 | 329.85M + 62.59M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_hash_blake2_256                  | 1.24G   | 1.59G   | +28.23     | 206.16M + 51.64M * r + 4 * READ + WRITE                                                 | 325.67M + 63.16M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_hash_sha2_256                    | 1.43G   | 1.84G   | +28.85     | 203.96M + 61.31M * r + 4 * READ + WRITE                                                 | 324.97M + 75.89M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | on_initialize_per_queue_item          | 1.99G   | 2.57G   | +29.10     | 1.94M * q + READ + WRITE                                                                | 12.00M + 2.50M * q + READ + WRITE                                                        | READ = 25.00K, WRITE = 100.00K, q = 1.02K        |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_is_contract                      | 6.30G   | 8.20G   | +30.19     | 106.22M + 307.65M * r + 4 * READ + 80 * r * READ + WRITE                                | 210.67M + 397.51M * r + 4 * READ + 80 * r * READ + WRITE                                 | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_code_hash                        | 7.52G   | 9.92G   | +31.82     | 104.50M + 368.90M * r + 4 * READ + 80 * r * READ + WRITE                                | 225.31M + 482.56M * r + 4 * READ + 80 * r * READ + WRITE                                 | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_memory_grow                     | 260.70M | 348.87M | +33.82     | 73.58M + 187.11M * r                                                                    | 119.14M + 229.72M * r                                                                    | READ = 25.00K, WRITE = 100.00K, r = 1            |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_input                            | 1.02G   | 1.39G   | +37.17     | 208.56M + 40.33M * r + 4 * READ + WRITE                                                 | 328.82M + 53.18M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_set_code_hash                    | 15.69G  | 21.59G  | +37.64     | 774.38M * r + 79 * r * READ + 79 * r * WRITE                                            | 1.07G * r + 79 * r * READ + 79 * r * WRITE                                               | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | remove_code                           | 30.34M  | 42.46M  | +39.95     | 30.02M + READ + 3 * WRITE                                                               | 42.14M + READ + 3 * WRITE                                                                | READ = 25.00K, WRITE = 100.00K                   |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | set_code                              | 27.57M  | 38.76M  | +40.61     | 27.19M + 3 * READ + 3 * WRITE                                                           | 38.39M + 3 * READ + 3 * WRITE                                                            | READ = 25.00K, WRITE = 100.00K                   |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_return_per_kb                    | 391.85M | 559.95M | +42.90     | 204.26M + 183.00K * n + 4 * READ + WRITE                                                | 324.23M + 230.00K * n + 4 * READ + WRITE                                                 | READ = 25.00K, WRITE = 100.00K, n = 1.02K        |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_value_transferred                | 1.02G   | 1.47G   | +44.11     | 207.41M + 40.70M * r + 4 * READ + WRITE                                                 | 326.57M + 57.27M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_minimum_balance                  | 1.02G   | 1.47G   | +44.11     | 209.26M + 40.48M * r + 4 * READ + WRITE                                                 | 328.80M + 56.98M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_address                          | 1.02G   | 1.47G   | +44.13     | 206.95M + 40.79M * r + 4 * READ + WRITE                                                 | 328.45M + 57.29M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_transfer                         | 30.34G  | 43.74G  | +44.17     | 127.18M + 1.50G * r + 5 * READ + 80 * r * READ + 2 * WRITE + 80 * r * WRITE             | 239.61M + 2.17G * r + 5 * READ + 80 * r * READ + 2 * WRITE + 80 * r * WRITE              | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_deposit_event                    | 5.02G   | 7.25G   | +44.45     | 220.86M + 239.95M * r + 4 * READ + WRITE                                                | 353.27M + 344.89M * r + 4 * READ + WRITE                                                 | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_gas_left                         | 1.02G   | 1.47G   | +44.45     | 208.69M + 40.60M * r + 4 * READ + WRITE                                                 | 327.61M + 57.34M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_caller                           | 1.03G   | 1.48G   | +44.60     | 206.41M + 40.99M * r + 4 * READ + WRITE                                                 | 327.88M + 57.80M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_now                              | 1.01G   | 1.47G   | +45.29     | 206.97M + 40.25M * r + 4 * READ + WRITE                                                 | 328.66M + 57.09M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_block_number                     | 1.01G   | 1.47G   | +45.82     | 206.45M + 40.13M * r + 4 * READ + WRITE                                                 | 328.29M + 57.16M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_weight_to_fee                    | 2.19G   | 3.26G   | +49.16     | 211.61M + 98.67M * r + 5 * READ + WRITE                                                 | 329.21M + 146.51M * r + 5 * READ + WRITE                                                 | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_random                           | 2.88G   | 4.30G   | +49.31     | 208.87M + 133.44M * r + 5 * READ + WRITE                                                | 328.45M + 198.41M * r + 5 * READ + WRITE                                                 | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_own_code_hash                    | 1.10G   | 1.64G   | +49.52     | 208.70M + 44.45M * r + 4 * READ + WRITE                                                 | 327.67M + 65.68M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | call                                  | 149.53M | 225.30M | +50.67     | 149.23M + 4 * READ + 2 * WRITE                                                          | 225.00M + 4 * READ + 2 * WRITE                                                           | READ = 25.00K, WRITE = 100.00K                   |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_gas                              | 521.26M | 786.73M | +50.93     | 134.48M + 19.33M * r + 4 * READ + WRITE                                                 | 203.83M + 29.14M * r + 4 * READ + WRITE                                                  | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_instantiate                      | 424.83G | 641.56G | +51.02     | 21.20G * r + 6 * READ + 320 * r * READ + 3 * WRITE + 320 * r * WRITE                    | 32.04G * r + 6 * READ + 320 * r * READ + 3 * WRITE + 320 * r * WRITE                     | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_balance                          | 2.55G   | 3.87G   | +52.00     | 209.81M + 116.83M * r + 5 * READ + WRITE                                                | 328.38M + 177.12M * r + 5 * READ + WRITE                                                 | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_terminate                        | 266.80M | 405.81M | +52.10     | 206.62M + 59.38M * r + 4 * READ + 4 * r * READ + WRITE + 5 * r * WRITE                  | 326.83M + 78.18M * r + 4 * READ + 4 * r * READ + WRITE + 5 * r * WRITE                   | READ = 25.00K, WRITE = 100.00K, r = 1            |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_return                           | 203.79M | 323.82M | +58.90     | 203.59M + 4 * READ + WRITE                                                              | 321.37M + 2.25M * r + 4 * READ + WRITE                                                   | READ = 25.00K, WRITE = 100.00K, r = 1            |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_call_indirect_per_param         | 158.63M | 252.62M | +59.25     | 98.60M + 469.00K * p                                                                    | 136.91M + 904.00K * p                                                                    | READ = 25.00K, WRITE = 100.00K, p = 128          |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | on_process_deletion_queue_batch       | 1.68M   | 2.68M   | +59.86     | 1.65M + READ                                                                            | 2.66M + READ                                                                             | READ = 25.00K, WRITE = 100.00K                   |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_call                             | 297.42G | 477.71G | +60.62     | 14.86G * r + 5 * READ + 80 * r * READ + WRITE + 80 * r * WRITE                          | 7.09M + 23.88G * r + 5 * READ + 80 * r * READ + WRITE + 80 * r * WRITE                   | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | seal_delegate_call                    | 295.98G | 475.90G | +60.79     | 14.80G * r + 79 * r * READ + WRITE                                                      | 23.79G * r + 79 * r * READ + WRITE                                                       | READ = 25.00K, WRITE = 100.00K, r = 20           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_br_table_per_entry              | 77.29M  | 125.03M | +61.76     | 76.27M + 4.00K * e                                                                      | 124.26M + 3.00K * e                                                                      | READ = 25.00K, WRITE = 100.00K, e = 256          |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_global_set                      | 145.03M | 236.36M | +62.97     | 76.98M + 1.36M * r                                                                      | 128.36M + 2.16M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_global_get                      | 136.51M | 227.57M | +66.71     | 76.91M + 1.19M * r                                                                      | 129.38M + 1.96M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64remu                         | 177.33M | 299.40M | +68.84     | 74.13M + 2.06M * r                                                                      | 119.40M + 3.60M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64divu                         | 177.51M | 300.34M | +69.20     | 73.86M + 2.07M * r                                                                      | 119.39M + 3.62M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64divs                         | 173.89M | 305.42M | +75.64     | 73.99M + 2.00M * r                                                                      | 119.77M + 3.71M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64rems                         | 175.15M | 311.89M | +78.07     | 73.80M + 2.03M * r                                                                      | 119.54M + 3.85M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_local_set                       | 108.73M | 193.88M | +78.31     | 74.33M + 688.00K * r                                                                    | 119.88M + 1.48M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_local_get                       | 105.75M | 189.26M | +78.96     | 74.56M + 624.00K * r                                                                    | 120.11M + 1.38M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_if                              | 171.58M | 308.83M | +79.99     | 73.98M + 1.95M * r                                                                      | 119.38M + 3.79M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_memory_current                  | 107.42M | 194.76M | +81.31     | 74.37M + 661.00K * r                                                                    | 119.41M + 1.51M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64const                        | 104.56M | 193.10M | +84.69     | 73.95M + 612.00K * r                                                                    | 119.45M + 1.47M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_br_table                        | 153.49M | 287.14M | +87.07     | 73.34M + 1.60M * r                                                                      | 118.54M + 3.37M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_br_if                           | 145.52M | 273.20M | +87.73     | 73.57M + 1.44M * r                                                                      | 119.50M + 3.07M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_local_tee                       | 120.06M | 227.35M | +89.36     | 74.61M + 909.00K * r                                                                    | 120.20M + 2.14M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64ltu                          | 142.05M | 271.93M | +91.43     | 74.05M + 1.36M * r                                                                      | 119.38M + 3.05M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64gtu                          | 141.92M | 272.19M | +91.80     | 74.27M + 1.35M * r                                                                      | 119.34M + 3.06M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64lts                          | 141.67M | 271.82M | +91.88     | 73.92M + 1.35M * r                                                                      | 119.53M + 3.05M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64leu                          | 142.25M | 272.97M | +91.89     | 73.85M + 1.37M * r                                                                      | 119.12M + 3.08M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64ne                           | 141.71M | 271.99M | +91.94     | 73.71M + 1.36M * r                                                                      | 119.34M + 3.05M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64geu                          | 141.63M | 272.02M | +92.07     | 73.98M + 1.35M * r                                                                      | 119.38M + 3.05M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64rotr                         | 141.75M | 272.44M | +92.19     | 73.75M + 1.36M * r                                                                      | 119.30M + 3.06M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64eq                           | 141.56M | 272.06M | +92.19     | 74.06M + 1.35M * r                                                                      | 119.71M + 3.05M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64shl                          | 141.68M | 272.31M | +92.20     | 74.33M + 1.35M * r                                                                      | 119.36M + 3.06M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64gts                          | 141.48M | 271.94M | +92.21     | 74.03M + 1.35M * r                                                                      | 119.24M + 3.05M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64ges                          | 141.43M | 271.86M | +92.22     | 74.03M + 1.35M * r                                                                      | 119.31M + 3.05M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64les                          | 141.45M | 271.94M | +92.25     | 73.95M + 1.35M * r                                                                      | 119.29M + 3.05M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64shru                         | 141.71M | 272.73M | +92.46     | 73.81M + 1.36M * r                                                                      | 119.33M + 3.07M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_select                          | 162.49M | 312.74M | +92.46     | 73.84M + 1.77M * r                                                                      | 119.79M + 3.86M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64rotl                         | 141.62M | 272.60M | +92.48     | 73.72M + 1.36M * r                                                                      | 119.40M + 3.06M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64shrs                         | 141.62M | 273.19M | +92.90     | 73.67M + 1.36M * r                                                                      | 119.39M + 3.08M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64mul                          | 140.42M | 271.66M | +93.47     | 74.22M + 1.32M * r                                                                      | 119.71M + 3.04M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64or                           | 140.70M | 272.22M | +93.47     | 74.20M + 1.33M * r                                                                      | 119.52M + 3.05M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_br                              | 120.97M | 234.08M | +93.50     | 73.92M + 941.00K * r                                                                    | 119.38M + 2.29M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64sub                          | 140.43M | 272.28M | +93.89     | 73.88M + 1.33M * r                                                                      | 119.18M + 3.06M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64and                          | 140.42M | 272.39M | +93.98     | 74.07M + 1.33M * r                                                                      | 119.39M + 3.06M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64add                          | 140.40M | 272.41M | +94.02     | 74.00M + 1.33M * r                                                                      | 119.26M + 3.06M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64xor                          | 140.29M | 272.36M | +94.14     | 74.24M + 1.32M * r                                                                      | 119.41M + 3.06M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i32wrapi64                      | 118.19M | 229.68M | +94.33     | 74.29M + 878.00K * r                                                                    | 119.33M + 2.21M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64ctz                          | 118.64M | 230.63M | +94.39     | 73.99M + 893.00K * r                                                                    | 119.58M + 2.22M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64eqz                          | 119.17M | 231.83M | +94.54     | 74.12M + 901.00K * r                                                                    | 119.38M + 2.25M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64clz                          | 118.41M | 230.39M | +94.58     | 74.21M + 884.00K * r                                                                    | 119.94M + 2.21M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64popcnt                       | 118.53M | 230.71M | +94.63     | 73.98M + 891.00K * r                                                                    | 119.31M + 2.23M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64extendui32                   | 117.50M | 229.91M | +95.66     | 74.10M + 868.00K * r                                                                    | 119.41M + 2.21M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64extendsi32                   | 117.28M | 229.80M | +95.94     | 73.98M + 866.00K * r                                                                    | 119.50M + 2.21M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64load                         | 140.26M | 279.10M | +98.99     | 74.06M + 1.32M * r                                                                      | 119.95M + 3.18M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
|--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------|
| frame/contracts/src/weights.rs | instr_i64store                        | 145.49M | 295.07M | +102.82    | 74.14M + 1.43M * r                                                                      | 120.27M + 3.50M * r                                                                      | READ = 25.00K, WRITE = 100.00K, r = 50           |
+--------------------------------+---------------------------------------+---------+---------+------------+-----------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------+--------------------------------------------------+
```
</details>

Dont know whats going on, but its not this MR. Will test again here https://github.com/paritytech/substrate/pull/11581

**Review by ggwpez — APPROVED** [review]

**Comment by ggwpez** [comment]
bot rebase

**Comment by bernardoaraujor** [comment]
merging/reviewing seems blocked to me

**Comment by ggwpez** [comment]
bot merge
