### PR TITLE
contracts: add sr25519_verify

### LINKED ISSUE #13703: contracts: Sr25519 (Schnorrkel) signature verification
**Questions**

- Is this a bug concerning building of ink! smart contracts?
    - no
- Is this a bug that appears when interacting with smart contracts via the Polkadot JS browser UI?
    - no

**FAQ**

- Are you using the nightly Rust channel to compile your smart contract?
- no
- Are you using an up-to-date `cargo-contract`? Check via `cargo contract --version`.
- yes
- Are you using an up-to-date ink! version in your smart contract?
- yes

**Describe the bug**
I cannot verify a sr25519 (schnorrkel) signature.

**Expected behavior**
Ability to verify a sr25519 (schnorrkel) signature in a manner similar to the `ecdsa_recover()` function.

**Screenshots**

**Additional context**
Our business logic dictates that we need to sign a payload on our frontend using the polkadot JS extension. Unfortunately, the keyring used by the extension stores the keys in sr25519 format and provide no functionality to load keys in a different format.

We need to verify these sr25519 signatures in ink. However, only ecdsa verification is currently provided via the `ecdsa_recover()` function. As we cannot access ecdsa on the polkadot JS extension, `ecdsa_recover()` is a no-go.

I've managed to add the schnorrkel crate to our ink contract and successfully verify sr25519 signatures from the frontend. Anyone wanting to do the same can see our ink contract code [here](https://github.com/prosopo/protocol/blob/1f6978a744636cf63fc80cf7676ee93082d05dad/contracts/lib.rs#L565) and js code [here](https://github.com/prosopo/procaptcha/blob/73b18ad192681137ec33698dd5f7d88905a1681d/src/modules/Manager.ts#L119) (one thing to note is that the polkadot js extension wraps the payload to sign in a `<Bytes>` tag - this was a big "gotcha!" for us).

My question is: is sr25519 going to be implemented in ink? Or is importing the schnorrkel crate the only option? Schnorrkel adds ~30KB to the contract size, which is an unfortunate but necessary hit for us at the moment.

### PR DESCRIPTION
**Pull request by pgherveou**
fix https://github.com/paritytech/substrate/issues/13703

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2596313

**Comment by pgherveou** [comment]
bot bench $ pallet dev pallet_contracts

File: frame/contracts/src/weights.rs
Comment (pgherveou) [inline frame/contracts/src/weights.rs:1]: missing the actual benchmark to generate this. working on it

**Comment by pgherveou** [comment]
@athei  quicks questions, before I take a second pass at this:

- should we implement a generic verify function as demonstrated here
https://github.com/AstarNetwork/astar-frame/pull/141/files#diff-16c73d79bacd21e8243b65478b218afa791cb812008c4f8055a549d03cd4862a

- Not too sure what are the exact use cases here, but do we want the message payload to be hashed so it's constant size or 
should it just be an arbitrary payload

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2622226

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2622212

File: frame/contracts/src/exec.rs [hunk 1]
```diff
@@ -35,8 +35,14 @@ use frame_support::{
...
 use pallet_contracts_primitives::ExecReturnValue;
 use smallvec::{Array, SmallVec};
-use sp_core::ecdsa::Public as ECDSAPublic;
-use sp_io::{crypto::secp256k1_ecdsa_recover_compressed, hashing::blake2_256};
+use sp_core::{
+	ecdsa::Public as ECDSAPublic,
+	sr25519::{Public as SR25519Public, Signature as SR25519Signature},
+};
+use sp_io::{
+	crypto::{secp256k1_ecdsa_recover_compressed, sr25519_verify as crypto_sr25519_verify},
```
Comment (athei) [inline frame/contracts/src/exec.rs:43]: I don't think we need the rename. Our function is scoped within the trait.

```suggestion
	crypto::{secp256k1_ecdsa_recover_compressed, sr25519_verify},
```

File: frame/contracts/src/wasm/runtime.rs [hunk 2]
```diff
@@ -251,6 +253,8 @@ pub enum RuntimeCosts {
 	HashBlake128(u32),
 	/// Weight of calling `seal_ecdsa_recover`.
 	EcdsaRecovery,
+	/// Weight of calling `seal_sr25519_verify`.
+	Sr25519Verify,
```
Comment (athei) [inline frame/contracts/src/wasm/runtime.rs:257]: Cost is not constant but linear over the message length.

**Review by athei — COMMENTED** [review]
> should we implement a generic verify function as demonstrated here
> https://github.com/AstarNetwork/astar-frame/pull/141/files#diff-16c73d79bacd21e8243b65478b218afa791cb812008c4f8055a549d03cd4862a

I would say we opt for individual host functions. We don't have precedence for multiplexed functions. Reason is that it makes benchmarking harder when we multiplex: The weight will depend on the argument which decides which algorithm to depley. Hence this PR should a function for sr25519 and one for ed25519.

> Not too sure what are the exact use cases here, but do we want the message payload to be hashed so it's constant size or
> should it just be an arbitrary payload

The message will be an arbitrary payload as demonstrated in this PR. Reason is that this is what the functions in `sp_io::crypto` expect. Weight needs to be linear over its length.

File: frame/contracts/src/wasm/mod.rs [hunk 3]
```diff
@@ -614,6 +616,10 @@ mod tests {
 			self.ecdsa_recover.borrow_mut().push((*signature, *message_hash));
 			Ok([3; 33])
 		}
+		fn sr25519_verify(&self, signature: &[u8; 64], message: &[u8], pub_key: &[u8; 32]) -> bool {
```
Comment (agryaznov) [inline frame/contracts/src/wasm/mod.rs:619]: we need to add test here as well, on the mocked Ext, see below for examples

File: frame/contracts/src/wasm/runtime.rs [hunk 4]
```diff
@@ -2466,6 +2471,43 @@ pub mod env {
...
+	///   be decodable as a 64 bytes. Traps otherwise.
+	/// - `message_ptr`: the pointer into the linear memory where the message is placed.
+	/// - `message_len`: the length of the message payload. Should be decodable as a Scale encoded
+	///   Vec<u8>. Traps otherwise.
+	/// - `pub_key_ptr`: the pointer into the linear memory where the public key is placed. Should
+	///   be decodable as a 32 bytes. Traps otherwise.
+	/// # Errors
+	///
+	/// - `ReturnCode::Sr25519VerifyFailed
+	#[prefixed_alias]
```
Comment (agryaznov) [inline frame/contracts/src/wasm/runtime.rs:2488]:
```suggestion
	#[unstable]
	#[prefixed_alias]
```
new functions not covered with e2e tests should be marked _unstable_

File: frame/contracts/src/tests.rs [hunk 5]
```diff
@@ -2906,6 +2906,68 @@ fn ecdsa_recover() {
...
+				None,
+				params,
+				false,
+				Determinism::Enforced,
+			)
+			.result
+		};
+
+		assert!(call_with_message(&b"hello world").is_ok());
+		assert!(call_with_message(&b"hello worlD").is_err());
```
Comment (agryaznov) [inline frame/contracts/src/tests.rs:2967]: let's check the returned err code here

File: frame/contracts/fixtures/sr25519_verify.wat [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+			$result
+			(call $seal_sr25519_verify
+				(local.get $signature_ptr)
+				(local.get $message_ptr)
+				(i32.const 12)
+				(local.get $pub_key_ptr)
+			)
+		)
+
+		;; trap if the result is not 0x0 (false)
```
Comment (agryaznov) [inline frame/contracts/fixtures/sr25519_verify.wat:60]:
```suggestion
		;; trap if the result is not 0x0 (ReturnCode::Success)
```

**Review by agryaznov — CHANGES_REQUESTED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2634133

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2634132

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2634147

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2642853

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2642852

**Comment by pgherveou** [comment]
oups bad merge, fixing it now

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2642925

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2642924

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2642978

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2642977

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2643029

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-benches
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2643030

File: frame/contracts/fixtures/sr25519_verify.wat [hunk 7]
```diff
@@ -0,0 +1,56 @@
+;; This contract:
+;; 1) Reads signature, message and public key from the input
+;; 2) Calls sr25519_verify
+;; 3) Traps if the signature is invalid
```
Comment (pgherveou) [inline frame/contracts/fixtures/sr25519_verify.wat:4]:
```suggestion
;; 2) Calls and return the result of sr25519_verify
```

**Comment by pgherveou** [comment]
bot bench $ pallet pallet_contracts

File: frame/contracts/src/benchmarking/mod.rs [hunk 8]
```diff
@@ -2008,9 +2008,61 @@ benchmarks! {
 		let origin = RawOrigin::Signed(instance.caller.clone());
 	}: call(origin, instance.addr, 0u32.into(), Weight::MAX, None, vec![])
 
+	// `n`: Messaqe input to verify in bytes
```
Comment (pgherveou) [inline frame/contracts/src/benchmarking/mod.rs:2011]:
```suggestion
	// `n`: Message input to verify in bytes
```

**Comment by pgherveou** [comment]
bot bench $ pallet pallet_contracts

**Comment by pgherveou** [comment]
bot cancel

**Comment by pgherveou** [comment]
bot bench $ pallet dev pallet_contracts

File: frame/contracts/fixtures/sr25519_verify.wat [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+(module
+    ;; import the host functions from the seal0 module
+	(import "seal0" "seal_sr25519_verify" (func $seal_sr25519_verify (param i32 i32 i32 i32) (result i32)))
+	(import "seal0" "seal_input" (func $seal_input (param i32 i32)))
+	(import "seal0" "seal_return" (func $seal_return (param i32 i32 i32)))
+
+	;; give the program 1 page of memory
+	(import "env" "memory" (memory 1 1))
+
+	;; [4, 8) len of signature + message + public key - 64 + 12 + 32 = 108 bytes
```
Comment (pgherveou) [inline frame/contracts/fixtures/sr25519_verify.wat:14]:
```suggestion
	;; [4, 8) length of signature + message + public key - 64 + 12 + 32 = 108 bytes
```

File: frame/contracts/src/wasm/runtime.rs [hunk 10]
```diff
@@ -2466,6 +2471,48 @@ pub mod env {
...
+	/// # Parameters
+	///
+	/// - `signature_ptr`: the pointer into the linear memory where the signature is placed. Should
+	///   be decodable as a 64 bytes. Traps otherwise.
+	/// - `pub_key_ptr`: the pointer into the linear memory where the public key is placed. Should
+	///   be decodable as a 32 bytes. Traps otherwise.
+	/// - `message_len`: the length of the message payload.
+	/// - `message_ptr`: the pointer into the linear memory where the message is placed. Should be
+	///   decodable as a Scale encoded Vec<u8>. Traps otherwise
+	/// # Errors
```
Comment (pgherveou) [inline frame/contracts/src/wasm/runtime.rs:2485]:
```suggestion
    ///
	/// # Errors
```

File: frame/contracts/src/benchmarking/mod.rs [hunk 11]
```diff
@@ -2008,9 +2008,61 @@ benchmarks! {
 		let origin = RawOrigin::Signed(instance.caller.clone());
 	}: call(origin, instance.addr, 0u32.into(), Weight::MAX, None, vec![])
 
+	// `n`: Message input to verify in bytes.
```
Comment (pgherveou) [inline frame/contracts/src/benchmarking/mod.rs:2011]:
```suggestion
	// `n`: Message input length to verify in bytes.
```

**Comment by pgherveou** [comment]
bot bench $ pallet pallet_contracts

Note to self do not commit until jobs done

**Comment by pgherveou** [comment]
bot bench $ pallet pallet_contracts

**Comment by pgherveou** [comment]
bot bench $ pallet dev pallet_contracts

File: frame/contracts/fixtures/sr25519_verify.wat [hunk 12]
```diff
@@ -0,0 +1,55 @@
...
+	(import "seal0" "seal_sr25519_verify" (func $seal_sr25519_verify (param i32 i32 i32 i32) (result i32)))
+	(import "seal0" "seal_input" (func $seal_input (param i32 i32)))
+	(import "seal0" "seal_return" (func $seal_return (param i32 i32 i32)))
+
+	;; give the program 1 page of memory
+	(import "env" "memory" (memory 1 1))
+
+	;; [4, 8) length of signature + message + public key - 64 + 12 + 32 = 108 bytes
+	;; write the length of the input (108 bytes) at offset 4
+	(data (i32.const 4) "\6c")
```
Comment (athei) [inline frame/contracts/fixtures/sr25519_verify.wat:16]: `0` is a valid address in wasm. Maybe I am missing something but I can't see a reason to start at `4` rather than zero.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2650245

File: frame/contracts/src/wasm/runtime.rs [hunk 13]
```diff
@@ -2466,6 +2471,49 @@ pub mod env {
...
+		ctx.charge_gas(RuntimeCosts::Sr25519Verify(message_len))?;
+
+		let mut signature: [u8; 64] = [0; 64];
+		ctx.read_sandbox_memory_into_buf(memory, signature_ptr, &mut signature)?;
+
+		let mut pub_key: [u8; 32] = [0; 32];
+		ctx.read_sandbox_memory_into_buf(memory, pub_key_ptr, &mut pub_key)?;
+
+		let message: Vec<u8> =
+			ctx.read_sandbox_memory_as_unbounded(memory, message_ptr, message_len)?;
```
[the remark this answers is not in the document]
Comment (pgherveou) [reply frame/contracts/src/wasm/runtime.rs:2507]: ah nvm understood what you mean

**Comment by pgherveou** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by pgherveou** [comment]
bot bench $ pallet dev pallet_contracts

**Comment by oleg-plakida** [comment]
> @pgherveou Command `"$PIPELINE_SCRIPTS_DIR/commands/bench/bench.sh" pallet dev pallet_contracts` has finished. Result: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2653407 has finished. If any artifacts were generated, you can download them from https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2653405/artifacts/download.

It's not finished. I've restarted the job.

File: frame/contracts/fixtures/sr25519_verify.wat [hunk 14]
```diff
@@ -0,0 +1,55 @@
...
+		;; Memory layout during `call`
+		;; [10, 74) signature
+		;; [74, 106) public key
+		;; [106, 117) message (11 bytes)
+		(local.set $signature_ptr (i32.const 10))
+		(local.set $pub_key_ptr (i32.const 74))
+		(local.set $message_ptr (i32.const 106))
+
+		;; store the input into the memory, starting at the signature and 
+		;; up to 108 bytes stored at offset 0
```
Comment (pgherveou) [inline frame/contracts/fixtures/sr25519_verify.wat:37]:
```suggestion
		;; up to 107 bytes stored at offset 0
```

File: frame/contracts/fixtures/sr25519_verify.wat [hunk 15]
```diff
@@ -0,0 +1,55 @@
...
+    ;; import the host functions from the seal0 module
+	(import "seal0" "sr25519_verify" (func $sr25519_verify (param i32 i32 i32 i32) (result i32)))
+	(import "seal0" "seal_input" (func $seal_input (param i32 i32)))
+	(import "seal0" "seal_return" (func $seal_return (param i32 i32 i32)))
+
+	;; give the program 1 page of memory
+	(import "env" "memory" (memory 1 1))
+
+	;; [0, 4) length of signature + message + public key - 64 + 11 + 32 = 107 bytes
+	;; write the length of the input (107 bytes) at offset 0
```
Comment (pgherveou) [inline frame/contracts/fixtures/sr25519_verify.wat:15]:
```suggestion
	;; write the length of the input (6b = 107) bytes at offset 0
```

File: frame/contracts/src/wasm/runtime.rs [hunk 16]
```diff
@@ -251,6 +253,8 @@ pub enum RuntimeCosts {
 	HashBlake128(u32),
 	/// Weight of calling `seal_ecdsa_recover`.
 	EcdsaRecovery,
+	/// Weight of calling `seal_sr25519_verify` for the given input length.
```
Comment (pgherveou) [inline frame/contracts/src/wasm/runtime.rs:256]:
```suggestion
	/// Weight of calling `seal_sr25519_verify` for the given input size.
```

File: frame/contracts/src/wasm/runtime.rs [hunk 17]
```diff
@@ -2466,6 +2473,47 @@ pub mod env {
...
+	///
+	/// # Parameters
+	///
+	/// - `signature_ptr`: the pointer into the linear memory where the signature is placed. Should
+	///   be decodable as a 64 bytes. Traps otherwise.
+	/// - `pub_key_ptr`: the pointer into the linear memory where the public key is placed. Should
+	///   be decodable as a 32 bytes. Traps otherwise.
+	/// - `message_len`: the length of the message payload.
+	/// - `message_ptr`: the pointer into the linear memory where the message is placed. Should be
+	///   decodable as a Scale encoded Vec<u8>. Traps otherwise
```
Comment (pgherveou) [inline frame/contracts/src/wasm/runtime.rs:2486]:
```suggestion
	/// - `message_ptr`: the pointer into the linear memory where the message is placed.
```

File: frame/contracts/src/benchmarking/mod.rs [hunk 18]
```diff
@@ -2008,9 +2008,114 @@ benchmarks! {
...
+
 	// Only calling the function itself with valid arguments.
 	// It generates different private keys and signatures for the message "Hello world".
-	// This is a slow call: We redeuce the number of runs.
+	// This is a slow call: We reduce the number of runs.
+	#[pov_mode = Measured]
+	seal_sr25519_verify {
+		let r in 0 .. API_BENCHMARK_RUNS / 10;
+
+		let message = b"Hello world".to_vec().encode();
```
Comment (pgherveou) [inline frame/contracts/src/benchmarking/mod.rs:2070]:
```suggestion
		let message = b"Hello world".to_vec();
```

File: frame/contracts/src/benchmarking/mod.rs [hunk 19]
```diff
@@ -2008,9 +2008,114 @@ benchmarks! {
 		let origin = RawOrigin::Signed(instance.caller.clone());
 	}: call(origin, instance.addr, 0u32.into(), Weight::MAX, None, vec![])
 
+	// `n`: Message input length to verify in bytes.
+	#[pov_mode = Measured]
+	seal_sr25519_verify_per_byte {
+		let n in 0 .. T::MaxCodeLen::get() - 255; // need some buffer so the code size does not
+												  // exceed the max code size.
+
+		let message = (0..n).zip((32u8..127u8).cycle()).map(|(_, c)| c).collect::<Vec<_>>().encode();
```
Comment (pgherveou) [inline frame/contracts/src/benchmarking/mod.rs:2017]:
```suggestion
		let message = (0..n).zip((32u8..127u8).cycle()).map(|(_, c)| c).collect::<Vec<_>>();
```

**Review by athei — APPROVED** [review]

**Review by agryaznov — APPROVED** [review]
only nitpicks

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2673478

**Comment by pgherveou** [comment]
bot merge

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/april-updates-for-substrate-and-polkadot-devs/2764/1
