### PR TITLE
babe: Disable unused median calculation

### LINKED ISSUE #3248: the node crashed during block produce
Hi, I run a node based on Substrate, there seemed something wrong with Babe Consensus, since the node crashed.

Below is the detail, please check:
stack backtrace:
   0: backtrace::backtrace::trace::hbf13aa9371ea9838 (0x107ee86cc)
   1: backtrace::capture::Backtrace::new::hc0ad6eecb1c0c878 (0x107ee7828)
   2: substrate_panic_handler::set::{{closure}}::hb69c32aff36c2baf (0x107e98491)
   3: std::panicking::rust_panic_with_hook::hf0bb129ab1b15fd6 (0x1080281c1)
   4: std::panicking::continue_panic_fmt::he3c165de25d290dd (0x108027c0d)
   5: rust_begin_unwind (0x108027af9)
   6: core::panicking::panic_fmt::h7c1b013b06f96653 (0x108048ce2)
   7: core::option::expect_failed::h5dfc1e5f41d6b78b (0x108048d4e)
   8: std::time::Instant::duration_since::h50ac53a967fd5b9f (0x108024a83)
   9: <std::time::Instant as core::ops::arith::Sub>::sub::hfd4386b97c7d8dd4 (0x108024d15)
  10: substrate_consensus_babe::median_algorithm::h2c41b2026d2eb6e8 (0x107477999)
  11: <substrate_consensus_babe::BabeVerifier<C> as substrate_consensus_common::import_queue::Verifier<B>>::verify::hfa50f7fc9cbd6dcc (0x10740c4d2)
  12: substrate_consensus_common::import_queue::import_single_block::h43c20dbcb27f636a (0x10731f394)
  13: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h23ff16bbaa94149d (0x107166c1c)
  14: futures_util::future::chain::Chain<Fut1,Fut2,Data>::poll::h04c264d8ce140dad (0x1072ff56f)
  15: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h405d392f05aa6571 (0x107167046)
  16: futures_executor::thread_pool::PoolState::work::hb214877c127ab0b7 (0x107e63774)
  17: std::sys_common::backtrace::__rust_begin_short_backtrace::hccd85cddaf6de1cb (0x107e656a4)
  18: std::panicking::try::do_call::h9e650398df6af551 (0x107e60b90)
  19: __rust_maybe_catch_panic (0x10803085f)
  20: core::ops::function::FnOnce::call_once{{vtable.shim}}::hfa585214ef494819 (0x107e62717)
  21: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h0cbb321164b22922 (0x108015c4e)
  22: std::sys::unix::thread::Thread::new::thread_start::hcd6fd4281f489166 (0x10802fdde)
  23: _pthread_body (0x7fff7134b661)
  24: _pthread_start (0x7fff7134b50d)

Thread 'import-queue-worker-0' panicked at 'supplied instant is later than self', src/libcore/option.rs:1034

commitId：f8c05eb36ea0e7228a1e368a9b1f37a2293d11a5

### PR DESCRIPTION
**Pull request by andresilva**
The median calculation that is done to figure out at what time the current slot should start (i.e. offset) is currently not properly implemented. Since it is currently unused I have removed the call from verify to it to avoid any issues. I have also fixed an issue that caused it to panic.

Fixes #3248.

### CODE REVIEW

**Comment by andresilva** [comment]
I have also removed annoying forbid/deny clauses.

**Comment by andresilva** [comment]
Reverted removal of forbid/deny clauses to avoid conflicting with #3213.

File: core/consensus/babe/src/lib.rs [hunk 1]
```diff
@@ -19,7 +19,6 @@
 //! BABE (Blind Assignment for Blockchain Extension) consensus in Substrate.
 
 #![forbid(unsafe_code, missing_docs, unused_must_use, unused_imports, unused_variables)]
```
Comment (bkchr) [inline core/consensus/babe/src/lib.rs]:
```suggestion
#![forbid(unsafe_code, missing_docs)]
```

Comment (andresilva) [reply core/consensus/babe/src/lib.rs]: Originally I removed all forbid/deny but since Gav did the same in #3213 I reverted to avoid conflicts. The only thing I removed `forbid(unused_code)` was necessary to make this PR compile.

**Comment by andresilva** [comment]
@DemiMarie-parity https://github.com/paritytech/substrate/pull/3251/commits/a18036507785277a6ab644a0e0bf3cebdca3da3b (see #3248 as well).
