### PR TITLE
Fix flaky test

### LINKED ISSUE #9728: Test `fallback_name_working` is flaky
```
---- service::tests::fallback_name_working stdout ----
thread 'service::tests::fallback_name_working' panicked at 'assertion failed: `(left == right)`
  left: `"//test-protocol-name/transactions/1"`,
 right: `"/new-shiny-protocol-that-isnt-PROTOCOL_NAME"`', client/network/src/service/tests.rs:531:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed::inner
   3: core::panicking::assert_failed
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: std::thread::local::LocalKey<T>::with
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: async_io::driver::block_on
   8: std::thread::local::LocalKey<T>::with
   9: async_std::task::builder::Builder::blocking
  10: sc_network::service::tests::fallback_name_working
  11: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
 ```

### PR DESCRIPTION
**Pull request by tomaka**
Fix #9728

### CODE REVIEW

File: client/network/src/service/tests.rs [hunk 1]
```diff
@@ -527,12 +530,13 @@ fn fallback_name_working() {
 		// Wait for the `NotificationStreamOpened`.
 		loop {
 			match events_stream1.next().await.unwrap() {
-				Event::NotificationStreamOpened { protocol, negotiated_fallback, .. } => {
-					assert_eq!(protocol, NEW_PROTOCOL_NAME);
+				Event::NotificationStreamOpened { protocol, negotiated_fallback, .. }
+					if protocol == NEW_PROTOCOL_NAME =>
+				{
```
Comment (tomaka) [inline client/network/src/service/tests.rs:535]: This is the only relevant change of this PR. The rest is `rustfmt`.

**Review by kpp — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by tomaka** [comment]
bot merge

**Comment by bkchr** [comment]
:robot:
