### PR TITLE
srml-contract: test calls not dispatched if tx fails

### LINKED ISSUE #2900: srml-contract: ext_dispatch_call disregards the status of the top-level execution
It seems that calls by `ext_dispatch_call` are dispatched even if the top-level transaction fails. This is not right and we need to dispatch them only if the top-level transaction suceeded.

(However, we still need to dispatch after refunding, not before)

### PR DESCRIPTION
**Pull request by ascjones**
Closes #2900.

This test confirms that it was not a bug in the first place. If the execution traps, then `call` will return here: https://github.com/paritytech/substrate/blob/0ead54732eb44083660aee1778a01adc5173dfb3/srml/contracts/src/exec.rs#L361-L369 and the dispatched calls will not be added to the top level context (and thus not dispatched).

For extra safety we *could* add add an `if let Ok(_) = result` around this block https://github.com/paritytech/substrate/blob/0ead54732eb44083660aee1778a01adc5173dfb3/srml/contracts/src/lib.rs#L435-L438 to make it clearer/safer.

### CODE REVIEW

**Comment by thiolliere** [comment]
yes ok but then the code is confusing to me, those calls and events iteration in lib.rs are useless ?

**Comment by ascjones** [comment]
@thiolliere I've added the check for execution success - which while not strictly necessary does make it clearer

File: srml/contracts/src/tests.rs [hunk 1]
```diff
@@ -522,6 +522,108 @@ fn dispatch_call() {
...
+
+			assert_ok!(Contract::create(
+				Origin::signed(ALICE),
+				100,
+				100_000,
+				HASH_DISPATCH_CALL_THEN_TRAP.into(),
+				vec![],
+			));
+
+			assert_err!(
```
Comment (pepyakin) [inline srml/contracts/src/tests.rs]:
```suggestion
			// Call the newly created contract. The contract is expected to dispatch a call
			// and then trap.
			assert_err!(
```

File: srml/contracts/src/lib.rs [hunk 2]
```diff
@@ -431,11 +431,13 @@ decl_module! {
 			// can alter the balance of the caller.
 			gas::refund_unused_gas::<T>(&origin, gas_meter, imbalance);
 
-			// Dispatch every recorded call with an appropriate origin.
-			ctx.calls.into_iter().for_each(|(who, call)| {
-				let result = call.dispatch(RawOrigin::Signed(who.clone()).into());
-				Self::deposit_event(RawEvent::Dispatched(who, result.is_ok()));
-			});
+			if let Ok(_) = result {
```
Comment (pepyakin) [inline srml/contracts/src/lib.rs]: I think we need the same thing for `fn create`, don't we?

File: srml/contracts/src/lib.rs [hunk 3]
```diff
@@ -431,11 +431,13 @@ decl_module! {
...
+				// Dispatch every recorded call with an appropriate origin.
+				ctx.calls.into_iter().for_each(|(who, call)| {
+					let result = call.dispatch(RawOrigin::Signed(who.clone()).into());
+					Self::deposit_event(RawEvent::Dispatched(who, result.is_ok()));
+				});
+			}
```
Comment (thiolliere) [inline srml/contracts/src/lib.rs]: I'm not sure that helps, I mean this calls and events are always empty at this stage ? 
If those are for obvious reason empty it is better not to process them and write a comment or an assert with the proof.
I should read the code again to see why.

File: srml/contracts/src/lib.rs [hunk 4]
```diff
@@ -431,11 +431,13 @@ decl_module! {
...
 			gas::refund_unused_gas::<T>(&origin, gas_meter, imbalance);
 
-			// Dispatch every recorded call with an appropriate origin.
-			ctx.calls.into_iter().for_each(|(who, call)| {
-				let result = call.dispatch(RawOrigin::Signed(who.clone()).into());
-				Self::deposit_event(RawEvent::Dispatched(who, result.is_ok()));
-			});
+			if let Ok(_) = result {
+				// Dispatch every recorded call with an appropriate origin.
+				ctx.calls.into_iter().for_each(|(who, call)| {
```
Comment (jimpo) [inline srml/contracts/src/lib.rs]: Is there a reason this has to be below `refund_unused_gas` and can't go in the `if` block above immediately after the events are deposited?

Comment (ascjones) [reply srml/contracts/src/lib.rs]: Not sure. Perhaps @pepyakin or @thiolliere can elaborate?

> (However, we still need to dispatch after refunding, not before)

File: srml/contracts/src/lib.rs (hunk 3 above)
Comment (ascjones) [reply srml/contracts/src/lib.rs]: So you mean an assert like: 
```
assert!(false == result.is_err() && !ctx.calls.is_empty(), 
    "Contract execution failed, no calls are dispatched")
```

File: srml/contracts/src/lib.rs (hunk 4 above)
Comment (thiolliere) [reply srml/contracts/src/lib.rs]: I would say that as gas is not used anymore its better that the caller got its money back before processing the logic of those calls. They might want to make use of it and there is no reason for us to hold it longer

File: srml/contracts/src/lib.rs (hunk 3 above)
Comment (thiolliere) [reply srml/contracts/src/lib.rs]: I was confused and thoughts that calls were empty on success as well. but no indeed.

I finally understand the code :-), if a failing call is guarantee to not change overlay, events and calls, then this could be done:
```diff
iff --git a/srml/contracts/src/lib.rs b/srml/contracts/src/lib.rs
index 58575ef89..e7cd79f37 100644
--- a/srml/contracts/src/lib.rs
+++ b/srml/contracts/src/lib.rs
@@ -412,18 +412,16 @@ decl_module! {
 
 			let result = ctx.call(dest, value, &mut gas_meter, &data, exec::EmptyOutputBuf::new());
 
-			if let Ok(_) = result {
-				// Commit all changes that made it thus far into the persistent storage.
-				DirectAccountDb.commit(ctx.overlay.into_change_set());
-
-				// Then deposit all events produced.
-				ctx.events.into_iter().for_each(|indexed_event| {
-					<system::Module<T>>::deposit_event_indexed(
-						&*indexed_event.topics,
-						<T as Trait>::Event::from(indexed_event.event).into(),
-					);
-				});
-			}
+			// Commit all changes that made it thus far into the persistent storage.
+			DirectAccountDb.commit(ctx.overlay.into_change_set());
+
+			// Then deposit all events produced.
+			ctx.events.into_iter().for_each(|indexed_event| {
+				<system::Module<T>>::deposit_event_indexed(
+					&*indexed_event.topics,
+					<T as Trait>::Event::from(indexed_event.event).into(),
+				);
+			});
 
 			// Refund cost of the unused gas.
 			//

+ same in other method
```

but I'm ok with this PR as it is now, it is a double check but it probably doesn't harm.

Comment (thiolliere) [reply srml/contracts/src/lib.rs]: oh I saw the revert but I might havn't express my precisely I meant either we get rid of all `if let Ok(_)` as all context is empty (overlay, events and calls) either we double check all of them. But I don't know what is prefered

File: srml/contracts/src/lib.rs (hunk 4 above)
Comment (jimpo) [reply srml/contracts/src/lib.rs]: That would be a nice comment to add to the source. :-)

File: srml/contracts/src/lib.rs (hunk 3 above)
Comment (pepyakin) [reply srml/contracts/src/lib.rs]: I am not sure if that worth changing now. We are about to make a refactor of the executive module anyway.

Comment (ascjones) [reply srml/contracts/src/lib.rs]: So are we happy with this PR just to be the test to prove that this is not a bug?

Comment (pepyakin) [reply srml/contracts/src/lib.rs]: The test is the primary thing, I'd say, yes.

Comment (ascjones) [reply srml/contracts/src/lib.rs]: Sounds like an approval to me :)

**Comment by pepyakin** [comment]
Merging this without version bump since this doesn't actually alter any on-chain code.
