### PR TITLE
Try-runtime Revamp and Facelift

### LINKED ISSUE #12044: remote-externalities: parallelize value download
The way this tool works now is that we first download all of they keys, in a paginated way. Then, we start requesting the values of the corresponding keys in batches. My guess is that this process can still be optimized by parallelizing the requests.

### LINKED ISSUE #12130: `TryState`: automatically execute after each migration
Not automatically yet, I think it is okay to leave it up to the pallet to do so, which is what you are seeing here.

We can make a follow-up and once `try_state` is a bit more standard, make it execute upon all migrations.

_Originally posted by @kianenigma in https://github.com/paritytech/substrate/pull/10174#discussion_r956728563_

---

Ofc, IFF `feature = try-runtime`

### LINKED ISSUE #12156: `try-runtime` - specifying runtime & cutting off unnecessary configuration burden
I'm trying to change the way how local runtime is passed. Currently, we must pass path to a chainspec, build genesis storage and retrieve `:CODE:` from there. Not only it is the second time we build the storage (the first time is in `create_runner` function in the client code), but we also do it completetly unnecessary.

I would like to propose two things:
  1) we add a new shared parameter for all `try-runtime` subcommands: `enum Runtime`, which has three variants: `Remote | Native | Local(Pathbuf)` with natural meaning:
  	- `Remote`: we use `Wasm` execution with the runtime included in the scraped storage (and we do not have to overwrite anything)
  	- `Native`: we use `Native` execution with the code from the binary that is actually running (in case of spec-* mismatch we can panic)
  	- `Local(Pathbuf)`: we use `Wasm` execution with the runtime read from local file at `Pathbuf` (which requires overwriting `:CODE:` in the scraped storage)

Of course, not every variant makes sense with every subcommand, but having a common way of specifying runtime + variant checks seems to be more friendly and straightforward than implicit, non-consistent approach.

  2) we completely get rid of using `sc_service::Configuration` and `sc_cli::SharedParams` in `try-runtime` - if I understand correctly, the only essential information that we use from it are: `default_heap_pages`, `max_runtime_instances` and `runtime_cache_size`. We could 'move' these three arguments to `SharedParams` and stop using both concepts at all. However, the problem is not gone: `TryRuntimeCmd` will be still launched using `sc::cli::Runner`, which requires `sc_service::Configuration` object. If I'm not mistaken, `try-runtime` is a command that needs nothing more than an async environment (with some logging configured etc), and the whole overhead with `sc_service::Configuration` is unneeded and possibly misleading.

Unfortunately, I don't see any other way than providing some additional simplified/generalized methods / structs to the client like:
```rust
fn create_simple_runner<T: ...>(&self, command: &T) -> error::Result<SimpleRunner<Self>> {
	let tokio_runtime = build_runtime()?;
	command.generalized_init(&Self::support_url(), &Self::impl_version())?;
	SimpleRunner::new(tokio_runtime)
}
```
so that commands like `TryRuntime` can be launched like:
```rust
#[cfg(feature = "try-runtime")]
Some(Subcommand::TryRuntime(cmd)) => {
	let runner = cli.create_simple_runner(cmd)?;
	runner.async_run(|| {
		let tokio_handle = ...;
		let task_manager =
			sc_service::TaskManager::new(tokio_handle, no_prometheus_registry)
				.map_err(|e| sc_cli::Error::Service(...))?;
		Ok((cmd.run::<Block, service::ExecutorDispatch>(), task_manager))
	})
}
```

As long as the former point seems to be quite feasible, I have many doubts with the latter one. In particular, I don't know exactly how much effort it requires.

@kianenigma please take a look

### LINKED ISSUE #12194: try-runtime: make snapshot file contain more data
... such that the `execute-block` command is 100% reproducible with a snapshot file.

Currently, a snapshot file only contains the state. For operations such as execute-block or offchain-worker, we also need the parent hash, block data, etc.

### LINKED ISSUE #12195: try-runtime: fix proof size
as spoken with Alan from moonbeam, the current proof size that's reported in the `on-runtime-upgrade` is not correct. IIRC, it had something to do with reading/writing the code, which is not on-par with reality. 

All in all, make sure that the proof size reported by try-runtime is 100% accurate.

### PR DESCRIPTION
**Pull request by kianenigma**
# Changelog 

## remote-externalities

* (CHANGED) `pallets` in `OnlineConfig` no longer has the interpretation of an empty list implying everything. `pallets: vec![foo]` is simply a shorthand for injecting `twox(foo)` into the list of hashed prefixes that we want to scrape. To remain backwards compatible in most cases, if the list of hashed prefixed is empty, we inject `vec![]` into it, which implies "download everything".
* (CHANGED) snapshot format has changed and now is a single file, and contains block hash as well. closes https://github.com/paritytech/substrate/issues/12194
* (ADDED) Value download is multi-threaded for both the main and child-tree. Significantly improving performance. The number of threads used can be set in `OnlineConfig`. closes https://github.com/paritytech/substrate/issues/12044
* (ADDED) `state_version`, if read from remote, will by default be set to whatever the remote node has. If snapshot is created, the state_version is kept and restored. The user can still overwrite this, but there's really no reason to use this option. 

## Try-runtime CLI

* (ADDED) new `create_snapshot` command. Should help us with https://github.com/paritytech/devops/issues/2083 and such. 
* (ADDED) the `state_version` of the local node and the remote node are checked.
* (CHANGED) on-runtime-upgrade can now optionally (`--checks`) call into `pre_upgrade`/`post_upgrade`/`try_state` hooks. The old behavior was basically passing in `--checks` by default, no longer the case. closes https://github.com/paritytech/substrate/issues/12195 and closes https://github.com/paritytech/substrate/issues/12130. 
* (ADDED) everything in try-runtime CLI now uses `WasmExecutor`. Thus, we can specify `enum Runtime { existing, path }` which simplifies a lot of things. Closes https://github.com/paritytech/substrate/issues/12156
* Make `execute-block` more reproducible.  

The main change that needs update in tools and CLIs is that a wasm file compiled with `feature=try-runtime` need to be provided separately. So a "test migration" process is as follows: 

```
cargo build --release --feature try-runtime 
cargo run --release --feature try-runtime try-runtime --runtime ./target/release/... -lruntime=debug on-runtime-upgrade ...
cargo clean 
```

Also be aware of: 

> * (CHANGED) on-runtime-upgrade can now optionally (`--checks`) call into `pre_upgrade`/`post_upgrade`/`try_state` hooks. The old behavior was basically passing in `--checks` by default, no longer the case.

and if you want to do. full migration testing, run with `--checks`, and without it if you prefer having a more accurate sense of PoV. 

---

polkadot companion: https://github.com/paritytech/polkadot/pull/6187
- [x] cumulus companion: 
- [x] Update docs.

### CODE REVIEW

**Comment by kianenigma** [comment]
from @ggwpez 

> Do you think we could add some state-diff to the try-runtime which outputs which keys got modified by a migration?  
> Some summary like: The following pallets had these storage elements touched y times: …

**Comment by crystalin** [comment]
Adding my request:
We would want to re-use try-runtime in the process of testing more manual element. For exemple, to demonstrate what a new pallet or feature would do on an existing chain state, or to verify the impact of a given change would be on multiple blocks.
For that, the try-runtime could support a command `fork` which would basically start producing blocks on top of the best block and have some checks (like authoring) disabled to allow the node to keep producing.

**Comment by librelois** [comment]
It would be nice to have an option in `follow-chain` that allows to lazily download the onchain storage, download a key/value only when we need it in the block execution.
The problem with `follow-chain` at the moment is that it downloads the whole storage while a large part of it might not be needed to execute the blocks.

**Comment by crystalin** [comment]
@kianenigma also it needs to improve the memory footprint, currently I can't try-runtime execute block with some of our Moonbeam networks, using a 2.5GB state (12M keys, https://alan-stuff.s3.amazonaws.com/3069691.top) takes > 64GB

**Comment by kianenigma** [comment]
> It would be nice to have an option in `follow-chain` that allows to lazily download the onchain storage, download a key/value only when we need it in the block execution. The problem with `follow-chain` at the moment is that it downloads the whole storage while a large part of it might not be needed to execute the blocks.

Indeed, this will be addressed.

**Comment by kianenigma** [comment]
> @kianenigma also it needs to improve the memory footprint, currently I can't try-runtime execute block with some of our Moonbeam networks, using a 2.5GB state (12M keys, https://alan-stuff.s3.amazonaws.com/3069691.top) takes > 64GB

Lazy download should also solve this, no?

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/how-to-make-a-fuzz-er-for-wasm-runtime/936/2

**Comment by crystalin** [comment]
@kianenigma additionally, it would be great if we could spin-up try-runtime from a base-path instead of retrieving the keys from remote server. (I'd also like to automate a `perf record` execution try-runtime but it is hard because the try-runtime spends like 1h to inject the keys :/ )

**Comment by crystalin** [comment]
@kianenigma or even nicer, allowing the try-runtime execute-block from a PoV :)

**Comment by kianenigma** [comment]
Okay, so I have done a bit of work on on-demand download. It kinda works, but you can't get any proofs of course. Or let's put it this way: even if it does generate a proof for you, you should not trust it :) it is probably not accurate. 

I am have a strong feeling that this will also have its limitations, because you HAVE to do the RPC calls sequentially. I suppose things like iterating a map that has a lot of keys will be super slow in this on-demand mode.

Nonetheless, I hope this, combined with all the parallelization work that I have added to this PR improves the overall usability.

> but it is hard because the try-runtime spends like 1h to inject the keys :/ )

I will improve this by making this in-memory inserting happen while values are being downloaded :) 

> using a 2.5GB state (12M keys, https://alan-stuff.s3.amazonaws.com/3069691.top) takes > 64GB

This is harder to fix, and probably not in the scope of this PR, as try-runtime is entirely assumed to live in memory for the time being. The only way to fix this is to point it to a base path. I will explore this, but not now. 

@crystalin let me know if you have any opinions about any of this.

**Comment by crystalin** [comment]
@kianenigma that's great to start. Can we test it ?
Concerning hte Memory > 64GB, I think it can be improved, because this is just due to the insertion, once passed the insertion, the memory drops from 80GB to something like 3-4GB

**Comment by kianenigma** [comment]
comparing fetching all keys form a local node.

current status of the branch as of [ee0130c](https://github.com/paritytech/substrate/pull/12537/commits/ee0130ca585789b0eb4bc69ef3bc67f54bb6a089)

```
running 1 test
test remote_tests::can_fetch_all ... 2022-11-13T21:31:41.739015Z  INFO remote-ext: since no at is provided, setting it to latest finalized head, 0xa2cc7a9259d1e4c03c6627472f878f26697d68d71dfa5f47aa95724e93faf7aa
2022-11-13T21:31:41.739033Z  INFO remote-ext: since no prefix is filtered, the data for all pallets will be downloaded
2022-11-13T21:31:41.739039Z  INFO remote-ext: scraping key-pairs from remote @0xa2cc7a9259d1e4c03c6627472f878f26697d68d71dfa5f47aa95724e93faf7aa
2022-11-13T21:31:41.740253Z  INFO remote-ext: Querying a total of 28 keys, took 0s to fetch keys, splitting among 8 threads, 4 keys per thread
2022-11-13T21:31:41.748374Z  INFO remote-ext: adding data for hashed prefix: 3a6368696c645f73746f726167653a64656661756c743a, took 0s
2022-11-13T21:32:15.889162Z  INFO remote-ext: Querying a total of 1747018 keys, took 34s to fetch keys, splitting among 8 threads, 218378 keys per thread
2022-11-13T21:32:49.209805Z  INFO remote-ext: adding data for hashed prefix: , took 67s
2022-11-13T21:32:49.464542Z  INFO remote-ext: 👩‍👦 scraping child-tree data from 56 top keys, split among 8 threads, 7 top keys per thread
2022-11-13T21:32:55.617117Z  INFO remote-ext: injecting a total of 1747046 top keys
2022-11-13T21:33:31.054103Z  INFO remote-ext: injecting a total of 371982 child keys
2022-11-13T21:33:42.238466Z  INFO remote-ext: initialized state externalities with storage root 0x05594107185cbf998ef05f77560326b465e5c0c2aa5d8ff0290a369e3fcceb84 and state_version V0
ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 11 filtered out; finished in 125.56s
```

After the latest commit that makes writes to `ext` concurrent: 
```
2022-11-13T21:34:05.487093Z  INFO remote-ext: since no prefix is filtered, the data for all pallets will be downloaded
2022-11-13T21:34:05.487536Z  INFO remote-ext: scraping key-pairs from remote at block height 0x86a9d209dc4c74502ae228147a188a7387230fc63a65ca86c3474d7f1094620d
2022-11-13T21:34:05.488524Z  INFO remote-ext: Querying a total of 28 keys, took 0s to fetch keys, splitting among 8 threads, 4 keys per thread
2022-11-13T21:34:05.496413Z  INFO remote-ext: adding data for hashed prefix: 3a6368696c645f73746f726167653a64656661756c743a, took 0s
2022-11-13T21:34:40.542436Z  INFO remote-ext: Querying a total of 1747312 keys, took 35s to fetch keys, splitting among 8 threads, 218414 keys per thread
2022-11-13T21:35:21.298733Z  INFO remote-ext: adding data for hashed prefix: , took 75s
2022-11-13T21:35:21.364353Z  INFO remote-ext: 👩‍👦 scraping child-tree data from 56 top keys, split among 8 threads, 7 top keys per thread
2022-11-13T21:35:32.909822Z  INFO remote-ext: initialized state externalities with storage root 0x4806bf9d774d6b61168cab47ea618f2cb7f68572d85c5266d3c11625bd741d33 and state_version V0
ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 11 filtered out; finished in 92.54s
```

File: frame/executive/src/lib.rs [hunk 1]
```diff
@@ -286,8 +284,20 @@ where
...
-	pub fn try_runtime_upgrade() -> Result<frame_support::weights::Weight, &'static str> {
-		let weight = Self::execute_on_runtime_upgrade();
+	pub fn try_runtime_upgrade(
+		checks: bool,
+	) -> Result<frame_support::weights::Weight, &'static str> {
+		let weight =
+			<(COnRuntimeUpgrade, AllPalletsWithSystem) as OnRuntimeUpgrade>::try_on_runtime_upgrade(
+				checks,
+			);
+		if checks {
```
Comment (kianenigma) [inline frame/executive/src/lib.rs:294]: cc @ggwpez

**Comment by crystalin** [comment]
I don't know how you thought about doing the lazy loading. But ideally, you would run the block to know which data to load and then reexecute it once all the data is local (so that doing perf on it would not be impacted by the lazy loading)

File: utils/frame/remote-externalities/src/lib.rs [hunk 2]
```diff
@@ -112,13 +147,19 @@ impl Transport {
...
+	fn from(uri: &str) -> Self {
+		Transport { uri: Some(uri.to_string()), remote_client: None }
 	}
 }
 
 impl From<Arc<WsClient>> for Transport {
-	fn from(client: Arc<WsClient>) -> Self {
-		Transport::RemoteClient(client)
+	fn from(_: Arc<WsClient>) -> Self {
+		unimplemented!("we should not allow this. any client must be first built with a uri");
```
Comment (pmikolajczyk41) [inline utils/frame/remote-externalities/src/lib.rs:162]: question: Why? And why do we have this `impl` then?

Also, it seems like we can simplify `Transport`:
 - single constructor / conversion from `AsRef<str>`
 - deref / explicit downcasting to `Option<WsClient>`
 - no public fields
 - getter for the client (+ maybe just informational for uri / custom `Debug` impl)

File: utils/frame/remote-externalities/src/lib.rs [hunk 3]
```diff
@@ -167,6 +222,12 @@ impl<B: BlockT> From<String> for OnlineConfig<B> {
 	}
 }
 
+impl<B: BlockT> From<&str> for OnlineConfig<B> {
```
Comment (pmikolajczyk41) [inline utils/frame/remote-externalities/src/lib.rs:225]: suggestion: similar note with `AsRef<str>`

File: utils/frame/remote-externalities/src/lib.rs [hunk 4]
```diff
@@ -320,72 +382,147 @@ where
...
-			let batch = chunk_keys
-				.iter()
-				.cloned()
-				.map(|key| ("state_getStorage", rpc_params![key, at]))
-				.collect::<Vec<_>>();
+		let keys =
+			time_block!("rpc_get_keys_paged", { self.rpc_get_keys_paged(prefix, at).await? });
+		let client = self.as_online().transport.remote_client.clone().unwrap();
+		let thread_chunk_size =
+			((keys.len() + self.as_online().threads - 1) / self.as_online().threads).max(1);
```
Comment (pmikolajczyk41) [inline utils/frame/remote-externalities/src/lib.rs:399]: suggestion: just to avoid strange failure - `saturating_div`?

File: utils/frame/remote-externalities/src/lib.rs [hunk 5]
```diff
@@ -320,72 +382,147 @@ where
...
+								(key.clone().0, value.0)
+							})
+							.collect::<Vec<_>>();
+
+						// send this batch to the main thread to start inserting.
+						thread_sender.send(Message::Batch(batch_kv)).unwrap();
+					}
+
+					thread_sender.send(Message::Terminated).unwrap();
+					thread_key_values
```
Comment (pmikolajczyk41) [inline utils/frame/remote-externalities/src/lib.rs:481]: question: you've lost me here; why do we return this data? haven't we sent it all already?

File: utils/frame/try-runtime/cli/src/lib.rs [hunk 6]
```diff
@@ -457,130 +527,153 @@ pub enum State {
...
+					at,
+					transport: uri.to_owned().into(),
+					state_snapshot: None,
+					pallets: pallet.clone(),
+					child_trie: *child_tree,
+					hashed_keys: vec![
+						// we always download the code, but we almost always won't use it, based on
+						// `Runtime`.
+						well_known_keys::CODE.to_vec(),
+						// we will always download this key, since it helps detect if we should do
```
Comment (pmikolajczyk41) [inline utils/frame/try-runtime/cli/src/lib.rs:570]: question: where do we actually use it?

File: utils/frame/try-runtime/cli/src/lib.rs [hunk 7]
```diff
@@ -457,130 +527,153 @@ pub enum State {
...
+			.execute_with(|| sp_io::storage::get(well_known_keys::CODE))
+			.expect("':CODE:' is always downloaded in try-runtime-cli; qed");
+
+		// then, we replace the code based on what the CLI wishes.
+		let maybe_code_to_overwrite = match shared.runtime {
+			Runtime::Local => Some(
+				config
+					.chain_spec
+					.build_storage()
+					.unwrap()
```
Comment (pmikolajczyk41) [inline utils/frame/try-runtime/cli/src/lib.rs:603]: question: this is still suboptimal, right? especially building the whole unnecessary storage; tbh I don't see any gain of keeping `Runtime::Local` when you can just point to a compiled wasm blob

File: bin/node/cli/Cargo.toml [hunk 8]
```diff
@@ -58,6 +58,7 @@ sp-keystore = { version = "0.12.0", path = "../../../primitives/keystore" }
 sp-consensus = { version = "0.10.0-dev", path = "../../../primitives/consensus/common" }
 sp-transaction-pool = { version = "4.0.0-dev", path = "../../../primitives/transaction-pool" }
 sp-transaction-storage-proof = { version = "4.0.0-dev", path = "../../../primitives/transaction-storage-proof" }
+sp-io = { path = "../../../primitives/io" }
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply bin/node/cli/Cargo.toml:61]: I drop them intentionally, because if you important locally, version is just pain and no benefit.

File: primitives/storage/src/lib.rs [hunk 9]
```diff
@@ -407,6 +407,7 @@ impl ChildTrieParentKeyId {
 /// V0 and V1 uses a same trie implementation, but V1 will write external value node in the trie for
 /// value with size at least `TRIE_VALUE_NODE_THRESHOLD`.
 #[derive(Debug, Clone, Copy, Eq, PartialEq)]
+#[cfg_attr(feature = "std", derive(Encode, Decode))]
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply primitives/storage/src/lib.rs:410]: The wasm size is indeed the main reason.

[the remark this answers is not in the document]
Comment (pmikolajczyk41) [reply primitives/storage/src/lib.rs:410]: is there any official policy here? e.g. to always put `codec` derivation under `std` feature? 

also, afaik, in Rust binary unused code will be pruned; but do you know what's happening for wasm? does it differ between compact and standard?

File: bin/node/cli/Cargo.toml (hunk 8 above)
[the remark this answers is not in the document]
Comment (pmikolajczyk41) [reply bin/node/cli/Cargo.toml:61]: do you think that it would be okay to remove these version markers from all Cargo.tomls?

File: frame/try-runtime/src/lib.rs [hunk 10]
```diff
@@ -33,7 +33,11 @@ sp_api::decl_runtime_apis! {
...
 		/// Returns the consumed weight of the migration in case of a successful one, combined with
 		/// the total allowed block weight of the runtime.
-		fn on_runtime_upgrade() -> (Weight, Weight);
+		///
+		/// If `checks` is `true`, `pre_migrate` and `post_migrate` of each migration and
+		/// `try_state` of all pallets will be executed. Else, no. If checks are executed, the PoV
+		/// tracking is likely inaccurate.
+		fn on_runtime_upgrade(checks: bool) -> (Weight, Weight);
 
 		/// Execute the given block, but don't check that its state root matches that of yours.
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/try-runtime/src/lib.rs:42]: `state_root_check` is not used and is not relevant here. In all cases we don't check any root in this function.

File: frame/support/src/traits/hooks.rs [hunk 11]
```diff
@@ -136,13 +136,42 @@ pub trait OnRuntimeUpgrade {
...
+			Some(state)
+		} else {
+			None
+		};
+
+		let weight = Self::on_runtime_upgrade();
+
+		if checks {
+			let _guard = frame_support::StorageNoopGuard::default();
+			// we want to panic if any checks fail right here right now.
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/support/src/traits/hooks.rs:156]: We could, but I am not a fan of it. I think having a backtrace that tells us exactly this line of code paniced is better than bubbling the error up and needing to deal with it. Ofc, this is only a valid argument because this is a testing CLI.

File: frame/support/src/traits/hooks.rs [hunk 12]
```diff
@@ -136,13 +136,42 @@ pub trait OnRuntimeUpgrade {
...
 	}
 
+	/// Same as [`on_runtime_upgrade`], but perform the optional [`pre_upgrade`] and
+	/// [`post_upgrade`] as well.
+	#[cfg(feature = "try-runtime")]
+	fn try_on_runtime_upgrade(checks: bool) -> Weight {
+		let maybe_state = if checks {
+			let _guard = frame_support::StorageNoopGuard::default();
+			let state = Self::pre_upgrade().unwrap();
+			drop(_guard);
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/support/src/traits/hooks.rs:146]: Sounds good, but happy with the current state for now :)

File: frame/support/src/traits/hooks.rs [hunk 13]
```diff
@@ -136,13 +136,42 @@ pub trait OnRuntimeUpgrade {
...
+
 	/// Execute some pre-checks prior to a runtime upgrade.
 	///
 	/// Return a `Vec<u8>` that can contain arbitrary encoded data (usually some pre-upgrade state),
 	/// which will be passed to `post_upgrade` after upgrading for post-check. An empty vector
 	/// should be returned if there is no such need.
 	///
 	/// This hook is never meant to be executed on-chain but is meant to be used by testing tools.
+	///
+	/// This hook must not write to any state, as it would make the main `on_runtime_upgrade` path
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/support/src/traits/hooks.rs:173]: Done.

File: frame/staking/src/pallet/impls.rs [hunk 14]
```diff
@@ -1690,7 +1693,7 @@ impl<T: Config> Pallet<T> {
 		<Nominators<T>>::iter()
 			.filter_map(
 				|(nominator, nomination)| {
-					if nomination.submitted_in > era {
+					if nomination.submitted_in < era {
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/staking/src/pallet/impls.rs:1696]: I totally agree, and I find them very confusing as well :(

File: frame/staking/src/pallet/impls.rs [hunk 15]
```diff
@@ -1634,9 +1634,9 @@ impl<T: Config> Pallet<T> {
 		ensure!(
 			T::VoterList::iter()
 				.all(|x| <Nominators<T>>::contains_key(&x) || <Validators<T>>::contains_key(&x)),
-			"VoterList contains non-nominators"
+			"VoterList contains non-staker"
 		);
-		T::VoterList::try_state()?;
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/staking/src/pallet/impls.rs:1639]: Because in most cases is a different pallet, which will have its own opportunity of calling its `try_state`. 

Note that this is not a good approach, as we cannot know this (`VoterList` is a new pallet) in all cases. For now I removed it because the `try_state` of staking was already taking too long.

File: frame/executive/src/lib.rs [hunk 16]
```diff
@@ -286,8 +284,20 @@ where
 	/// Execute all `OnRuntimeUpgrade` of this runtime, including the pre and post migration checks.
 	///
 	/// This should only be used for testing.
-	pub fn try_runtime_upgrade() -> Result<frame_support::weights::Weight, &'static str> {
-		let weight = Self::execute_on_runtime_upgrade();
+	pub fn try_runtime_upgrade(
+		checks: bool,
+	) -> Result<frame_support::weights::Weight, &'static str> {
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/executive/src/lib.rs:289]: It is not in `#[feature = try-runtime]`

File: frame/executive/src/lib.rs [hunk 17]
```diff
@@ -286,8 +284,20 @@ where
...
+		let weight =
+			<(COnRuntimeUpgrade, AllPalletsWithSystem) as OnRuntimeUpgrade>::try_on_runtime_upgrade(
+				checks,
+			);
+		if checks {
+			<AllPalletsWithSystem as frame_support::traits::TryState<System::BlockNumber>>::try_state(
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/executive/src/lib.rs:295]: yeah great point, will add and document it.

File: frame/executive/src/lib.rs [hunk 18]
```diff
@@ -286,8 +284,20 @@ where
...
+				frame_system::Pallet::<System>::block_number(),
+				frame_try_runtime::TryStateSelect::All,
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/executive/src/lib.rs:297]: Yeah I presume so, for now I just kept it simpler.

File: frame/executive/src/lib.rs [hunk 19]
```diff
@@ -286,8 +284,20 @@ where
...
+	pub fn try_runtime_upgrade(
+		checks: bool,
+	) -> Result<frame_support::weights::Weight, &'static str> {
+		let weight =
+			<(COnRuntimeUpgrade, AllPalletsWithSystem) as OnRuntimeUpgrade>::try_on_runtime_upgrade(
+				checks,
+			);
+		if checks {
+			<AllPalletsWithSystem as frame_support::traits::TryState<System::BlockNumber>>::try_state(
+				frame_system::Pallet::<System>::block_number(),
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/executive/src/lib.rs:296]: the documentation of `OnRuntimeUpgrade::on_runtime_upgrade` refers to the call path of `OnRuntimeUpgrade::on_runtime_upgrade` in real chains. Here, everything is rather different. Whether `block_number` exists or not depends on whether `remote-externalities` is initialized with or without it on the CLI side. 

Alternatively, we can make sure we always read this storage item, similar to `LastRuntimeUpgrade`: 
 

As a side note, the fact that `try_state` accepts a block number is just a convention. I am not sure why we actually need it, it is almost certainly not going to be used.

File: utils/frame/remote-externalities/src/lib.rs (hunk 3 above)
Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:225]: my bad 🤦

File: utils/frame/remote-externalities/src/lib.rs (hunk 4 above)
Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:399]: what I actually need is a simple `div_ceil`, not sure how `saturating_div` helps with that?

File: utils/frame/remote-externalities/src/lib.rs (hunk 5 above)
Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:481]: We still need to bubble it up to write it to a file, if desired. 

There's a not acknowledging that this is not so great.

I think a nice abstraction would be to pass in a `Optiom<WriteStream>` to this function. Similar to updating `pending_ext`, we also write to this. If a cache file is needed, this will be `Some(_)`, else `None`.

But I am not sure how to implement that efficiently either, so I timed the execution, and it turned out that returning this data for caching purposes is not a big deal, so I opted for this for now.

File: utils/frame/remote-externalities/src/lib.rs [hunk 20]
```diff
@@ -649,27 +780,143 @@ where
...
-	pub(crate) async fn pre_build(
-		mut self,
-	) -> Result<(TopKeyValues, ChildKeyValues), &'static str> {
-		let mut top_kv = match self.mode.clone() {
-			Mode::Offline(config) => self.load_top_snapshot(&config.state_snapshot.path)?,
-			Mode::Online(_) => {
-				self.init_remote_client().await?;
-				self.load_top_remote_and_maybe_save().await?
-			},
+	pub(crate) async fn load_remote_and_maybe_save(
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:820]: Done, and they should have not been public actually :)

File: utils/frame/try-runtime/cli/src/lib.rs (hunk 6 above)
Comment (kianenigma) [reply utils/frame/try-runtime/cli/src/lib.rs:570]: [It happens inside the runti](https://github.com/paritytech/substrate/blob/dd8a34775aab9b362a5cc7552d5603c2fe812f82/frame/executive/src/lib.rs#L379)

File: utils/frame/try-runtime/cli/src/lib.rs (hunk 7 above)
Comment (kianenigma) [reply utils/frame/try-runtime/cli/src/lib.rs:603]: yeah, let me try the wasm blob approach and if it works, I will just remove it.

File: primitives/runtime/src/generic/unchecked_extrinsic.rs [hunk 21]
```diff
@@ -161,6 +161,22 @@ where
 			None => CheckedExtrinsic { signed: None, function: self.function },
 		})
 	}
+
+	#[cfg(feature = "try-runtime")]
+	fn unchecked_into_checked(
```
Comment (niklasad1) [inline primitives/runtime/src/generic/unchecked_extrinsic.rs:166]: not super happy about having the `try-runtime` leaked into this crate.

Can we make it `unsafe fn into_unchecked()` instead and remove the feature?
Then document that the signature of the transaction is not verified.

Comment (niklasad1) [reply primitives/runtime/src/generic/unchecked_extrinsic.rs:166]: I don't understand why this is needed FWIW.

File: utils/frame/remote-externalities/src/lib.rs [hunk 22]
```diff
@@ -320,72 +350,143 @@ where
...
+		enum Message {
+			Terminated,
+			Batch(Vec<(Vec<u8>, Vec<u8>)>),
+		}
+		let (tx, rx) = std::sync::mpsc::channel::<Message>();
+
+		for thread_keys in keys_chunked {
+			let thread_client = client.clone();
+			let thread_sender = tx.clone();
+			let handle = std::thread::spawn(move || {
```
Comment (niklasad1) [inline utils/frame/remote-externalities/src/lib.rs:389]: I think these spawned threads doesn't really help make thing faster.

As the RPC client has a shared background thread which does the heavy work such spawning threads just to await for some async I/O to become ready seems like a waste.

I guess we could try with `FuturesUnordered/Ordered` here instead.

Comment (niklasad1) [reply utils/frame/remote-externalities/src/lib.rs:389]: The only benefit I can think of is that the batch requests can performed in parallel but for "waiting" for the responses it should help.

I still think awaiting on the responses is bottleneck here...

File: primitives/runtime/src/generic/unchecked_extrinsic.rs (hunk 21 above)
Comment (kianenigma) [reply primitives/runtime/src/generic/unchecked_extrinsic.rs:166]: https://github.com/paritytech/substrate/pull/12537/files#diff-71647e596916530d84fd02546feb833ff703dbf19397d076c499ab7dbf265da2R252 is where this is needed, to disable signature verification.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2100211

File: utils/frame/remote-externalities/src/lib.rs (hunk 22 above)
Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:389]: Yeah my experiments also show that we have not gained much benefit from this. If confirmed, I will revert this part.

Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:389]: Although, the nice thing about threading is that we can write to `pending_ext` little by little, and while downloading is happening, which is know to bring a good amount of improvements.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2115279

File: bin/node/cli/Cargo.toml (hunk 8 above)
[the remark this answers is not in the document]
Comment (kianenigma) [reply bin/node/cli/Cargo.toml:61]: It is an ongoing discussion and beyond my or this PR's scope tbh.

File: primitives/storage/src/lib.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (kianenigma) [reply primitives/storage/src/lib.rs:410]: I think the preferred way is to: if you know it is not needed in the runtime, feature-gate it with `std` to not rely on the compiler optimization.

**Comment by kianenigma** [comment]
Okay so I spent today making the CI mostly happy here, and some final cleanups. 

Ideally, I want 3 reviews here: 

1. @niklasad1 to review the changes in `remote-externalities`
2. @pmikolajczyk41 to review the changes in `try-runtime-cli`
3. @bkchr and/or @ggwpez to review the small changes in `frame/` (executive and support mainly)

File: frame/executive/src/lib.rs [hunk 23]
```diff
@@ -286,9 +322,29 @@ where
...
+			.unwrap();
+		}
+
+		let weight =
+			<(COnRuntimeUpgrade, AllPalletsWithSystem) as OnRuntimeUpgrade>::try_on_runtime_upgrade(
+				checks,
+			);
+
+		if checks {
+			<AllPalletsWithSystem as frame_support::traits::TryState<System::BlockNumber>>::try_state(
```
Comment (ggwpez) [inline frame/executive/src/lib.rs:341]: Could still add a `StorageNoopGuard` here and below.

File: frame/support/src/traits/hooks.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (ggwpez) [reply frame/support/src/traits/hooks.rs:143]: You can do that with `assert_storage_noop!` but I added the guard to have less indentation and to work better for larger code blocks.

**Review by ggwpez — APPROVED** [review]
`frame/` looks good!

File: utils/frame/remote-externalities/src/lib.rs [hunk 24]
```diff
@@ -78,47 +111,32 @@ pub struct OfflineConfig {
...
-			log::debug!(target: LOG_TARGET, "initializing remote client to {:?}", uri);
-
-			let ws_client = ws_client(uri).await.map_err(|e| {
-				log::error!(target: LOG_TARGET, "error: {:?}", e);
-				"failed to build ws client"
-			})?;
-
-			*self = Self::RemoteClient(Arc::new(ws_client))
+		if let Some(uri) = &self.uri {
+			let ws_client = ws_client(uri).await.unwrap();
```
Comment (niklasad1) [inline utils/frame/remote-externalities/src/lib.rs:129]:
```suggestion
			let ws_client = ws_client(uri).await.map_err(|e| {
				log::error!(target: LOG_TARGET, "error: {:?}", e);
				"failed to build ws client"
			})?;
```

File: utils/frame/remote-externalities/src/lib.rs [hunk 25]
```diff
@@ -78,47 +111,32 @@ pub struct OfflineConfig {
 
 /// Description of the transport protocol (for online execution).
 #[derive(Debug, Clone)]
-pub enum Transport {
+pub struct Transport {
 	/// Use the `URI` to open a new WebSocket connection.
-	Uri(String),
+	uri: Option<String>,
```
Comment (niklasad1) [inline utils/frame/remote-externalities/src/lib.rs:116]: why introduce the `Option's`?

File: utils/frame/remote-externalities/src/lib.rs [hunk 26]
```diff
@@ -320,72 +351,147 @@ where
...
-		let client = self.as_online().rpc_client();
-		for chunk_keys in keys.chunks(BATCH_SIZE) {
-			let batch = chunk_keys
-				.iter()
-				.cloned()
-				.map(|key| ("state_getStorage", rpc_params![key, at]))
-				.collect::<Vec<_>>();
+		let keys = self.rpc_get_keys_paged(prefix.clone(), at).await?;
+		let client = self.as_online().transport.remote_client.clone().unwrap();
+		let thread_chunk_size = ((keys.len() + Self::threads() - 1) / Self::threads()).max(1);
```
Comment (niklasad1) [inline utils/frame/remote-externalities/src/lib.rs:366]: move this after the `keys.is_empty()` check or add a comment that is checked below i.e, that we can end-up with `thread_chunk_size == 0`

if you would force `Self::threads()` return `NonZeroUsize` you wouldn't need to add more clarification comments and the `max(1)` is unreachable.

File: utils/frame/remote-externalities/src/lib.rs [hunk 27]
```diff
@@ -462,214 +565,342 @@ where
...
 	///
 	/// `top_kv` need not be only child-bearing top keys. It should be all of the top keys that are
 	/// included thus far.
-	async fn load_child_remote(&self, top_kv: &[KeyValue]) -> Result<ChildKeyValues, &'static str> {
+	///
+	/// This function concurrently populates `pending_ext`. the return value is only for writing to
+	/// cache, we can also optimize further.
+	async fn load_child_remote(
+		&self,
+		top_kv: &Vec<KeyValue>,
```
Comment (niklasad1) [inline utils/frame/remote-externalities/src/lib.rs:583]:
```suggestion
		top_kv: &[KeyValue],
```

File: utils/frame/remote-externalities/src/lib.rs [hunk 28]
```diff
@@ -462,214 +565,342 @@ where
...
+			.filter_map(|(k, _)| is_default_child_storage_key(k.as_ref()).then(|| k.clone()))
 			.collect::<Vec<_>>();
 
+		if child_roots.is_empty() {
+			return Ok(Default::default())
+		}
+
+		// div-ceil simulation.
+		let child_roots_per_thread =
+			((child_roots.len() + Self::threads() - 1) / Self::threads()).max(1);
```
Comment (niklasad1) [inline utils/frame/remote-externalities/src/lib.rs:597]: same here;  if Self::threads() returns `NonZeroUsize` the max could be removed

**Review by pmikolajczyk41 — APPROVED** [review]

File: utils/frame/remote-externalities/src/lib.rs [hunk 29]
```diff
@@ -462,214 +565,342 @@ where
...
+				Ok(thread_child_kv)
+			});
+			handles.push(handle);
 		}
 
+		// first, wait until all threads send a `Terminated` message, in the meantime populate
+		// `pending_ext`.
+		let mut terminated = 0usize;
+		loop {
+			match rx.recv().unwrap() {
```
Comment (niklasad1) [inline utils/frame/remote-externalities/src/lib.rs:677]: in general we shouldn't use anything "blocking" in async fn's as `std::sync::mpsc::Receiver::recv` so would be better to use `futures::channel::mpsc` or some other "async channel"

based on your tests it's probably fine but it could fuck up the `tokio async threadpool`

File: frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr [hunk 30]
```diff
@@ -28,7 +28,7 @@ error[E0277]: the trait bound `Bar: EncodeLike` is not satisfied
              <&[(T,)] as EncodeLike<BinaryHeap<LikeT>>>
              <&[(T,)] as EncodeLike<LinkedList<LikeT>>>
              <&[T] as EncodeLike<Vec<U>>>
-           and 278 others
+           and 279 others
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr:31]: No idea, I just ran stuff locally with `TRYBUILD=overwrite` 🙈

File: frame/try-runtime/src/lib.rs [hunk 31]
```diff
@@ -33,12 +33,22 @@ sp_api::decl_runtime_apis! {
...
 		///
 		/// This is only sensible where the incoming block is from a different network, yet it has
 		/// the same block format as the runtime implementing this API.
 		fn execute_block(block: Block, state_root_check: bool, try_state: TryStateSelect) -> Weight;
+
+		/// A marker trait used just to identify if a runtime has been compiled with
+		/// `feature=try-runtime` or not.
+		///
+		/// It does nothing.
+		fn ping();
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/try-runtime/src/lib.rs:52]: I could call into any of the existing APIs as well, but then I'd have to prepare the correct data. Probably there's a way to check with a wasm executor if a given function name is exposed or not, but I did not go that far.

File: frame/support/src/traits/hooks.rs [hunk 32]
```diff
@@ -136,13 +133,42 @@ pub trait OnRuntimeUpgrade {
...
 	}
 
+	/// Same as `on_runtime_upgrade`, but perform the optional `pre_upgrade` and `post_upgrade` as
+	/// well.
+	#[cfg(feature = "try-runtime")]
+	fn try_on_runtime_upgrade(checks: bool) -> Weight {
+		let maybe_state = if checks {
+			let _guard = frame_support::StorageNoopGuard::default();
+			let state = Self::pre_upgrade().unwrap();
+			drop(_guard);
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply frame/support/src/traits/hooks.rs:143]: I like to be explicit if the `Drop` actually does something 🙈

File: utils/frame/remote-externalities/src/lib.rs (hunk 25 above)
Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:116]: Right, does not make sense 🙈 

Note the main reason I did this is because after creating the ws-client, I want to still know from which uri was used, something that ironically I cannot do with `WsClient`, ergo change to struct.

File: utils/frame/remote-externalities/src/lib.rs [hunk 33]
```diff
@@ -250,20 +275,21 @@ where
 	B::Hash: DeserializeOwned,
 	B::Header: DeserializeOwned,
 {
+	/// Get the number of threads to use.
+	fn threads() -> usize {
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:279]: I see this as temporary given #12869, okay for now IMO.

File: frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr (hunk 30 above)
[the remark this answers is not in the document]
Comment (ggwpez) [reply frame/support/test/tests/pallet_ui/storage_ensure_span_are_ok_on_wrong_gen.stderr:31]: There is `.maintain/update-rust-stable.sh 1.62.1` :sunglasses:

File: utils/frame/remote-externalities/src/lib.rs (hunk 25 above)
Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:116]: But, we won't need any of that anymore because we don't create a new client per thread, so I will revert all these changes.

File: utils/frame/try-runtime/cli/src/lib.rs [hunk 34]
```diff
@@ -457,130 +529,160 @@ pub enum State {
...
+		let mut ext = builder.build().await?;
+		let original_code = ext
+			.execute_with(|| sp_io::storage::get(well_known_keys::CODE))
+			.expect("':CODE:' is always downloaded in try-runtime-cli; qed");
+
+		// then, we replace the code based on what the CLI wishes.
+		let maybe_code_to_overwrite = match shared.runtime {
+			Runtime::Path(ref path) => Some(std::fs::read(path).map_err(|e| {
+				format!("error while reading runtime file from {:?}: {:?}", path, e)
+			})?),
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply utils/frame/try-runtime/cli/src/lib.rs:603]: great point!

File: utils/frame/try-runtime/cli/src/lib.rs [hunk 35]
```diff
@@ -417,20 +449,24 @@ pub struct SharedParams {
...
 
 	/// The number of 64KB pages to allocate for Wasm execution. Defaults to
 	/// [`sc_service::Configuration.default_heap_pages`].
 	#[arg(long)]
-	pub heap_pages: Option<u64>,
+	heap_pages: Option<u64>,
 
 	/// When enabled, the spec check will not panic, and instead only show a warning.
+	///
+	/// The spec checking will always check the spec name and version of the local code and the
```
[the remark this answers is not in the document]
Comment (kianenigma) [reply utils/frame/try-runtime/cli/src/lib.rs:461]: actually this flag is no longer used -- spec names must always match, spec versions never HAVE TO match.

File: utils/frame/remote-externalities/src/lib.rs (hunk 29 above)
Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:677]: No operation is being blocked by this, but are you saying that this could slow down everything?

Comment (niklasad1) [reply utils/frame/remote-externalities/src/lib.rs:677]: `rx.recv()` will block thread and it's possible that it prevents other futures being scheduled until the next `yield point`

Comment (niklasad1) [reply utils/frame/remote-externalities/src/lib.rs:677]: in other words until a response in sent on this channel.

File: utils/frame/remote-externalities/src/lib.rs (hunk 26 above)
Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:366]: `max(1)` is needed to ensure that if e.g. `keys.len() == 16` and `threads == 20`, we don't allocate 1 key to each thread.

Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:366]: done.

**Review by niklasad1 — APPROVED** [review]
remote-externalities looks good to me but the errors are still quite bad when I tried `$ time cargo test --features remote-test --release can_fetch_all` on public RPC endpoints we would need
https://github.com/paritytech/substrate/pull/12663 for that to be nicer :P

File: utils/frame/try-runtime/cli/src/lib.rs [hunk 36]
```diff
@@ -383,20 +379,56 @@ pub enum Command {
...
-	/// The execution strategy that should be used.
-	#[arg(long, value_name = "STRATEGY", value_enum, ignore_case = true, default_value_t = ExecutionStrategy::Wasm)]
-	pub execution: ExecutionStrategy,
+	#[arg(long)]
+	/// The runtime to use.
+	///
+	/// Must be a path to a wasm blob, compiled with `try-runtime` feature flag.
+	///
+	/// Or, `existing`, indicating that you don't want to overwrite the runtime. This will use
+	/// whatever comes from the remote node, or the snapshot file.
```
Comment (bkchr) [inline utils/frame/try-runtime/cli/src/lib.rs:430]:
```suggestion
	/// The runtime to use.
	///
	/// Must be a path to a wasm blob, compiled with `try-runtime` feature flag.
	///
	/// Or, `existing`, indicating that you don't want to overwrite the runtime. This will use
	/// whatever comes from the remote node, or the snapshot file.
	#[arg(long)]
```

File: utils/frame/try-runtime/cli/src/lib.rs [hunk 37]
```diff
@@ -457,130 +523,163 @@ pub enum State {
...
 
-	/// Get the uri, if self is `Live`.
-	pub(crate) fn live_uri(&self) -> Option<String> {
-		match self {
-			State::Live { uri, .. } => Some(uri.clone()),
-			_ => None,
+		// whatever runtime we have in store now must have been compiled with try-runtime feature.
+		if !ensure_try_runtime::<Block, HostFns>(&shared, &ext) {
+			return Err("given runtime is NOT compiled with try-runtime feature!".into())
 		}
```
Comment (bkchr) [inline utils/frame/try-runtime/cli/src/lib.rs:638]:
```suggestion
		if runtime_version.api_version(TryRuntime::ID).is_none() {
			return Err("given runtime is NOT compiled with try-runtime feature!".into())
		}
```

Something like that is much better and easier :P

File: utils/frame/try-runtime/cli/src/commands/offchain_worker.rs [hunk 38]
```diff
@@ -89,84 +55,50 @@ impl OffchainWorkerCmd {
...
-		expected_spec_name,
-		expected_spec_version,
-		shared.no_spec_check_panic,
-	)
-	.await;
+	let header = ChainApi::<(), Block::Hash, Block::Header, ()>::header(&rpc, Some(next_hash))
+		.await
+		.map_err(rpc_err_handler)
+		.map(|maybe_header| maybe_header.ok_or("Header does not exist"))??;
+	let payload = (header).encode();
```
Comment (bkchr) [inline utils/frame/try-runtime/cli/src/commands/offchain_worker.rs:93]:
```suggestion
	let payload = header.encode();
```

File: utils/frame/remote-externalities/src/lib.rs [hunk 39]
```diff
@@ -462,214 +599,342 @@ where
...
+
+		for thread_child_roots in child_roots
+			.chunks(child_roots_per_thread)
+			.map(|x| x.into())
+			.collect::<Vec<Vec<_>>>()
+		{
+			let thread_client = client.clone();
+			let thread_sender = tx.clone();
+			let handle = thread::spawn(move || {
+				let rt = tokio::runtime::Runtime::new().unwrap();
```
Comment (bkchr) [inline utils/frame/remote-externalities/src/lib.rs:663]: You should share the same runtime for the entire `RemoteExternalities` instance. You can then use https://docs.rs/tokio/latest/tokio/runtime/struct.Handle.html#method.block_on to block on futures

File: frame/support/src/traits/hooks.rs [hunk 40]
```diff
@@ -440,110 +437,4 @@ mod tests {
 			ON_IDLE_INVOCATION_ORDER.clear();
 		}
 	}
-
-	#[cfg(feature = "try-runtime")]
-	#[test]
-	#[allow(dead_code)]
-	fn on_runtime_upgrade_tuple() {
```
Comment (bkchr) [inline frame/support/src/traits/hooks.rs:447]: Why did you removed this?

File: bin/node/runtime/src/lib.rs [hunk 41]
```diff
@@ -2148,15 +2148,18 @@ impl_runtime_apis! {
 		) -> Weight {
 			log::info!(
 				target: "node-runtime",
-				"try-runtime: executing block {:?} / root checks: {:?} / try-state-select: {:?}",
+				"try-runtime: executing block {:?} / state root check: {:?} / signature check: {:?} / try-state-select: {:?}",
 				block.header.hash(),
 				state_root_check,
+				false,
 				select,
 			);
```
Comment (bkchr) [inline bin/node/runtime/src/lib.rs:2156]: Why isn't this printed in `try_execute_block`?

File: frame/support/src/traits/hooks.rs [hunk 42]
```diff
@@ -136,13 +133,39 @@ pub trait OnRuntimeUpgrade {
...
+			let _guard = frame_support::StorageNoopGuard::default();
+			let state = Self::pre_upgrade()?;
+			Some(state)
+		} else {
+			None
+		};
+
+		let weight = Self::on_runtime_upgrade();
+
+		if checks {
```
Comment (bkchr) [inline frame/support/src/traits/hooks.rs:150]:
```suggestion
		if let Some(state) = maybe_state {
```

File: frame/support/src/traits/hooks.rs [hunk 43]
```diff
@@ -136,13 +133,39 @@ pub trait OnRuntimeUpgrade {
...
+			let _guard = frame_support::StorageNoopGuard::default();
+			// we want to panic if any checks fail right here right now.
+			Self::post_upgrade(maybe_state.expect("checks has not changed; value is Some; qed"))?
```
Comment (bkchr) [inline frame/support/src/traits/hooks.rs:153]:
```suggestion
			Self::post_upgrade(state)?
```

File: frame/try-runtime/src/lib.rs (hunk 31 above)
[the remark this answers is not in the document]
Comment (bkchr) [reply frame/try-runtime/src/lib.rs:52]: I added a comment on how to remove this function. Please remove it :P

**Review by bkchr — APPROVED** [review]

File: utils/frame/remote-externalities/src/lib.rs (hunk 39 above)
Comment (kianenigma) [reply utils/frame/remote-externalities/src/lib.rs:663]: I delegate all such changes to @niklasad1 and #12869

File: frame/support/src/traits/hooks.rs (hunk 40 above)
Comment (kianenigma) [reply frame/support/src/traits/hooks.rs:447]: It is not needed anymore, because the logic is now trivial.

File: bin/node/runtime/src/lib.rs (hunk 41 above)
Comment (kianenigma) [reply bin/node/runtime/src/lib.rs:2156]: Yeah seems a bit too noisy, will remove.

File: utils/frame/try-runtime/cli/src/lib.rs (hunk 37 above)
Comment (kianenigma) [reply utils/frame/try-runtime/cli/src/lib.rs:638]: Beautiful sir.

Comment (kianenigma) [reply utils/frame/try-runtime/cli/src/lib.rs:638]: Well, we don't work at the `client/ProvideRuntimeApi` level here, so hard to find something that implements `ApiExt` from the state machine or the raw code. Might give up.

Comment (kianenigma) [reply utils/frame/try-runtime/cli/src/lib.rs:638]: yeah, it seems like all such functionality is only available if you build a whole client, which we totally don't want to do here. https://paritytech.github.io/substrate/master/sp_api/trait.ProvideRuntimeApi.html#implementors

**Comment by kianenigma** [comment]
@lisa-parity after this PR, the docs for `try-runtime` in substrate.dev needs to be re-visited. I have documented the source code quite extensively, which I hope can act as a good starting point.

File: utils/frame/try-runtime/cli/src/lib.rs (hunk 37 above)
Comment (bkchr) [reply utils/frame/try-runtime/cli/src/lib.rs]: That is the reason I had written `runtime_version` :P

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2159100

**Comment by kianenigma** [comment]
bot merge

**Comment by kianenigma** [comment]
bot merge

**Comment by kianenigma** [comment]
bot merge
