### PR TITLE
Fix tried to send handshake twice

### LINKED ISSUE #5201: "Tried to enable notifications handler that was already enabled"
Some warnings have been noticed on Polkadot master.

```
2020-03-07 19:24:12 Imported #1351071 (0x2a59…4c87)
2020-03-07 19:24:20 Discovered new external address for our node: /ip4/10.156.1.213/tcp/30333/p2p/QmSz5s5cmK2x2A1BKMyWvtTX2Sy6LzmPZN1AJPzMvWfiEK
2020-03-07 19:24:20 Imported #1351071 (0x9113…db21)
2020-03-07 19:24:20 Imported #1351071 (0xec8c…07b5)
2020-03-07 19:24:21 Tried to enable notifications handler that was already enabled
2020-03-07 19:24:21 Tried to enable notifications handler that was already enabled
2020-03-07 19:24:21 Tried to enable notifications handler that was already enabled
2020-03-07 19:24:21 Imported #1351072 (0x62d8…9747)
2020-03-07 19:24:21 Notifications handler in a poisoned state
2020-03-07 19:24:21 Notifications handler in a poisoned state
2020-03-07 19:24:21 Notifications handler in a poisoned state
2020-03-07 19:24:21 Imported #1351072 (0xe3b5…5796)
```

```
2020-03-08 08:45:18 Tried to send handshake twice
2020-03-08 08:45:18 Tried to send handshake twice
2020-03-08 08:45:18 Tried to send handshake twice
```

Having the `sub-libp2p` logs would be extremely useful, however I tried running a node with `--in-peers 200` for 12 hours and couldn't reproduce.

Messages are printed three times because Polkadot has three active notification protocols, but this probably concerns only one connection.

### PR DESCRIPTION
**Pull request by tomaka**
cc #5201

There was a possible state inconsistency in the `NotificationsInSubstream`.

### CODE REVIEW

File: client/network/src/protocol/generic_proto/upgrade/notifications.rs [hunk 1]
```diff
@@ -189,8 +186,10 @@ where TSubstream: AsyncRead + AsyncWrite + Unpin,
 			match mem::replace(this.handshake, NotificationsInSubstreamHandshake::Sent) {
 				NotificationsInSubstreamHandshake::Sent =>
 					return Stream::poll_next(this.socket.as_mut(), cx),
-				NotificationsInSubstreamHandshake::NotSent =>
-					return Poll::Pending,
+				NotificationsInSubstreamHandshake::NotSent => {
+					*this.handshake = NotificationsInSubstreamHandshake::NotSent;
```
Comment (tomaka) [inline client/network/src/protocol/generic_proto/upgrade/notifications.rs]: The main bugfix is here.
The rest of the PR is only the log statements that I added a bit everywhere in my attempts to understand the issue.

File: client/network/src/protocol/generic_proto/handler/group.rs [hunk 2]
```diff
@@ -302,6 +302,9 @@ impl ProtocolsHandler for NotifsHandler {
 	fn inject_event(&mut self, message: NotifsHandlerIn) {
 		match message {
 			NotifsHandlerIn::Enable => {
+				if let EnabledState::Enabled = self.enabled {
+					error!("enabling already-enabled handler");
```
Comment (romanb) [inline client/network/src/protocol/generic_proto/handler/group.rs]:
```suggestion
					debug!("enabling already-enabled handler");
```
I'm suggesting this because I really don't think it is a good idea if duplicate invocations of code which can trivially be idempotent (like enabling or disabling a handler) are treated as errors. I've been bitten by that before in substrate code in the context of https://github.com/paritytech/substrate/pull/5278 where a handler was even unnecessarily left in a poisoned state, see [here](https://github.com/paritytech/substrate/blob/master/client/network/src/protocol/generic_proto/handler/notif_out.rs#L284-L285) and [here](https://github.com/paritytech/substrate/blob/master/client/network/src/protocol/generic_proto/handler/notif_out.rs#L292-L293). I change that in #5278. These may be the causes for the other logs seen in #5201.

At worst, calling an idempotent method or callback twice is a performance issue, hence justifying debug or trace logs, but in my opinion should never be considered an error and especially not unnecessarily leave the code in a broken state.

File: client/network/src/protocol/generic_proto/handler/group.rs [hunk 3]
```diff
@@ -314,6 +317,9 @@ impl ProtocolsHandler for NotifsHandler {
 				}
 			},
 			NotifsHandlerIn::Disable => {
+				if let EnabledState::Disabled = self.enabled {
+					error!("disabling already-disabled handler");
```
Comment (romanb) [inline client/network/src/protocol/generic_proto/handler/group.rs]:
```suggestion
					debug!("disabling already-disabled handler");
```

File: client/network/src/protocol/generic_proto/handler/notif_in.rs [hunk 4]
```diff
@@ -156,16 +156,19 @@ impl ProtocolsHandler for NotifsInHandler {
 		&mut self,
 		(msg, proto): <Self::InboundProtocol as InboundUpgrade<NegotiatedSubstream>>::Output
 	) {
+		// If a substream already exists, we drop it and replace it with the new incoming one.
```
Comment (romanb) [inline client/network/src/protocol/generic_proto/handler/notif_in.rs]: What is the rationale for preferring the new substream over the old?

File: client/network/src/protocol/generic_proto/upgrade/notifications.rs [hunk 5]
```diff
@@ -164,12 +164,9 @@ where TSubstream: AsyncRead + AsyncWrite,
 {
 	/// Sends the handshake in order to inform the remote that we accept the substream.
 	pub fn send_handshake(&mut self, message: impl Into<Vec<u8>>) {
-		match self.handshake {
-			NotificationsInSubstreamHandshake::NotSent => {}
-			_ => {
-				error!(target: "sub-libp2p", "Tried to send handshake twice");
-				return;
-			}
+		if matches!(self.handshake, NotificationsInSubstreamHandshake::NotSent) {
```
[the remark this answers is not in the document]
Comment (tomaka) [reply client/network/src/protocol/generic_proto/upgrade/notifications.rs]: Oh right. I reapplied my changes manually before opening the PR and made a mistake here.

File: client/network/src/protocol/generic_proto/handler/notif_in.rs (hunk 4 above)
Comment (tomaka) [reply client/network/src/protocol/generic_proto/handler/notif_in.rs]: It is forbidden to open a new substream if you already have one open. You're supposed to close the current one first.

I realized, however, that if the remote opens a substream, then closes it, then opens another one, then `inject_fully_negotiated_inbound` might be called a second time before we had the chance to realize that the first substream has been closed.

Consequently I went with simply always using with the most-recently opened substream.

File: client/network/src/protocol/generic_proto/handler/group.rs (hunk 2 above)
Comment (tomaka) [reply client/network/src/protocol/generic_proto/handler/group.rs]: > At worst, calling an idempotent method or callback twice is a performance issue

My reasoning is that the logic of `src/protocol/generic_proto/behaviour.rs` is quite complicated, and a state inconsistency there can quickly degenerate into more complicated issues.

I went with `error!` in order to scream out "we've found a bug" without it going unnoticed.

Comment (tomaka) [reply client/network/src/protocol/generic_proto/handler/group.rs]: It makes sense to put avoid these poisoned state, but there is no such poisoned state in this PR, and I would leave them as `error!`s.

File: client/network/src/protocol/generic_proto/handler/notif_in.rs (hunk 4 above)
Comment (tomaka) [reply client/network/src/protocol/generic_proto/handler/notif_in.rs]: I'm not actually sure that this specific situation can happen with `yamux`, as it depends on how the `StreamMuxer` is implemented.

File: client/network/src/protocol/generic_proto/handler/group.rs (hunk 2 above)
Comment (romanb) [reply client/network/src/protocol/generic_proto/handler/group.rs]: > I went with error! in order to scream out "we've found a bug" without it going unnoticed.

As I said, I do not consider it a bug if an idempotent piece of code, which enabling/disabling a handler should be, is executed multiple times, but rather only a potential performance improvement if one wishes to avoid all extraneous calls. Requiring some code which could easily be idempotent to only be called "once", just makes life unnecessarily harder since it makes it harder to write functionally correct code. Again, just my two cents. The bug that is fixed here seems to me somewhere else and if multiple invocations of "enable" / "disable" would somehow be connected to a bug, `debug!` logging is sufficient to identify such unwanted interactions.

File: client/network/src/protocol/generic_proto/handler/notif_in.rs (hunk 4 above)
Comment (romanb) [reply client/network/src/protocol/generic_proto/handler/notif_in.rs]: I see, thanks.

File: client/network/src/protocol/generic_proto/handler/group.rs (hunk 2 above)
Comment (tomaka) [reply client/network/src/protocol/generic_proto/handler/group.rs]: From the perspective of the `NotificationsInHandler` it is indeed not a bug to get enabled when it is already enabled or disabled when it is already disabled.

This `error!` exists purely to detect bugs in `behaviour.rs` and it exists because of implementation details in `behaviour.rs`.

I agree that theoretically speaking this `error!` should be in `behaviour.rs` and not here, but from a pragmatic perspective, if you look at the code in `behaviour.rs`, it is much more reasonable to put it here.

Comment (tomaka) [reply client/network/src/protocol/generic_proto/handler/group.rs]: I've changed this to `debug!`s so that we hopefully get this in before the Polkadot release today.

**Comment by NikVolf** [comment]
> Not sure about the test failure on `should_revalidate_across_many_blocks`, I think I've seen it before (i.e. I think it is just a flaky test, but don't take my word for it).

test was fixed, just merge master @tomaka

**Comment by tomaka** [comment]
#5360 has been merged and triggers this error way more often, so I'm going to merge this fix as soon as the CI passes.

**Comment by tomaka** [comment]
@NikVolf Now it's `testing::pool::should_push_watchers_during_maintaince` that is failing for what it's worth.
