### PR TITLE
RUSTSEC-2021-0076 bump libsecp256k1

### LINKED ISSUE #9356: RUSTSEC-2021-0076 and libsecp256k1 version in sp-core
There has been a new RUSTSEC issue that stems from `libsecp256k1`: https://rustsec.org/advisories/RUSTSEC-2021-0076

I would like to bump `libsecp256k1` in `sp-core`, but there are two blockers in the way:
1. There's a bug that is solved on master but not yet in a release, which is needed to make the changes from `0.3.5` -> `0.5.x`: https://github.com/paritytech/libsecp256k1/pull/63
2. `libsecp256k1` no_std is broken. I submitted a PR already and tracking here: https://github.com/paritytech/libsecp256k1/issues/71

Once these are resolved I will submit a PR to bump the dependency and make the required changes.

### PR DESCRIPTION
**Pull request by trevor-crypto**
libsecp256k1 allows overflowing signatures
https://rustsec.org/advisories/RUSTSEC-2021-0076

Changes were made to conform to libsecp256k1 version differences.

Closes #9356

### CODE REVIEW

**Comment by bkchr** [comment]
@sorpaas please check if that is the right way. I remember that you said something about some migration.

File: primitives/core/src/ecdsa.rs [hunk 1]
```diff
@@ -379,12 +379,12 @@ impl From<(secp256k1::Signature, secp256k1::RecoveryId)> for Signature {
...
 #[cfg(feature = "full_crypto")]
-impl<'a> TryFrom<&'a Signature> for (secp256k1::Signature, secp256k1::RecoveryId) {
+impl<'a> TryFrom<&'a Signature> for (libsecp256k1::Signature, libsecp256k1::RecoveryId) {
 	type Error = ();
-	fn try_from(x: &'a Signature) -> Result<(secp256k1::Signature, secp256k1::RecoveryId), Self::Error> {
+	fn try_from(x: &'a Signature) -> Result<(libsecp256k1::Signature, libsecp256k1::RecoveryId), Self::Error> {
 		Ok((
-			secp256k1::Signature::parse_slice(&x.0[0..64]).expect("hardcoded to 64 bytes; qed"),
-			secp256k1::RecoveryId::parse(x.0[64]).map_err(|_| ())?,
+			libsecp256k1::Signature::parse_standard_slice(&x.0[0..64]).expect("hardcoded to 64 bytes; qed"),
```
Comment (sorpaas) [inline primitives/core/src/ecdsa.rs:386]:
```suggestion
			libsecp256k1::Signature::parse_overflowing_slice(&x.0[0..64]).expect("hardcoded to 64 bytes; qed"),
```

We still need this as `parse_overflowing_slice` for now, then move to `parse_standard_slice` through a migration.

File: primitives/core/src/ecdsa.rs [hunk 2]
```diff
@@ -509,11 +509,11 @@ impl TraitPair for Pair {
...
 	/// size. Use it only if you're coming from byte buffers and need the speed.
 	fn verify_weak<P: AsRef<[u8]>, M: AsRef<[u8]>>(sig: &[u8], message: M, pubkey: P) -> bool {
-		let message = secp256k1::Message::parse(&blake2_256(message.as_ref()));
+		let message = libsecp256k1::Message::parse(&blake2_256(message.as_ref()));
 		if sig.len() != 65 { return false }
-		let ri = match secp256k1::RecoveryId::parse(sig[64]) { Ok(x) => x, _ => return false };
-		let sig = match secp256k1::Signature::parse_slice(&sig[0..64]) { Ok(x) => x, _ => return false };
-		match secp256k1::recover(&message, &sig, &ri) {
+		let ri = match libsecp256k1::RecoveryId::parse(sig[64]) { Ok(x) => x, _ => return false };
+		let sig = match libsecp256k1::Signature::parse_standard_slice(&sig[0..64]) { Ok(x) => x, _ => return false };
```
Comment (sorpaas) [inline primitives/core/src/ecdsa.rs:515]: Same here.

File: primitives/core/src/ecdsa.rs (hunk 1 above)
Comment (trevor-crypto) [reply primitives/core/src/ecdsa.rs:386]: What's the reasoning behind this? (just for my own education)

Comment (trevor-crypto) [reply primitives/core/src/ecdsa.rs]: Actually, I see. Some preexisting Signatures may be overflowing so we need to parse them with that

Comment (sorpaas) [reply primitives/core/src/ecdsa.rs]: It would otherwise be an actual security advisory for Substrate.

Parsing overflowing slice is not dangerous and by itself is safe. The security advisory arises if there are multiple clients being maintained and all of them need to conform to a standard way.

If we change this to `parse_standard_slice` in Substrate now we need to mark it as a high security upgrade for Substrate and ask everyone to upgrade, and during this period an attacker can split the chain. On the other hand, if we do it via a migration then it's completely safe, and we can do the migration in our own pace without any security concerns.

The drawback for the later, of course, is that `parse_overflowing_slice` will exist in Substrate at least for years to come (until when old blocks no longer needs to be re-processed by anyone). However, given that the method is actually safe, but just non-standard, it shouldn't be of any problems.

Comment (bkchr) [reply primitives/core/src/ecdsa.rs]: What you mean by a migration? 

Isn't the problem only the old runtimes? So we should introduce a new host function?

Comment (sorpaas) [reply primitives/core/src/ecdsa.rs]: Yeah. We're on the same page.

**Review by sorpaas — DISMISSED** [review]

**Comment by bkchr** [comment]
@sorpaas shouldn't we directly introduce the new host function? Host functions support versioning and we already use this versioning for a similar problem with schnorrkel.

**Comment by sorpaas** [comment]
@bkchr Yeah we should do it.

**Comment by bkchr** [comment]
@trevor-crypto check this out https://github.com/paritytech/substrate/blob/master/primitives/io/src/lib.rs#L599-L600

@trevor-crypto We would need to do something similar here and use `parse_overflowing_slice()` in the version 1 and version 2 would use `parse_standard_slice()`

**Comment by trevor-crypto** [comment]
@bkchr thanks! Found my way there already by furiously grepping for 'host functions". I'm wondering how something like this will work with the `TryFrom` trait impl, since that is one place where `parse_overflowing/standard_slice()` needs to be used.

**Comment by bkchr** [comment]
@trevor-crypto basically you need to revert https://github.com/paritytech/substrate/pull/9391/commits/c65328414a561180e16e44ff20d6de182f4a55ad because everything from now need to use the new function. Only the old host function needs to use the old function.

**Comment by trevor-crypto** [comment]
Added version 2 for `ecdsa_verify`. Please check carefully :pray:

**Comment by bkchr** [comment]
@sorpaas please also check another time.

File: primitives/core/src/ecdsa.rs [hunk 3]
```diff
@@ -546,25 +545,57 @@ impl Pair {
...
+		};
+		match libsecp256k1::recover(&message, &sig, &ri) {
+			Ok(actual) => pubkey.0[..] == actual.serialize_compressed()[..],
+			_ => false,
+		}
+	}
+}
+
+#[cfg(feature = "full_crypto")]
+fn parse_signature(
```
Comment (sorpaas) [inline primitives/core/src/ecdsa.rs:584]: Can we rename this to `parse_standard_signature` and `parse_overflowing_signature` and similarly for all the above `verify_` public functions? The priority here should be make sure that all library users get to deliberately choose whether they want standard or overflowing, so we shouldn't be using the same old name.

Comment (trevor-crypto) [reply primitives/core/src/ecdsa.rs]: Can't change the trait fn names, but I changed `verify_deprecated` to `verify_overflowing`

Comment (sorpaas) [reply primitives/core/src/ecdsa.rs]: That doesn't do much unfortunately. If you can't change the other name for `standard` then I suggest putting the `overflowing` one to deprecated.

I don't have huge problems keeping it as is, but we do need to be slightly careful here since misusing `overflowing` vs `standard` may be a source of trouble.

Alternatively, we can create a separate structure for the `OverflowingSignature` and rename the current one to `StandardSignature`. That would be the best for clarify, but just that it may be a lot of work -- so I guess it's optional.

**Comment by trevor-crypto** [comment]
Rebased with `master` hoping that the tests would pass :confounded:

File: primitives/core/src/ecdsa.rs (hunk 3 above)
Comment (trevor-crypto) [reply primitives/core/src/ecdsa.rs]: @sorpaas ok thanks. I will leave it as `verify_deprecated`, since it also coincides with the names of the other versioned host functions in `primitives/io/src/lib.rs`.

**Review by sorpaas — APPROVED** [review]

**Comment by girazoki** [comment]
I wanted to jump in because I see that  https://github.com/paritytech/substrate/blob/7dcc77b982f59eaf6cec19499d981164b04a255d/primitives/io/src/lib.rs#L750 also uses `secp256k1::Signature::parse_slice`. Is there a reason why it does not need to get this change?

**Review by sorpaas — CHANGES_REQUESTED** [review]
Yeah @girazoki is right. This PR still misses a few version bumps.

**Comment by trevor-crypto** [comment]
Thanks @girazoki 

I guess I missed other places as well like bumping `libp2p` since `libp2p-core` uses `libsecp256k1` too.

**Comment by trevor-crypto** [comment]
All traces of < v0.5.0 of `libsecp256k1` have been removed. Once https://github.com/libp2p/rust-libp2p/pull/2151 is in a release, then everything should be on `libsecp256k1 v0.6.0`.

**Comment by girazoki** [comment]
Nice! Is there a reason why sp_io::crypto::secp256k1_ecdsa_recover does not need to handle both parse_overflowing and parse_standard? Wouldnt it be the case that if we have a block/tx with a signature that overflows, if we just use the `parse_standard` would fail?

**Comment by sorpaas** [comment]
I think this assumes that we don't actually use secp256k1 outside of runtime. From what I know this seems to be the case.

**Comment by bkchr** [comment]
> I wanted to jump in because I see that
> 
> https://github.com/paritytech/substrate/blob/7dcc77b982f59eaf6cec19499d981164b04a255d/primitives/io/src/lib.rs#L750
> also uses `secp256k1::Signature::parse_slice`. Is there a reason why it does not need to get this change?

Yeah this is right, this needs to be versioned as well.

**Comment by trevor-crypto** [comment]
@bkchr ok, so I will also add a v2 for `secp256k1_ecdsa_recover` and `secp256k1_ecdsa_recover_compressed`

**Comment by bkchr** [comment]
Ty! And after a master merge we should be ready to merge this pr! Sorry for the delay!

**Comment by trevor-crypto** [comment]
Please check carefully! Thanks :grin: :pray:

**Comment by bkchr** [comment]
@tomaka @kpp could please someone of you review the libp2p changes

File: primitives/core/Cargo.toml [hunk 4]
```diff
@@ -49,7 +49,7 @@ schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated", "u64_backen
 sha2 = { version = "0.9.2", default-features = false, optional = true }
 hex = { version = "0.4", default-features = false, optional = true }
 twox-hash = { version = "1.5.0", default-features = false, optional = true }
-libsecp256k1 = { version = "0.3.2", default-features = false, features = ["hmac"], optional = true }
+libsecp256k1 = { version = "0.6", default-features = false, features = ["hmac", "static-context"], optional = true }
```
Comment (tomaka) [inline primitives/core/Cargo.toml:52]: Note keeping: in principle this feature shouldn't be there, but https://github.com/paritytech/libsecp256k1/issues/77

File: client/network/src/protocol/notifications/tests.rs [hunk 5]
```diff
@@ -262,8 +262,8 @@ fn reconnect_after_disconnect() {
 		loop {
 			// Grab next event from services.
 			let event = {
-				let s1 = service1.next();
-				let s2 = service2.next();
+				let s1 = service1.select_next_some();
+				let s2 = service2.select_next_some();
```
Comment (tomaka) [inline client/network/src/protocol/notifications/tests.rs:266]: Did you change this because you encountered a panic with `next()`? Or did you change this "just in case"?

**Review by tomaka — APPROVED** [review]
Libp2p changes look good, thanks!

File: client/network/src/protocol/notifications/tests.rs (hunk 5 above)
Comment (trevor-crypto) [reply client/network/src/protocol/notifications/tests.rs:266]: No panic, just does not compile anymore. I did a quick read through some PRs and found `select_next_some()` in an example usage

Comment (tomaka) [reply client/network/src/protocol/notifications/tests.rs:266]: Weird that it doesn't compile, but why not.

Comment (trevor-crypto) [reply client/network/src/protocol/notifications/tests.rs:266]: The `next()` call is fine, but it would have required me to match on the `Option<...>` in the `match` below. Thought this was more concise.

**Comment by bkchr** [comment]
@tomaka any why this test is failing:
```
---- discovery::tests::discovery_working stdout ----
thread 'discovery::tests::discovery_working' panicked at 'Unexpected event: NewListenAddr { listener_id: ListenerId(1), address: "/memory/9379582200911454507" }', client/network/src/discovery.rs:1036:37
stack backtrace:
```

**Comment by tomaka** [comment]
New version of libp2p now reports all events, such as new local addresses, instead of only discovery-specific events. The test just needs to be adjusted to ignore anything that's not `SwarmEvent::Behaviour` instead of panicking.

**Comment by trevor-crypto** [comment]
> The test just needs to be adjusted to ignore anything that's not SwarmEvent::Behaviour instead of panicking.

@tomaka done, thanks!

**Review by sorpaas — CHANGES_REQUESTED** [review]
There are still two libsecp256k1 dependencies -- 0.5.0 and 0.6.0. I believe 0.5.0 might come from libp2p. You might temporarily downgrade to 0.5.0, but I really hope this can be upgraded soon since there are many new changes between 0.5.0 and 0.6.0.

**Comment by trevor-crypto** [comment]
@sorpaas yeah, that is true. I didn't think it would conflict, since the RUSTSEC states that >=0.5.0 is fine.

It seems that this is already bumped on `libp2p` master. Maybe someone can push a release? Then after that I can bump the `libp2p` version

**Comment by bkchr** [comment]
I don't see any reason to block this pr because some libp2p stuff isn't updated yet.

**Comment by tomaka** [comment]
The merge conflict is just because of https://github.com/paritytech/substrate/pull/9490
You can solve it by replacing the file with your code.

**Comment by tomaka** [comment]
I didn't mention this, but we don't make any use of the secp256k1 capabilities of libp2p. I don't see any reason to not merge this PR.

**Review by sorpaas — APPROVED** [review]

**Comment by bkchr** [comment]
@trevor-crypto sorry :see_no_evil: Please merge master again and then I will merge this! Sorry for the problems

**Comment by trevor-crypto** [comment]
Rebased with `master` again. Had a lot of lock file conflicts, so hopefully everything worked out :grimacing:

**Review by tomaka — APPROVED** [review]

File: bin/node/browser-testing/Cargo.toml [hunk 6]
```diff
@@ -8,6 +8,8 @@ license = "Apache-2.0"
 
 [dependencies]
 jsonrpc-core = "18.0.0"
+futures-timer = "3.0.2"
+libp2p = { version = "0.39.1", default-features = false }
```
Comment (bkchr) [inline bin/node/browser-testing/Cargo.toml:12]:
```suggestion
```

File: primitives/core/src/ecdsa.rs [hunk 7]
```diff
@@ -577,25 +567,57 @@ impl Pair {
...
+			_ => false,
+		}
+	}
+}
+
+#[cfg(feature = "full_crypto")]
+fn parse_signature_standard(
+	x: &[u8],
+) -> Result<(libsecp256k1::Signature, libsecp256k1::RecoveryId), libsecp256k1::Error> {
+	let sig = libsecp256k1::Signature::parse_standard_slice(&x[0..64])?;
```
Comment (bkchr) [inline primitives/core/src/ecdsa.rs:609]:
```suggestion
	let sig = libsecp256k1::Signature::parse_standard_slice(&x[..64])?;
```

File: primitives/core/src/ecdsa.rs [hunk 8]
```diff
@@ -577,25 +567,57 @@ impl Pair {
...
+	let ri = libsecp256k1::RecoveryId::parse(x[64])?;
+	Ok((sig, ri))
+}
+
+#[cfg(feature = "full_crypto")]
+fn parse_signature_overflowing(
+	x: &[u8],
+) -> Result<(libsecp256k1::Signature, libsecp256k1::RecoveryId), libsecp256k1::Error> {
+	let sig = libsecp256k1::Signature::parse_overflowing_slice(&x[0..64])?;
```
Comment (bkchr) [inline primitives/core/src/ecdsa.rs:618]:
```suggestion
	let sig = libsecp256k1::Signature::parse_overflowing_slice(&x[..64])?;
```

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge

**Comment by trevor-crypto** [comment]
@bkchr Thanks for applying those fixes!

**Comment by bkchr** [comment]
bot merge force
