### PR TITLE
registrar: Avoid freebies in provide_judgement

### LINKED ISSUE #12294: BEEFY: Implement peer reputation changes for gossip exchanges
BEEFY voter gadget uses its own gossip sub-protocol, but currently doesn't make use of the peer reputation changes API available there.

This issue tracks defining the reputation change deltas for the various error-cases and plumbing them in.

### LINKED ISSUE #12460: registrar: Avoid freebies in `provide_judgement`
In `provide_judgement`, evaluate the return value of `repatriate_reserved` and do not store the judgement if it fails. The registrar will still have to pay the fees without getting any compensation but at least the user won't get a confirmed identity for free.

### PR DESCRIPTION
**Pull request by dharjeezy**
This PR evaluates the error being returned by `repatriate_reserved`

Wrote test

Fixed Benchmarks

closes #12460

Polkadot address: 12ZNas89oEagaxLVNbpqmvfMxdrGrqN7gJKSpwthTUPZsrku

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@dharjeezy please fix the tests and please also add a specific test for exactly the fixed case.

**Comment by dharjeezy** [comment]
> @dharjeezy please fix the tests and please also add a specific test for exactly the fixed case.

Oh...Alright, Will do.

**Review by kianenigma — APPROVED** [review]
IFF tests are added.

**Comment by dharjeezy** [comment]
@bkchr @kianenigma 

Wrote tests and fixed benchmarks

File: frame/identity/src/benchmarking.rs [hunk 1]
```diff
@@ -44,7 +44,7 @@ fn add_registrars<T: Config>(r: u32) -> Result<(), &'static str> {
 		let _ = T::Currency::make_free_balance_be(&registrar, BalanceOf::<T>::max_value());
 		let registrar_origin = T::RegistrarOrigin::successful_origin();
 		Identity::<T>::add_registrar(registrar_origin, registrar_lookup)?;
-		Identity::<T>::set_fee(RawOrigin::Signed(registrar.clone()).into(), i, 10u32.into())?;
+		Identity::<T>::set_fee(RawOrigin::Signed(registrar.clone()).into(), i, 0u32.into())?;
```
Comment (bkchr) [inline frame/identity/src/benchmarking.rs:47]: Can we please change this back?

Comment (bkchr) [reply frame/identity/src/benchmarking.rs:47]: There are sometimes optimization when the transferred amount is 0.

File: frame/identity/src/lib.rs [hunk 2]
```diff
@@ -238,6 +238,8 @@ pub mod pallet {
 		NotOwned,
 		/// The provided judgement was for a different identity.
 		JudgementForDifferentIdentity,
+		/// Error thrown when repatriate_reserved returns an error.
+		RepatriateReservedError,
```
Comment (bkchr) [inline frame/identity/src/lib.rs:242]:
```suggestion
		JudgementPaymenrFailed,
```

Also change doc to make this more clear

**Review by bkchr — COMMENTED** [review]
Generally looking good. We will just need to wait for the audit, but this should be simple.

Please also provide your polkadot address

File: frame/identity/src/lib.rs (hunk 2 above)
Comment (dharjeezy) [reply frame/identity/src/lib.rs]: > Also change doc to make this more clear

I noticed there is a typo in your suggested change @bkchr

File: frame/identity/src/benchmarking.rs (hunk 1 above)
Comment (dharjeezy) [reply frame/identity/src/benchmarking.rs]: > Can we please change this back?

Gone ahead to fix this

**Comment by dharjeezy** [comment]
> Generally looking good. We will just need to wait for the audit, but this should be simple.
> 
> Please also provide your polkadot address

I have gone ahead to update my PR description with my Polkadot address @bkchr

File: frame/identity/src/benchmarking.rs [hunk 3]
```diff
@@ -362,9 +372,14 @@ benchmarks! {
 
 		// User requests judgement from all the registrars, and they approve
 		for i in 0..r {
+			let registrar: T::AccountId = account("registrar", i, SEED);
+			let registrar_lookup = T::Lookup::unlookup(registrar.clone());
```
Comment (bkchr) [inline frame/identity/src/benchmarking.rs:376]:
```suggestion
```

File: frame/identity/src/benchmarking.rs [hunk 4]
```diff
@@ -213,9 +218,14 @@ benchmarks! {
...
```
Comment (bkchr) [inline frame/identity/src/benchmarking.rs:222]:
```suggestion
```

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
bot merge
