### PR TITLE
offchain: Upgrade hyper to 0.13, which uses tokio 0.2

### LINKED ISSUE #4647: offchain::http_response_wait() fatal executor error: SpawnError { is_shutdown: true }
When I use `offchain` methods:

```
let id: HttpRequestId = sp_io::offchain::http_request_start(method, uri, &[0]).unwrap();
let deadline = sp_io::offchain::timestamp().add(Duration::from_millis(100_000));

match sp_io::offchain::http_response_wait(&[id], Some(deadline))[0] {
	HttpRequestStatus::Finished(200) => (),
	_ => {
		return Err("Request failed");
	}
}
```
it will  return `HttpRequestStatus::IoError`,  runtime logs are:

```
main WARN hyper::common::exec  executor error: SpawnError { is_shutdown: true }
main WARN hyper::client  error spawning critical client task: executor failed to spawn task: tokio::spawn failed (is a tokio runtime running this future?)
```

Substrate Version: commit 39db16e213d92db4f0bffc9dae715ad9c59d2a0c

Is there something wrong with `offchain http_request` or just not the right methods I used ?

Thanks.

### PR DESCRIPTION
**Pull request by Xanewok**
Fixes the regressed offchain HTTP API by upgrading hyper to use tokio 0.2.

While an integration test for offchain HTTP API [exists](https://github.com/paritytech/substrate/blob/b02a97129286a8453ef78f58963b72c7ae47aef6/client/executor/src/integration_tests/mod.rs#L469), it [uses mocks in `TestOffchainExt`](https://github.com/paritytech/substrate/blob/6e0a4877afbe2309e106b84333bb70200531b604/primitives/core/src/offchain/testing.rs#L199-L304), so I decided against duplicating an another harness with actual HTTP.

I imagine a better approach would be to set up most of the runtime and test the HTTP from offchain workers directly but didn't want to block the fix here, let me know if I should work on setting that up as well.

Tested manually on https://github.com/Xanewok/substrate/tree/offchain-worker-example with `cargo run --bin node-template -- --dev`.

Fixes #4647.

### CODE REVIEW

**Comment by Xanewok** [comment]
Forgot to adapt the test code as well, let me fix it up real quick.

**Comment by bkchr** [comment]
I think it would be nice to have a real test. I think if we use the test runtime and create some server for the test. You would connect to this server from the offchain worker.

File: client/offchain/src/api/http.rs [hunk 1]
```diff
@@ -688,31 +688,38 @@ impl fmt::Debug for HttpWorkerRequest {
...
 	use super::http;
-	use futures::prelude::*;
-	use futures01::Future as _;
 	use sp_core::offchain::{HttpError, HttpRequestId, HttpRequestStatus, Duration};
 
 	// Returns an `HttpApi` whose worker is ran in the background, and a `SocketAddr` to an HTTP
 	// server that runs in the background as well.
 	macro_rules! build_api_server {
 		() => {{
+			macro_rules! tokio_run {
```
Comment (tomusdrw) [inline client/offchain/src/api/http.rs]: Not sure if the number of repetitions is worth a macro. We could either inline it or just use a closure?

Comment (Xanewok) [reply client/offchain/src/api/http.rs]: We can't use closures since the two futures differ in concrete types (this would require a generic closure, it's what I tried originally) - I can inline it or use a helper function :+1:

**Comment by Xanewok** [comment]
Wasm build fails on `cargo build --target=wasm32-unknown-unknown -p sc-consensus-aura` due to pulling in optional `net2` dependency of hyper but I'm opting out of default features... Hopefully it's not feature conflating Cargo bug; will investigate.

File: client/offchain/src/api/http.rs (hunk 1 above)
Comment (Xanewok) [reply client/offchain/src/api/http.rs]: Used a generic helper function.

**Comment by Xanewok** [comment]
If I were to guess, I'd say it's the new `hyper-rustls` here (by default) including `runtime` feature for `hyper` but it seems that the 0.13 version is also pulled in wasm in https://github.com/paritytech/substrate/blob/a9680b40469c8180e5b6b083c01dc04f69e4037c/utils/grafana-data-source/Cargo.toml#L11
hence we unfortunately conflate features and pull in the runtime to wasm accidentally.

Cargo features :angry:

**Comment by gavofyork** [comment]
web-wasm failing?

File: client/offchain/Cargo.toml [hunk 2]
```diff
@@ -27,14 +26,14 @@ sc-network = { version = "0.8", path = "../network" }
 sc-keystore = { version = "2.0.0", path = "../keystore" }
 
 [target.'cfg(not(target_os = "unknown"))'.dependencies]
-hyper = "0.12.35"
-hyper-rustls = "0.17.1"
+hyper = { version = "0.13.1", default-features = false, features = ["stream"] }
```
Comment (tomaka) [inline client/offchain/Cargo.toml]: I think you're missing features here anyway, as `hyper` needs the `tcp` or `runtime` feature in order to use tokio.

File: client/offchain/Cargo.toml [hunk 3]
```diff
@@ -27,14 +26,14 @@ sc-network = { version = "0.8", path = "../network" }
...
+hyper-rustls = "0.19"
 
 [dev-dependencies]
 sc-client-db = { version = "0.8", default-features = true, path = "../db/" }
 env_logger = "0.7.0"
 substrate-test-runtime-client = { version = "2.0.0", path = "../../test-utils/runtime/client" }
-tokio = "0.1.22"
+tokio = "0.2"
```
Comment (tomaka) [inline client/offchain/Cargo.toml]: Have you tried putting that in `target.cfg(not(unknown)).dev-dependencies`?

File: client/offchain/Cargo.toml (hunk 2 above)
Comment (Xanewok) [reply client/offchain/Cargo.toml]: You're right, I originally copied it from `grafana-data-source` but forgot to change it, meanwhile `hyper-rustls` enabled the `hyper/runtime` via https://github.com/ctz/hyper-rustls/blob/f51987a477af6d104783dee3b354e3db244f61a4/Cargo.toml#L29.

I'll fix it to pull all default features here for clarity.

File: utils/grafana-data-source/Cargo.toml [hunk 4]
```diff
@@ -20,4 +18,6 @@ futures-timer = "3.0.1"
 derive_more = "0.99"
 
 [target.'cfg(not(target_os = "unknown"))'.dependencies]
+hyper = { version = "0.13.1", default-features = false, features = ["stream"] }
```
Comment (tomaka) [inline utils/grafana-data-source/Cargo.toml]: Nit: many people just don't care, but I try to enforce alphabetical ordering.
