### PR TITLE
Make network_config_path an Option

### LINKED ISSUE #5611: Browser node panic on current_dir call
**Backtrace**
```
panicked at 'current directory must exist: Custom { kind: Other, error: "operation not supported on wasm yet" }', /home/akru/.cargo/git/checkouts/substrate-7e08433d4c370a21/f830567/utils/browser/src/lib.rs:52:10

Stack:

Error
    at imports.wbg.__wbg_new_59cb74e423758ede (http://localhost:8000/pkg/node_cli.js:380:19)
    at console_error_panic_hook::hook::he31ca500bfbb591f (wasm-function[4398]:0x89a833)
    at core::ops::function::Fn::call::hc216e029665ec866 (wasm-function[17651]:0xb8632b)
    at std::panicking::rust_panic_with_hook::h867e681bd1540878 (wasm-function[10575]:0xaf657a)
    at rust_begin_unwind (wasm-function[13790]:0xb685e7)
    at core::panicking::panic_fmt::h3385088abad2ae65 (wasm-function[14652]:0xb74b64)
    at core::option::expect_none_failed::h02ac17d8100488e3 (wasm-function[12437]:0xb48480)
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h85e8fecb4be13745 (wasm-function[199]:0x1affb6)
    at wasm_bindgen_futures::task::singlethread::Task::run::hefcada778f4d4166 (wasm-function[9702]:0xac2c76)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h9a938d1595776dc7 (wasm-function[8887]:0xa897cb)
```

**Error**

Looks like `env::current_dir` isn't available in the browser.

https://github.com/paritytech/substrate/blob/master/utils/browser/src/lib.rs#L52
```rust
		Default::default(),
		&std::env::current_dir().expect("current directory must exist"),
	);
	network.boot_nodes = chain_spec.boot_nodes().to_vec();
```

### PR DESCRIPTION
**Pull request by expenses**
Closes #5611.

### CODE REVIEW

**Comment by cecton** [comment]
> don

Ah! Actually that was what I was thinking about. The only occurrence of it I saw was to create the directory. Good to hear that it will finally be used.

File: client/network/src/config.rs [hunk 1]
```diff
@@ -384,7 +384,7 @@ impl NetworkConfiguration {
 			"test-node",
 			"test-client",
 			Default::default(),
-			&std::env::current_dir().expect("current directory must exist"),
+			Some(std::env::current_dir().expect("current directory must exist")),
```
Comment (cecton) [inline client/network/src/config.rs:387]: Check the commit history but I think this can be `None`. Those are used only in some specific test I think

Comment (cecton) [reply client/network/src/config.rs:387]: Actually you don't even need to check the logs. As @tomaka said, it wasn't used at all anywhere so you can replace all of them to None instead of the current directory

Comment (expenses) [reply client/network/src/config.rs]: Oh yeah, that makes sense.

File: client/cli/src/commands/mod.rs [hunk 2]
```diff
@@ -173,7 +173,7 @@ macro_rules! substrate_cli_subcommands {
 				&self,
 				chain_spec: &::std::boxed::Box<dyn ::sc_service::ChainSpec>,
 				is_dev: bool,
-				net_config_dir: &::std::path::PathBuf,
+				net_config_dir: Option<::std::path::PathBuf>,
```
Comment (cecton) [inline client/cli/src/commands/mod.rs:176]: You can remove the option as this will always be provided in the cli context
