### PR TITLE
Fix reliance on non-empty NodeInfo::endpoints

### LINKED ISSUE #6976: Panic in peer_info.rs seen in tests
The following line has just panicked for me in a unit test: https://github.com/paritytech/substrate/blob/1aef04351c286427f720a811ccf43d0605ef4528/client/network/src/peer_info.rs#L139

There is indeed a misunderstanding somewhere.
The information about a node are kept even after the node disconnects, and as such `endpoints` can reasonably be empty.

cc https://github.com/paritytech/substrate/issues/5881

### PR DESCRIPTION
**Pull request by kpp**
Fix #6976

### CODE REVIEW

File: client/network/src/peer_info.rs [hunk 1]
```diff
@@ -138,13 +138,16 @@ pub struct Node<'a>(&'a NodeInfo);
 
 impl<'a> Node<'a> {
 	/// Returns the endpoint of an established connection to the peer.
-	pub fn endpoint(&self) -> &'a ConnectedPoint {
-		&self.0.endpoints[0] // `endpoints` are non-empty by definition
+	///
+	/// Returns `None` if we are disconnected. It can happen when we are
+	/// disconnected, however the node is still in cache for `CACHE_EXPIRE` period.
```
Comment (tomaka) [inline client/network/src/peer_info.rs:143]:
```suggestion
	/// Returns `None` if we are disconnected from the node.
```

I don't think it's worth going into details.

**Review by tomaka — APPROVED** [review]

**Review by tomaka — APPROVED** [review]

**Comment by tomaka** [comment]
bot merge
