### PR TITLE
Properly log sealing and the newly created proposal hash from aura

### LINKED ISSUE #1138: In Aura, the block hash when logging a proposed block is wrong
because the consensus engine adds a new digest item for the seal, the hash changes after the log item is issued.

### PR DESCRIPTION
**Pull request by gnunicorn**
Fixes #1138.

I opted for keeping the mentioned message but rephrase it slightly, because it still contains other useful information and is a good 
default in non-aura cases. Instead I added another message post pre-sealing in aura to announce the hash change, that felt more explicit 
and cleaner to me.

Run with `RUST_LOG=info node` now announces them as:
```
2019-01-11 13:50:41 Prepared block for proposing at 1 [hash: 0xe07f9bcda5e8cdf4d1d2cd5ed5787b8a7d471cf4a269b5f32dfdd6871bdb5904; 
parent_hash: 0x7171…78a8; extrinsics: [0xad52…0fdd]]
2019-01-11 13:50:41 Pre-sealed block for proposal at 1. Hash now 0x9923b1c5cc870c25175c65dd32caeb5661c36e74f1a92c7becf171e98bb74c08, 
previously 0xe07f9bcda5e8cdf4d1d2cd5ed5787b8a7d471cf4a269b5f32dfdd6871bdb5904.

```

### CODE REVIEW

File: core/consensus/aura/src/lib.rs [hunk 1]
```diff
@@ -316,7 +317,7 @@ pub fn start_aura<B, C, E, I, SO, Error>(
 							signature,
 						);
 
-						let import_block = ImportBlock {
+						let import_block : ImportBlock<B> = ImportBlock {
```
Comment (gavofyork) [inline core/consensus/aura/src/lib.rs]: style:
```suggestion
						let import_block: ImportBlock<B> = ImportBlock {
```
