### PR TITLE
wrong name regex to filter url when provide --name=www as parameter in cli

### LINKED ISSUE #14574: wrong name regex to filter url when provide `--name=www` as parameter in cli
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

when using `--name` parameter and the value contains word `www`, the regex in the code will think this is a url and return error and exit.
However we should allow user to use the word `www` for it's a normal word.

The reason is the wrong regex in function:

https://github.com/paritytech/substrate/blob/c446786a498dee7b413de101efc3c339d3eddf44/client/cli/src/commands/run_cmd.rs#L395-L414

In L407
```rust
	let invalid_patterns = r"(https?:\\/+)?(www)+";
```
The `\` in this part should be `/\` to let regex can recognize it.

Thus, it at least should be (refer to linker https://uibakery.io/regex-library/url):
```rust
	let invalid_patterns = r"^https?:\/\/";
```

For the preview regex has filtered the char `.`, so we just need to find out the schema part.

### Steps to reproduce

example:
```bash
# just www
./target/release/substrate --tmp --dev --name=www
Error: Input("Invalid node name 'www'. Reason: Node name should not contain urls. If unsure, use none.")
# contains www
./target/release/substrate --tmp --dev --name=aawww
Error: Input("Invalid node name 'aawww'. Reason: Node name should not contain urls. If unsure, use none.")

./target/release/substrate --tmp --dev --name=wwwaa
Error: Input("Invalid node name 'wwwaa'. Reason: Node name should not contain urls. If unsure, use none.")
```

### PR DESCRIPTION
**Pull request by atenjin**
close #14574 

In this pr, we just filter `http://` `https://` prefix in the string, not including word `www`

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by michalkucharczyk — APPROVED** [review]

**Review by koute — APPROVED** [review]
*Technically* URLs don't necessarily have to be for HTTP(S), so maybe we should just disallow URLs for *any* protocol?

**Review by melekes — APPROVED** [review]

**Comment by michalkucharczyk** [comment]
> _Technically_ URLs don't necessarily have to be for HTTP(S), so maybe we should just disallow URLs for _any_ protocol?

had the same thought

**Comment by atenjin** [comment]
@michalkucharczyk hey another thing, can this hotfix pr cherry pick to polkadot-0.9.43 branch? oh maybe this contains in polkadotv1.0.0 is also ok

**Comment by bkchr** [comment]
@atenjin I don't see that this is a critical change that needs to be backported

**Comment by atenjin** [comment]
@bkchr sorry in our project, we are using this substrate branch in our chain, we meet this bug in our running service.
We can not ensure the time for the next polkadot version, so if this can be moved to that branch is more better

**Comment by bkchr** [comment]
Just don't remove the www from the name of your node. These names are only required for telemetry and nothing else and telemetry isn't important.

File: client/cli/src/commands/run_cmd.rs [hunk 1]
```diff
@@ -404,7 +404,7 @@ pub fn is_node_name_valid(_name: &str) -> std::result::Result<(), &str> {
 		return Err("Node name should not contain invalid chars such as '.' and '@'")
 	}
 
-	let invalid_patterns = r"(https?:\\/+)?(www)+";
+	let invalid_patterns = r"^https?:\/\/";
```
Comment (ggwpez) [inline client/cli/src/commands/run_cmd.rs:407]: `let invalid_patterns = r"^https?:\\/\\/";`

Instead?

Comment (andresilva) [reply client/cli/src/commands/run_cmd.rs:407]: I think you don't even need to escape the `/` when using raw string, so just `r"^https?://"` should work. Also none of the tests would catch this since the URLs also include a `.` so this condition is never tested.

Comment (andresilva) [reply client/cli/src/commands/run_cmd.rs:407]: https://github.com/paritytech/substrate/pull/14593
