### PR TITLE
Fix #7629

### LINKED ISSUE #7629: Error: Attempted to send notification on unknown protocol: "/paritytech/grandpa/1"
This line is being printed occasionally on our nodes.

https://github.com/paritytech/substrate/blob/8febf11a1ab7870c5284ae06951045c5d450cac2/client%2Fnetwork%2Fsrc%2Fservice.rs#L637

### PR DESCRIPTION
**Pull request by tomaka**
Fix #7629 

This downgrade the `error` into a `debug` log.

The error happens if we try to send a notification on a substream that has already been closed.
Considering that sending notifications happen in parallel of receiving events, this can happen in completely normal situations. It was a mistake to have it as an `error`.

Also cc #6756

### CODE REVIEW

**Review by romanb — APPROVED** [review]

File: client/network/src/service.rs [hunk 1]
```diff
@@ -668,9 +668,9 @@ impl<B: BlockT + 'static, H: ExHashT> NetworkService<B, H> {
 				sink.clone()
 			} else {
 				// Notification silently discarded, as documented.
-				log::error!(
+				log::debug!(
 					target: "sub-libp2p",
-					"Attempted to send notification on unknown protocol: {:?}",
+					"Attempted to send notification on closed substream: {:?}",
```
Comment (mxinden) [inline client/network/src/service.rs:673]: Can one be sure that the substream was open at some point in time?
```suggestion
					"Attempted to send notification on missing or closed substream: {:?}",
```

**Review by mxinden — APPROVED** [review]

**Comment by tomaka** [comment]
bot merge
